### ISSUE TITLE
Please compatible with ProtocolSupport

### ISSUE THREAD

**Issue by jiongjionger** [filoghost/HolographicDisplays#10]
Please compatible with ProtocolSupport :)
link: http://www.spigotmc.org/resources/protocolsupport.7201/
1.7.2/1.7.10 client join 1.8/1.8.3 server can not see HolographicDisplays

**Comment by filoghost** [comment]
It's up to the plugin making holograms compatible.

**Comment by jiongjionger** [comment]
It's hard for them to be compatible with holograms. Because 1.7.2/1.7.10 client does not support armor stand.And i try to add ProtocolSupport remap code,it does not work.
Could you please use WitherSkull and Horse instead Armorstand?

* Sorry for my poor English.

**Comment by filoghost** [comment]
I did it for 1.7 -> 1.8 (the patch, on Spigot), it should not be difficult to make it for 1.8 -> 1.7 for the author. And sorry if it sounds rude, but it's not up to me to solve the problem if another plugin allows more versions.

**Comment by jiongjionger** [comment]
It's fine. Thank you for your reply :)
