### ISSUE TITLE
Hologram Variables Only Working For Me (1.13.1)

### ISSUE THREAD

**Issue by TheAgentRAINBOW** [filoghost/HolographicDisplays#101]
# So, I have a hologram set up to display a user's display name...
However, it only changes when I change my name. So other players see my name, not their own.
Imagine my username was "1". Everyone looking at the hologram would see "1".
But then I change it to "2", it changes for me and everyone else can see it.
But for whatever reason they only see what I see, not what they're meant to see.
https://gyazo.com/6d4dcf3d752eed4296941a76ee7ffe4b

Thanks in advance,
TheAgentRAINBOW

**Comment by Echoblast53** [comment]
I came across this issue as well, and leaving the area and come back would cause the oldest mc player to display their custom info for all in the area to see. To fix this, I had to restart my server :S

**Comment by CrabMustard** [comment]
I've noticed this problem myself. Additionally, I've also encountered similar issues in other plugins on 1.13 using ProtocolLib, such as right clicking a chair causes someone else to sit in it in FurnitureLib, so this might be an issue on the side of ProtocolLib.

**Comment by Echoblast53** [comment]
Calling rainbow (or any other refresh property, including the aforementioned "edit the holo" action) doesn't correctly show the right custom ProtocolLib display: if I request {player}, it will, without the refresh property, correctly display the right username. However, calling a refresh property on {player} will cause it to display the oldest player there, no matter who is viewing the holo. (1.12.2)

**Comment by filoghost** [comment]
This has been fixed in https://github.com/filoghost/HolographicDisplays/commit/485ea9feff7963e621f487e57c7def62e507f273, please try a new development build from https://ci.filoghost.me/job/HolographicDisplays/

**Comment by Echoblast53** [comment]
Works like a charm. Nice job.
