### ISSUE TITLE
Holograms don't load on server start

### ISSUE THREAD

**Issue by Sikatsu** [filoghost/HolographicDisplays#103]
For some reason my holograms won't load on server restart.

All holograms give an error like this:

WARN Hologram 'cathedralleave' was in the world 'mobarena' but it wasn't loaded.

I tried to turn debug on and see what's wrong but it doesn't tell me.

/hd reload fixes it.

How can the world not be loaded?

**Comment by Sikatsu** [comment]
Adding [Multiverse-Core] to depend instead of softdepend fixes the issue.
But this is more like a workaround then an actual fix. Someone has any idea?

**Comment by sgdc3** [comment]
First hologram load needs to be scheduled, so it runs after any plugin is initialized (such as world managers)

**Comment by filoghost** [comment]
This problem will be discussed here: https://github.com/filoghost/HolographicDisplays/issues/82
