### ISSUE TITLE
Item holograms can be duped using hoppers

### ISSUE THREAD

**Issue by Skuhoo** [filoghost/HolographicDisplays#104]
As the title suggests, players can place hoppers underneath item holograms and the hopper will infinitely pick up the item.

I understand this issue doesn't really affect most use cases of HolographicDisplays, as they're primarily used in areas in which players do not have build permissions. Our server, however, uses them more dynamically and their use includes areas where players can build.

**Comment by sgdc3** [comment]
@Skuhoo are you using the latest dev build? this was fixed some weeks ago

**Comment by Skuhoo** [comment]
@sgdc3 That's my bad. We discovered this bug about a month and a half ago but I just now remembered to open an issue regarding it. I didn't think to check past issues since I didn't see anything about it when we initially discovered the bug. Thanks for the help.
