### ISSUE TITLE
ProtocolLib and Holograhic Rainbow don't mix.

### ISSUE THREAD

**Issue by Echoblast53** [filoghost/HolographicDisplays#105]
Calling rainbow (or any other refresh property) doesn't correctly show the right custom ProtocolLib display: if I request {player}, it will, without the refresh property, correctly display the right username. However, calling a refresh property on {player} will cause it to display the oldest player there, no matter who is viewing the holo.

**Comment by filoghost** [comment]
Duplicate/related to #101
