### ISSUE TITLE
ProtocolLib 4.4.0 crash

### ISSUE THREAD

**Issue by BestMark** [filoghost/HolographicDisplays#109]
After updating the ProtocolLib to 4.4.0 version, such errors began to appear in the log.
https://pastebin.com/2KX8V9YK

**Comment by filoghost** [comment]
Should be fixed in https://github.com/filoghost/HolographicDisplays/commit/7a122a7231009a14c77d1b8917276f2752addf72, please try with a dev build or wait for v2.3.1 on Bukkit Dev.
