### ISSUE TITLE
HolographicDisplays lag Timings

### ISSUE THREAD

**Issue by Kedarin** [filoghost/HolographicDisplays#11]
Hi,
I don't understand why HolographicDisplays get : 
    0.00%	 816.11%	  0.41 s	   408.06 ms	 0.0	       0.0k	 Task:StartupLoadHologramsTask(Single)
My timings : http://timings.aikar.co/?url=11501230

Server version : version git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
HolographicDisplays version : 2.1.10

Thank you,

**Comment by filoghost** [comment]
As the task name says "StartupLoadHologramsTask" it's only executed when the plugin loads. I won't cause any lag.

**Comment by Kedarin** [comment]
Thank's for information
