### ISSUE TITLE
Touchscreen Holograms data resets after /restart

### ISSUE THREAD

**Issue by WizzleBear** [filoghost/HolographicDisplays#110]
Not sure where to put this but I thought here would be good.

I am using Touchscreen Holograms v1.3.2 and Holographic displays v2.3.1. No error is said on startup by Touchscreen Holograms or HD. I don't know what else to put, but if I see something pop up about data being reset in the console, I will be sure to tell you.

**Comment by filoghost** [comment]
This has been fixed in Touchscreen Holograms. Update to 1.4.0 to get the fix.
