### ISSUE TITLE
Hologram show distance

### ISSUE THREAD

**Issue by Sikatsu** [filoghost/HolographicDisplays#113]
Hey,

I've seen some plugins lately adding support for hiding holograms too far away from the player.
Would this be possible to implement? Or is this already possible?

**Comment by filoghost** [comment]
Sorry for the late answer. It would need to be implemented with Protocol Lib, but is there any reason to? Holograms aren't probably a cause of FPS drops client side.

**Comment by Sikatsu** [comment]
It would be nice if it's optional for users with Protocol Lib.
The reason wouldn't be for FPS, but it looks way more neat then holograms thru all the walls and buildings in a distance.

**Comment by filoghost** [comment]
In spigot.yml you can change the tracking range of these two to achieve the effect:
```
world-settings:
  default:
    entity-tracking-range:
      misc: 10
      other: 10
```

Implementing it in Protocol Lib is difficult and time consuming compared to the improvements of this feature.

**Comment by Sikatsu** [comment]
While that indeed works, that setting applies to more then just holograms. It's not the best solution which i'm not a fan of myself. Hoped it was possible to add with protocollib support just like CMI did it with their holograms.
