### ISSUE TITLE
Using latest dev build of HolographicDisplays in Paper 1.13.2 found this WARN

### ISSUE THREAD

**Issue by axemwa** [filoghost/HolographicDisplays#115]
https://pastebin.com/zpCcQBqa

**Comment by axemwa** [comment]
haven't seen it since

**Comment by sgdc3** [comment]
Not a HD related issue i think, you can safely ignore it.

**Comment by axemwa** [comment]
Kwl thanx, its gone now hmm. Strange it isn't HD related I just reported it cause HD was mentioned in the WARN
