### ISSUE TITLE
latest spigot paper update breaks holograms

### ISSUE THREAD

**Issue by BBoyJD10** [filoghost/HolographicDisplays#117]
not wkring on latest build

**Comment by Drc-DEV** [comment]
This is not working due to recent nms changes in Spigot 

https://pastebin.com/0LAj8QL4

**Comment by MiniDigger** [comment]
duplicate of #116 which is fixed already.
use a dev build from here https://ci.filoghost.me/job/HolographicDisplays

**Comment by BBoyJD10** [comment]
doesnt work

**Comment by DarkFort** [comment]
Same problem https://hastebin.com/goqopopoxi.pl
 PaperSpigot 1.13.2

**Comment by MattCM** [comment]
![image](https://user-images.githubusercontent.com/44980073/50366742-8313c680-0573-11e9-952b-68fe7eaae7de.png)
Same issue, on Spigot 1.13.2 new build as of now.

**Comment by MattCM** [comment]
Scrap that, the dev build fixes it, sorry please delete^^

**Comment by filoghost** [comment]
A new version with this fix is being published to Bukkit Dev, I'm closing this issue.
