### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by Zandor300** [filoghost/HolographicDisplays#12]
You should put this on a Maven repository so we can easily add it to our maven project.

**Comment by filoghost** [comment]
I should first use Maven on the entire project - however, I'm busy at the moment and I don't know if I'm going to use Maven.

**Comment by Favorlock** [comment]
I'd highly encourage mavenizing the project. It's not difficult to do and frankly makes it easier for other people to utilize your api without needing to include the source/library in their own repo or downloading it and adding it to their path each time they set up the project.

I think in this day of age maven is the go to dependency management for java.

**Comment by Incomp** [comment]
+1 this

**Comment by MarcinWieczorek** [comment]
I used to use API as it is in a jar, but I figured out how to set up a simple mvn repo.
It's good for now, but please reconsider supporting maven!

```xml
<repository>
    <id>filoghost-repo</id>
    <url>http://novaguilds.pl/repo/</url>
</repository>

<dependency>
    <groupId>com.gmail.filoghost</groupId>
    <artifactId>holographicdisplays.api</artifactId>
    <version>2.1.3</version>
</dependency>
```

**Comment by Locknlol** [comment]
I'd love an officially hosted maven repo! Sorry for the necro, but I feel this is still relevant.

**Comment by MarcinWieczorek** [comment]
http://repo.novaguilds.pl/com/gmail/filoghost/holographicdisplays.api/2.1.3/

**Comment by Locknlol** [comment]
Hey Marcin, I tried using that. In my pom.xml I have:

`
        <repository>
            <id>novaguilds-repo</id>
            <url>http://repo.novaguilds.pl/</url>
        </repository>

        <dependency>
            <groupId>com.gmail.filoghost</groupId>
            <artifactId>holographicdisplays.api</artifactId>
            <version>2.1.3</version>
            <scope>provided</scope>
        </dependency>
`

But it's not recognizing that it's there. "Missing artifact com.gmail.filoghost:holographicdisplays.api:jar:2.1.3"

**Comment by MarcinWieczorek** [comment]
Are those inside repositories and dependencies tags?

**Comment by Locknlol** [comment]
Yes they are. (I have a few so I made it smaller)

**Comment by MarcinWieczorek** [comment]
No idea. I'll try to update tomorrow.

**Comment by KingFaris10** [comment]
Any updates to this?

**Comment by sgdc3** [comment]
filo seems to be very busy recently, don't expect a maven update very soon

**Comment by KingFaris10** [comment]
Oh right, I'll just add it to my local maven repository then.

**Comment by stuntguy3000** [comment]
So...

**Comment by Favorlock** [comment]
@stuntguy3000 it hasn't happened since this thread was created, pretty sure it won't happen sadly.

**Comment by stuntguy3000** [comment]
It's a shame @filoghost is a poor developer for such a popular plugin.

**Comment by sgdc3** [comment]
@stuntguy3000 ... Why don't mavenize thebproject by yourself then? -_- I think that @filoghost is too busy atm to update/enhance his (FREE!!!!!) plugins.

**Comment by MarcinWieczorek** [comment]
He might be too busy, that's why I supplied with a repository and @games647 ported the project to Maven and created a pull request (which has been ignored). No one demands the author to do anything as it is his free will and time to continue HolographicDisplays. This plugin is an API ergo it should support Maven, period. I guess we all got used to the fact that it won't. We came here to help, not to riot.

**Comment by sgdc3** [comment]
@MarcinWieczorek I agree with you, but that message wasn't very polite.

**Comment by MarcinWieczorek** [comment]
Cannot disagree.

**Comment by stuntguy3000** [comment]
@sgdc3 I disagree.

Been 2 years.

![image](https://cloud.githubusercontent.com/assets/1522389/24294065/bc933dc6-10e4-11e7-8cfb-d77d96130544.png)

@filoghost Has outright refused to host a Maven Repository, despite how easy it is to host (GitHub repository is free!). It's a poor attitude to have and he deserves everything coming his way by refusing to support developers like this.

This plugin is massive, playing the excuse of it being a free plugin is not suitable for a project of this scale.

@MarcinWieczorek I demand @filoghost to step up his game, but we all know that won't happen/

**Comment by Favorlock** [comment]
@filoghost I suggest you close this issue considering you haven't mavenized the project after this much time. It's pointless to leave it open when you aren't willing to put in the effort to resolve the issue.

**Comment by sgdc3** [comment]
@Favorlock Who said that?

**Comment by Favorlock** [comment]
@sgdc3 "I'm busy at the moment and I don't know if I'm going to use Maven."

That already shows a lack of willingness to begin. The 2 years of silence just adds to that.

**Comment by sgdc3** [comment]
Let him manage his issuetracker as he wants.

**Comment by Favorlock** [comment]
So you're saying that it's acceptable to let people manage a public project in a poor manner? Just because it is public doesn't imply that it can't and shouldn't be held to a higher standard. Frankly, if he hasn't responded in 2 years he probably isn't going to respond to this issue ever again, as such the issue should be closed and the case put to rest for good.

**Comment by sgdc3** [comment]
Anyway, temp repository for latest version: http://ci.xephi.fr/plugin/repository/everything/com/gmail/filoghost/holographicdisplays/2.2.5/

**Comment by stuntguy3000** [comment]
"temp repository"

That's as bad as not having one. If you depend on a repository you can't trust, it's worse than using a local jar.

**Comment by sgdc3** [comment]
You can trust it, we use it to host authme related dependencies and other projects.

**Comment by sgdc3** [comment]
Ok, i'm having some issue with the mvn install:install-jar scope, one moment

**Comment by stuntguy3000** [comment]
🤣

**Comment by filoghost** [comment]
I've been doing only maintenance on my plugins for years now. Time is the reason, I'm giving priority to more important stuff.

I'm not going to just blindly accept any pull request without even knowing what is doing, I want to learn Maven and possibly setup Jenkins for development builds.

I will try to add maven support this summer, no promise though.

**Comment by MarcinWieczorek** [comment]
Yeah maven requires a lot of changes because of its directory tree. I can offer my help.

**Comment by MarkehMe** [comment]
I will publish https://github.com/redstone/HolographicDisplays to a maven repository.

**Comment by filoghost** [comment]
https://github.com/filoghost/HolographicDisplays/commit/dcee93e3e9ceb6a8d7a3d472a1182ab3ea05601a better late than never, also thanks to @markhughes and @sgdc3 for helping me

**Comment by Incomp** [comment]
Sweet. Thanks a bunch.
