### ISSUE TITLE
Lines keep merging together & Server Status not working.

### ISSUE THREAD

**Issue by Zilacon** [filoghost/HolographicDisplays#120]
Hello i wanted to use your plugin on all of my servers to replace my walls of signs. I have 1.6.4, 1.7.10, and 1.13.2 servers.

When i go to setup a display on my 1.6.4 vanilla HUB it just merges every single line into 1. If i reload the plugin it momentarily seperates them but then merges them again. Ive tried reloading the server and restarting the server. Even changing the line spacing in the config. Nothing is working.

It seems after line 3 it makes a new line to merge. So lines 1-3 are merged into line 1 and lines 4-6 are merged into line 4.

Any idea on how to fix this?

Using HD 2.1.13 for 1.6.4 Spigot.

EDIT: After changing the spacing to 1.0 in the config all lines show up but are spaced like 4 lines apart. When i use anything below 1 it merges them together. so 0.99 and below.

EDIT 2: Enabling the pinger in the config and adding the server IP's also does not work. When adding {status: HUB} in the line it just shows "Offline" even though i am obviously on the hub. I have tried IP:Port, IP, Domain, Domain:Port, even 127.0.0.1:Port, and localhost:port. None of these work. I have tried multiple servers and multiple bungeecords IP's/Domain's.

EDIT 3: It seems like if you place it ANYWHERE where there is a sign currently, or was there in the past, it will never display correctly. If you move it to an area that has never had a sign there before, it does not merge the lines.

**Comment by filoghost** [comment]
Sorry, 1.6.4 and 1.7.10 aren't supported anymore. I also have no idea how to fix it.
