### ISSUE TITLE
Holograms vanish when you look at them (1.7.10 Cauldron/Thermos)

### ISSUE THREAD

**Issue by Zilacon** [filoghost/HolographicDisplays#122]
As the title states when you look at the holograms EVERY hologram on the server vanishes. If you look away from them they all appear. I am aware of the issues with spigot tracking and activation distance settings while trying to get 1.6.4 to work but that does not seem to be the case on here.

Any ideas on how to solve this problem? I am trying version 2.2.5 and 2.2.6.

**Comment by Zilacon** [comment]
@filoghost poke.

**Comment by filoghost** [comment]
Sorry, that version isn't supported anymore. I remember a client side bug on forge 1.7.10 where players were not able to see floating items (HD's icons). Try using a vanilla client, that's all I know.
