### ISSUE TITLE
Add support for NBT data in icons

### ISSUE THREAD

**Issue by RedstoneFuture** [filoghost/HolographicDisplays#128]
Would you like add the option to define a icon material with the key of a specify player-skull?

e.g. 

> {Skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjFhNzNkODM2NmNhZWVhNmFlZTY1NmFkZWNkMWUzYmQ1ZjhmN2JlNTcxYTNlMjFjN2FjYjc4ZDQ3NWNiIn19fQ=="}

**Comment by filoghost** [comment]
I would expand this to allow all NBT values on icons. Something like:
`ICON: material {... nbt data ...}`

**Comment by Elxafil** [comment]
Will you make sure to add in the 1.14 newly added custom_model_data NBT?

**Comment by filoghost** [comment]
https://github.com/filoghost/HolographicDisplays/commit/42cc919035db87af947f0e31cc785aac1c681652

@Elxafil You can use any NBT data value, including custom_model_data.
