### ISSUE TITLE
TouchHandler dont work

### ISSUE THREAD

**Issue by Eternirya** [filoghost/HolographicDisplays#131]
HolographicDisplays version: 2.3.2
Server version: 1.11.2
Code: https://pastebin.com/gMiGmUJd

Don't send message when i right clicked.

I have try PickupHandler and its work normally.

**Comment by filoghost** [comment]
Could be solved now, could you retry on the latest dev build please? https://ci.codemc.org/job/filoghost/job/HolographicDisplays/
