### ISSUE TITLE
1.14

### ISSUE THREAD

**Issue by DDuart** [filoghost/HolographicDisplays#132]
Hello, mc 1.14 is out! Can you add support to 1.14?

**Comment by TheMonDon** [comment]
I don't know, i think this plugin is dead.

**Comment by sgdc3** [comment]
@TheMonDon not at all xD Be patient!

**Comment by filoghost** [comment]
Support has been added in dev builds: https://ci.filoghost.me/job/HolographicDisplays

**Comment by Pangamma** [comment]
@filoghost  @sgdc3  Can you guys get a discord? Please? It would be super useful.

**Comment by filoghost** [comment]
@Pangamma No, sorry. I barely have time to update the plugins.

**Comment by Pangamma** [comment]
@filoghost  I updated one of your plugins for you, if that helps.  https://github.com/filoghost/ChestCommands/pull/14/files
