### ISSUE TITLE
1.14.1 support

### ISSUE THREAD

**Issue by Sikatsu** [filoghost/HolographicDisplays#136]
Currently doesn't work on 1.14.1.

**Comment by YourCoalAlt** [comment]
I think because you closed this you figured it out, but as long as you have the latest ProtocolLib build and the latest HolographicDisplays build, it should work fine.

**Comment by Sikatsu** [comment]
Yeah, I really just forgot to upload the right build, thanks for the reply
though!

Op do 16 mei 2019 01:24 schreef YourCoalAlt <notifications@github.com>:
