### ISSUE TITLE
Error /Hd edit

### ISSUE THREAD

**Issue by Onydarius** [filoghost/HolographicDisplays#137]
![image](https://user-images.githubusercontent.com/50853095/58062248-41497500-7b3f-11e9-9d62-0a2eb1cc17f5.png)
![image](https://user-images.githubusercontent.com/50853095/58062253-46a6bf80-7b3f-11e9-9a69-983e224b0396.png)

**Comment by filoghost** [comment]
You should run Spigot, not CraftBukkit.
