### ISSUE TITLE
VisibilityManager.showTo method not working in 1.14

### ISSUE THREAD

**Issue by koca2000** [filoghost/HolographicDisplays#139]
Hi!

I am developer of NoteBlockMusicPlayer and I am using `VisibilityManager` to show different holograms to op and non-op players. However in 1.14 the `showTo` method does not work.

Log: https://pastebin.com/UfrWub8b

HolographicDisplays: 2.3.3 Jenkins Build 72
ProtocolLib: 4.5.0 Jenkins Build 8

**Comment by SkytAsul** [comment]
Same for me: https://pastebin.com/nbueXCj8

**Comment by filoghost** [comment]
Could be related to https://github.com/filoghost/HolographicDisplays/issues/135. Are you using Spigot 1.14, 1.14.1 or 1.14.2?

**Comment by koca2000** [comment]
I tried 1.14.2, but some user reported same issue when using 1.14.1.

**Comment by SkytAsul** [comment]
1.14.2, and I've got the same with 1.14.

**Comment by filoghost** [comment]
Should be fixed by https://github.com/filoghost/HolographicDisplays/commit/644d58c80ef6ab1734301785b64b5cf683484cc3

**Comment by koca2000** [comment]
No errors now, but there is another problem related to it. When you use two holograms at same location and make only one visible, the one that si created first is at right position, but the second one is lifted aprox two blocks. On 1.13 it works fine. Tested with 1.14.2.

**Comment by jascotty2** [comment]
I'm also having a really weird issue with VisibilityManager in 1.14.2:
This snippit is supposed to hide the hologram from all players until added later with VisibilityManager.showTo, but what I'm seeing is that the hologram is always visible:
```
final Hologram hologram = HologramsAPI.createHologram(plugin, location);
hologram.getVisibilityManager().setVisibleByDefault(false);
hologram.appendTextLine("test");
```

**Comment by SkytAsul** [comment]
There are many problems related with the VisilbityManager, I've created another issue: https://github.com/filoghost/HolographicDisplays/issues/169

**Comment by orblazer** [comment]
Hello, This bug is steel present.

When i use `VisibilityManager#showTo` this is doesn't apear to player but if i toggle in Spectator i see armor stand.
**NOTE** : This is despawn the line if no set `setVisibleByDefault` to `false`

My code :
```java
// Init npc
Hologram hologram = HologramsAPI.createHologram(plugin, location);
hologram.getVisibilityManager().setVisibleByDefault(false);
hologram.appendTextLine("test");

// When player join
hologram.getVisibilityManager().showTo(player);
```

Versions :
- **Paper** : git-Paper-175 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
- **HolographicDisplays** : 2.3.3-SNAPSHOT (build#87)
- **ProtocolLib** : v4.5.0-SNAPSHOT (build#16)

Thanks.

**Comment by filoghost** [comment]
Bug should be fixed in https://github.com/filoghost/HolographicDisplays/commit/70e070ac11a9164729aa69c64f6e1c106eece6aa. Please try the new dev build.

**Comment by orblazer** [comment]
Yes this is fixed, thanks you !
