### ISSUE TITLE
ReWorld support

### ISSUE THREAD

**Issue by Sikatsu** [filoghost/HolographicDisplays#141]
Hey,

I moved from multiverse to ReWorld, however the holograms load before the world now causing the holograms not to be enabled. Could you add support for ReWorld?

https://www.spigotmc.org/threads/reworld-paid.327940/

Kind regards,

Sikatsu

**Comment by filoghost** [comment]
This should probably be fixed by the creator of ReWorld for now. Holographic Displays doesn't support dynamic world loading, and ReWorld should load the worlds at startup (I don't know why it would load them later).

**Comment by Sikatsu** [comment]
@filoghost 

I asked the developer of ReWorld and he pointed me here, i'll try to contact him again in that case.
Sorry or the duplicate.

**Comment by GCD56** [comment]
Try something really stupid just for kicks: Rename Reworld jar to AReWorld jar and start the server (use a DEV) you might be able to trick the thing to load reworld first if it is loading alphabetically. Stranger things have worked in the past.

**Comment by Sikatsu** [comment]
Just tried doing that on a test server, but it didn't change anything sadly.

The developer of ReWorld says this is something that needs to be fixed by the HolographicDisplays developer.

Guess I just bought a premium plugin for nothing since it doesn't work with HD..

**Comment by GCD56** [comment]
HolographicDisplays needs updated to 1.14.2 anyway, if the guy ever gets around to it that might fix it.
HolographicDisplays could put a soft depend in plugin.yml for ReWorld so it will load after ReWorld if it exists.
Good luck

**Comment by Sikatsu** [comment]
That's also what I tried doing together with the ReWorld developer, without any luck.

HolographicDisplays works on 1.14.2 btw, using the devbuilds.

**Comment by filoghost** [comment]
The new beta version should work with unloaded worlds.
