### ISSUE TITLE
Getting a 1.14.2 Error Dev Build

### ISSUE THREAD

**Issue by BobbyTowers** [filoghost/HolographicDisplays#150]
Getting this error - https://pastebin.com/urVn4Y4z

**Comment by i9hdkill** [comment]
Caused by this recent change in spigot
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/fa71719350d15fd5d5091c4fe45ff2e86a95371c#nms-patches/Entity.patch

**Comment by filoghost** [comment]
Those are probably 2 different errors, https://github.com/filoghost/HolographicDisplays/issues/148 and https://github.com/filoghost/HolographicDisplays/issues/135
