### ISSUE TITLE
ChunkUnloadEvent EventException: null on start up, server crash ticking entity

### ISSUE THREAD

**Issue by YourCoal** [filoghost/HolographicDisplays#152]
Startup: https://pastebin.com/3SWsTPVa

Crash: https://pastebin.com/xigRmMc7

**Comment by zachrocks22** [comment]
I too also have this issue. It's on 1.14.2 Paper Spigot and begins from build number 65. Where they Flag GS4QueryEvent as async (see [here](https://github.com/PaperMC/Paper/commit/523545e80922b29b50c5c0b77659895729e3e851)) I really hope the issue can get resolved :)

**Comment by filoghost** [comment]
See https://github.com/filoghost/HolographicDisplays/issues/148
