### ISSUE TITLE
java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by Nogapra** [filoghost/HolographicDisplays#156]
Hello
PaperMC : Paper version git-Paper-65 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
Holographic Display 2.3.3.Snapshot.80

I have a problem that is not too serious (see the end of the pastebin) but all the plugins I use on my test server and that have a dependency on holographic display me the same error.

I wanted to know if this came from the fact that the dev of the other plugins is not taken the API holographic display into account or if it came from the use of PaperMC build 65

Sorry for my english
Thanks and good work

French Version :
J'ai un problème qui n'est pas trop grave (voir la fin du pastebin) mais tout les plugins que j'utilise sur mon serveur de test et qui ont une dépendance à Holographique Display me remonte la même erreur.

Je voulais savoir si cela venait du fait que les dev des autres plugins n'est pas pris l'API Holographic Display en compte ou si cela venait de l'utilisation de PaperMC Build 65

Merci et bon travail 

https://pastebin.com/9C4CB3x1

**Comment by filoghost** [comment]
Has been fixed, see #148
