### ISSUE TITLE
1.14.2 placeholderapi support not work

### ISSUE THREAD

**Issue by successed** [filoghost/HolographicDisplays#161]
1.14.2 placeholderapi support not work

http://prntscr.com/o02zfu

Holographic version : http://prntscr.com/o02zll

Server version paper latest 1.14.2 #76

**Comment by HexedHero** [comment]
It doesn't support PlaceholderAPI

you have to use https://www.spigotmc.org/resources/holographicextension.18461/ for PlaceholderAPI

**Comment by successed** [comment]
we need PlaceholderAPI support.

**Comment by HexedHero** [comment]
and you have it
https://www.spigotmc.org/resources/holographicextension.18461/

its legit drop and install and don't need to do anything else...

**Comment by successed** [comment]
there is not work mean.

**Comment by HexedHero** [comment]
It does work...

"It also injects your favourite placeholders from PlaceholderAPI (requires ProtocolLib)"

**Comment by successed** [comment]
> It does work...
> 
> "It also injects your favourite placeholders from PlaceholderAPI (requires ProtocolLib)"

Check this out you idiot: https://hastebin.com/tufelenodo.pl

**Comment by HexedHero** [comment]
> > It does work...
> > "It also injects your favourite placeholders from PlaceholderAPI (requires ProtocolLib)"
> 
> Check this out you idiot: https://hastebin.com/tufelenodo.pl

How about you use the right protocollib version... "idiot"
https://cdn.hexedhero.com/u/IsH5cAZEyL.jpg

**Comment by successed** [comment]
> > > It does work...
> > > "It also injects your favourite placeholders from PlaceholderAPI (requires ProtocolLib)"
> > 
> > 
> > Check this out you idiot: https://hastebin.com/tufelenodo.pl
> 
> How about you use the right protocollib version... "idiot"
> https://cdn.hexedhero.com/u/IsH5cAZEyL.jpg

4.5.0-SNAPSHOT "idiot"

**Comment by HexedHero** [comment]
https://ci.codemc.org/job/filoghost/job/HolographicDisplays/

**Comment by successed** [comment]
> https://ci.codemc.org/job/filoghost/job/HolographicDisplays/

i have HolographicDisplays-2.3.3-SNAPSHOT.jar "idiot"

READ:
İ HAVE 1.14.2 SERVER AND İ DON'T HAVE ANY OLD VERSİON PLUGİNS.

**Comment by HexedHero** [comment]
> > https://ci.codemc.org/job/filoghost/job/HolographicDisplays/
> 
> i have HolographicDisplays-2.3.3-SNAPSHOT.jar "idiot"
> 
> READ:
> İ HAVE 1.14.2 SERVER AND İ DON'T HAVE ANY OLD VERSİON PLUGİNS.

Then it's a you issue, I have all 4 latest plugins, HD, HDE, PAPI and ProtLib and its working perfect on latest 1.14.2 Spigot.

**Comment by successed** [comment]
there is not work mean.

**Comment by simpleauthority** [comment]
This is a warzone.

**Comment by filoghost** [comment]
No need to call people names, especially when you're clearly in the wrong. There is already an issue open for PlaceholderAPI support: https://github.com/filoghost/HolographicDisplays/issues/100
