### ISSUE TITLE
Cannot use capitals in hologram names

### ISSUE THREAD

**Issue by HexedHero** [filoghost/HolographicDisplays#162]
If you change the name of your hologram to have capitals in your data file you cannot do anything with it in-game

https://cdn.hexedhero.com/u/SbJExPklA7.jpg

**Comment by Escyth** [comment]
Please implement that fix, it allows for better readability when listing all of the holograms.

**Comment by filoghost** [comment]
Added in https://github.com/filoghost/HolographicDisplays/commit/be96a5c5fda36d9c70e2732d112c2ae4e9482f14, try the latest dev build: https://ci.codemc.org/job/filoghost/job/HolographicDisplays
