### ISSUE TITLE
onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by MeesterMaarten** [filoghost/HolographicDisplays#163]
I'm using the latest HolographicDisplays build with the UltimateStacker plugin on the latest Spigot-1.14.2-build and the console seems to be spamming: 'onPacketSending(PacketEvent)' - Cannot retrieve entity from ID.

Error: https://pastebin.com/VrtKsine

Thanks in advance!

Maarten.

**Comment by filoghost** [comment]
Update Protocol Lib. If the issue persists, it must be related to https://github.com/filoghost/HolographicDisplays/issues/135
