### ISSUE TITLE
Integrazione AuthMe

### ISSUE THREAD

**Issue by MichaelOfficialYT** [filoghost/HolographicDisplays#165]
Volevo sapere se potevo fare un'ologramma alla hub con gli utenti registrati

**Comment by filoghost** [comment]
There's no integration with AuthMe. You have to register a new placeholder with the official API: https://ci.codemc.org/job/filoghost/job/HolographicDisplays/javadoc/index.html?com/gmail/filoghost/holographicdisplays/api/HologramsAPI.html (see registerPlaceholder)
