### ISSUE TITLE
Hologram Latest dev build - It auto restarts or closes server every 15 minutes and console spam

### ISSUE THREAD

**Issue by AccioAce** [filoghost/HolographicDisplays#168]
Hello,
I notice that hologram is causing major issues for 1.14.2 where it will auto-restart or close every 10-15 minutes as I tested it for some server. Also here's a screenshot of console spam: https://gyazo.com/7955edb2bdfe5510b486f45f58f75092

**Comment by filoghost** [comment]
Download the latest dev build.
