### ISSUE TITLE
BungeeCord - Chest Commands

### ISSUE THREAD

**Issue by RebelLP** [filoghost/HolographicDisplays#17]
Hello,
I would've if you could add to chestcommands for bungeeCord MOTD, and how many players are on a particular server.

I thank you in advance for your answer

**Comment by filoghost** [comment]
Wrong repository, this is Holographic Displays.

**Comment by RebelLP** [comment]
not that! I need what you have written! Would you por us this plugin do it for free?

**Comment by RebelLP** [comment]
Hello,
I'd like you to join Bungee Cord with your plugin ChestCommands. I'd like to go motd witch you should visit a number of players on a particular server. I changed the item will need to play a minigame. When the lobby will have the necessary blue wave and he'll be in the game and that wave will be red. I'd like to tan item varied by color. Like if Lobby will be blue and the necessary wave of change to the blue wave
