### ISSUE TITLE
Exception on server start

### ISSUE THREAD

**Issue by Artuto** [filoghost/HolographicDisplays#173]
Hello. I'm getting the following exception on start: https://gist.github.com/Artuto/777646585bab6feec8ae53f74d0a3ae9

This started to happen when I updated ProtocolLib to 4.5 dev build #9.

Using Paper 1.13.2 and OpenJ9 (OpenJDK 8 and OpenJ9 as JVM).

**Comment by sgdc3** [comment]
Make sure you are running the latest HD dev build: https://ci.codemc.org/job/filoghost/job/HolographicDisplays/

**Comment by Artuto** [comment]
Yep, a dev build fixed it.
