### ISSUE TITLE
1.14.3 support

### ISSUE THREAD

**Issue by Sikatsu** [filoghost/HolographicDisplays#174]
It doesn't seem to enable on spigot 1.14.3. The usual message appears as with any .x bump.

This is just a notify.

**Comment by filoghost** [comment]
What message? I tried and it's working, on the latest dev build.

**Comment by Sikatsu** [comment]
Whoops sorry, seems I had the wrong build somehow.

**Comment by skilledpt** [comment]
its not working for me on 1.14.3, latest build :l
