### ISSUE TITLE
Extra Feature

### ISSUE THREAD

**Issue by successed** [filoghost/HolographicDisplays#176]
Can you add animated item please ? 
this :
https://proxy.spigotmc.org/08aba4fd8c3d279b71b0bdb9da1121aaec0ffb54?url=https%3A%2F%2Fi.gyazo.com%2Fce32bb7253fa69921c6b4f8f4f312109.gif

**Comment by filoghost** [comment]
Honestly, it would be too much work for such a "simple" feature, because of how the plugin is currently coded. Pull requests are welcome of course, if anyone wants to add this.
