### ISSUE TITLE
ChestCommands=BungeeCord

### ISSUE THREAD

**Issue by RebelLP** [filoghost/HolographicDisplays#18]
Hello,
I'd like you to join Bungee Cord with your plugin ChestCommands. I'd like to go motd witch you should visit a number of players on a particular server. I changed the item will need to play a minigame. When the lobby will have the necessary blue wave and he'll be in the game and that wave will be red. I'd like to tan item varied by color. Like if Lobby will be blue and the necessary wave of change to the blue wave

**Comment by filoghost** [comment]
Stop opening issues. This issue tracker is for Holographic Displays, not for Chest Commands. I won't add it for sure if you keep insisting.

**Comment by RebelLP** [comment]
Oh no! For 1) I do not know how should I put under question plugin ChestCommands
 Over 2) I would like to have collaborated with mime project and would have made for our plugins.
 Over 3) Necessarily we need JAVA devlopera.
 Over 4) Plugins for us to create can sell spigot.
 For this, I'll be happy to cooperate with us budet thank you in advance for your response.
Thenks

FACEBOOK: https://www.facebook.com/funnylandczech
WEB: http://funny-land.tk/
