### ISSUE TITLE
unhandled exception spam in console and log file

### ISSUE THREAD

**Issue by stw222** [filoghost/HolographicDisplays#180]
[https://pastebin.com/a0nf1c8A](https://pastebin.com/a0nf1c8A)

paper spigot version 107 for 1.14.2
holographicdisplays-2.3.3-snapshot.jar

plugins:

- actionbar api
- announcer
- arnorstand tools
- async world edit
- better sleep
- buycraftx
- chunk spawner limiter
- citizens
- core protect
- crazy auctions
- discordSRV
- dynmap
- editable signs
- essentialsx
- greifprevention
- head database
- heads plus
- holographic displays
- HorseTPWithMe
- marriage master
- matrix
- mcmmo classic
- mineable spawners
- mob capture
- mobhunting
- multiverse core
- multiverse inventories
- multiverse netherportals
- multiverse portals
- multiverse signportals
- nerf phantoms
- openinv
- permissionsex
- placeholder api
- plot2dynmap
- plotsquared
- protocol lib
- server list plus
- tab
- tempfly
- vault
- voting plugin
- wildernesstb
- world edit
- world guard

**Comment by filoghost** [comment]
Please update ProtocolLib to the latest development build, you're using an old build.

ProtocolLib dev builds: http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/
