### ISSUE TITLE
plugin disabled

### ISSUE THREAD

**Issue by pewdular** [filoghost/HolographicDisplays#185]
I downloaded Holographic Displays earlier today, When i attempt to use it i get 'org.bukkit.command.CommandException: Cannot execute command 'hd' in plugin HolographicDisplays v2.3.2 - plugin is disabled." in console. In game, it says Internal Error.
How do I enable the plugin?

**Comment by YouHaveTrouble** [comment]
Check the logs next time. As for now plugin only works up until 1.13.1

**Comment by Andre601** [comment]
Dev Builds do work on 1.14.3 @YouHaveTrouble 
Don't spread semi-true information

**Comment by filoghost** [comment]
First of all, use latest version. I'll reopen the issue if you provide logs with the latest version. Make sure you're using Spigot and not just CraftBukkit.
