### ISSUE TITLE
Empty line possible?

### ISSUE THREAD

**Issue by Andre601** [filoghost/HolographicDisplays#187]
I know that HolographicDisplays is in a state where it only receives required updates for compatibility with newer versions and suggestions are (more or less) not added.
But I still want to suggest this here since I thing people could need it in a way.

## Idea
My idea is to add a way (subcommand?) to allow an empty line in hd.
Right now you can't have an empty line. At least not in an easy way.

By empty Line I don't mean like a line with no text in it. I mean a gab where no text is, because just having an empty line still leaves this semi-transparent background of the nametag that can be annoying.
So an option to have a small gap between two lines would be cool to have because the only real way to have this is by having two separate holograms.

## Possible ways
One way could be an additional command like `/hd addblank <name>` (and of course the other variants of it like setblank, insertblank, etc.)
The second idea would be a sort of placeholder like `{blank}` that tells HD to just move down x units without adding a text. This solution could be more useful because that way you wouldn't need to add separate sub-commands and editing could perhaps be easier.

**Comment by Darkweasam** [comment]
you could do &r so it will be blank, or in the database.yml 
- ''
will do it

**Comment by Andre601** [comment]
Like I mentioned would this still keep the tag itself

**Comment by Darkweasam** [comment]
the
`- ''`
wont

**Comment by filoghost** [comment]
Hi, there's already `{empty}`, the tag is not visible.
