### ISSUE TITLE
Add setLine and getLines for Hologram in API.

### ISSUE THREAD

**Issue by lishaodong** [filoghost/HolographicDisplays#19]
First I want to thank you for your work in this plugin, it's terrific. I just hope you can add more methods in Hologram class, in the API.

Currently I think I can't get all lines of a hologram (as a List<String> or something else), that's kind of annoying. And I don't know how to use getLine(int i) to get the text of this line.

And it will be better if there is a setLine(int i, String text) method, currently I can only use removeLine then insertTextLine.

**Comment by lishaodong** [comment]
ok. I thought I have figure it out. 

I can cast HologramLine to TextLine to get text of a line, right?

Anyway, you can add some methods if you think necessary, or you can close this issue.

Thanks

**Comment by filoghost** [comment]
Yes, you have to cast it to TextLine. I didn't add getLines() (the only one that isn't present) to avoid confusing people, since the returned array or List would just be a copy. You wouldn't be able to remove lines using that array.
