### ISSUE TITLE
Lag caused by chunks loading

### ISSUE THREAD

**Issue by andrewkm** [filoghost/HolographicDisplays#191]
HolographicDisplays is currently taking up over 25% of our server tick.
https://i.imgur.com/o4qOc6P.png
`HolographicDisplays::Event: c.g.f.h.l.MainListener (ChunkLoadEvent)`

I've seen several other servers report the same issues.
Now sure what's causing it.

We are running Paper 1.13.2 Build 639

**Comment by filoghost** [comment]
How many holograms do you have? Please try without other plugins if it still occurs.

**Comment by andrewkm** [comment]
We’ve of course tested with other hologram plugins as well as with no holograms.

This specific plugin is the one that hits performance really hard as can be seen by the timings.

We had about 30-40 holograms that were in a chunk that was constantly being passed through, (loaded and unloaded) as such there is some pretty big slowdown in that regard and how this plugin handles the loading of holograms.

Keeping the chunk loaded or removing the amount of holograms improves the performance but it’s still no where near as good as it should be.

**Comment by Lysandr0** [comment]
Same issue here.
It got especially worse after updating to the latest 1.14.4 development build, HolographicDisplay alone was dragging our server down to 10/9 tps. 
After disabling the plugin through PlugMan, tps went back at 20.
https://gyazo.com/8e0826cf2100e1f7e56b8e0d0e47052e
https://gyazo.com/bda6e073456bc19f20b04db19c328fd9

(Server version: git-Paper-161 (MC: 1.14.4)

**Comment by Raigna** [comment]
I experienced the same problem and so i did some investigating, it appeared that invisible armorstands would begin to spawn i certain areas to the point i have over 5000 spawn in one little area, once you restart they disappear

**Comment by sandor111** [comment]
Same problem here:
![Screenshot_720](https://user-images.githubusercontent.com/17690323/63770029-874b6d00-c8d4-11e9-834f-7b9271cb2340.png)

**Comment by Raigna** [comment]
I found a fix for my problem, if yours is similar it may help, the area I had holograms I used a flag from world guard to keep the chunk loaded, it fixed my problem at least

**Comment by Trikolon** [comment]
`v2.4.0.` is still affected. Degraded server performance (10 tps) after a couple of hours uptime.

**Comment by sandor111** [comment]
https://pastebin.com/sSxMBzqE

**Comment by sandor111** [comment]
> I found a fix for my problem, if yours is similar it may help, the area I had holograms I used a flag from world guard to keep the chunk loaded, it fixed my problem at least

Which flag?

**Comment by sgdc3** [comment]
@filoghost probably a placeholder task going crazy? :/

**Comment by filoghost** [comment]
Can someone provide the link to the timings report, or even better, a CPU timings snapshot (such as with VisualVM)? The CPU snapshot would help a lot. I failed to reproduce on my machine, loading and unloading as fast as possible a chunk with 1000 holograms in it, each one with a placeholder.

@sgdc3 Could be a coincidence, but I didn't know it compiles a regex each time internally. It may have some effects on performance, so the name is now cached in 1.13+ 66666dc51076a23a15d7d36f10feb33f437a0610

**Comment by SXRWahrheit** [comment]
@filoghost If you'd like to join the MythicMobs Discord and chat with users there, many of them have been having this issue and can probably either help you reproduce it or take the logs for you. Here's an invite link: https://discord.io/mythicmobs

**Comment by andrewkm** [comment]
Is this getting fixed @filoghost

**Comment by filoghost** [comment]
Was not easy to find a reason, but it looks like setting `precise-hologram-movement` to false could fix the problem. Can anyone confirm? Sorry if it took so long.

**Comment by Trikolon** [comment]
> Was not easy to find a reason, but it looks like setting `precise-hologram-movement` to `false` in the configuration of HD could fix the problem. Can anyone confirm? Sorry if it took so long.

Thank you! Testing this. Will get back to you once it's been running for a while.

**Comment by filoghost** [comment]
After some CPU profiling I am 99% sure `precise-hologram-movement` is the cause. It uses a method that can be slow if called frequently (see #16). I will need to rewrite that part without using stacktraces, using ProtocolLib if necessary.

**Comment by Trikolon** [comment]
Tested with latest dev build and `precise-hologram-movement` = `false`. Seems to be fixed. Thank you.

**Comment by filoghost** [comment]
I pushed a change to reimplement the functionality of `precise-hologram-movement` through ProtocolLib, fixing the lag problems. Since the option was enabled by default, many users should see big performance improvements if Holographic Displays was slowing their server.

Please test the latest dev build: https://ci.codemc.org/job/filoghost/job/HolographicDisplays
