### ISSUE TITLE
Error onPacketSending

### ISSUE THREAD

**Issue by LoXR** [filoghost/HolographicDisplays#195]
https://pastebin.com/jMTwhcFs
Server Version: Paper 1.14.4
Latest Dev build of HolographicDisplays.
Latest ProtocolLib (if necessary)

**Comment by Rixafy** [comment]
Hi @LoXR, use last stable version of ProtocolLib http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/, it fixes the problem.

**Comment by LoXR** [comment]
Awesome, does this work with 1.13 or only 1.14?

**Comment by Rixafy** [comment]
Don't know (I'm using older version of HD in 1.13 server where this isn't a problem), but I hope both.

**Comment by filoghost** [comment]
Please update ProtocolLib to the latest development build, you're using an old build and that particular bug has been fixed.

ProtocolLib dev builds: http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/
