### ISSUE TITLE
Error Cannot retrieve entity from ID. (Spam in console)

### ISSUE THREAD

**Issue by Focusprw** [filoghost/HolographicDisplays#196]
Minecraft version 1.14.4 paper build 156
ProtocolLib 4.4.0
HolographicDisplays-2.3.3-SNAPSHOT

Error code: https://pastebin.com/gBncaS3v

**Comment by Rixafy** [comment]
Hi, @Focusprw, use last stable build of ProtocolLib, 4.5.0-SNAPSHOT, http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/ it fixes the problem.

**Comment by hnedokneznik** [comment]
Using 
Paper version git-Paper-153 (MC: 1.14.4)
[ProtocolLib] Enabling ProtocolLib v4.5.0-SNAPSHOT
[HolographicDisplays] Loading HolographicDisplays v2.3.3-SNAPSHOT
Error log from console: https://pastebin.com/YiX0Ttdh every time player log in game.

**Comment by filoghost** [comment]
Please update ProtocolLib to the latest development build, you're using an old build and that particular bug has been fixed.

ProtocolLib dev builds: http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/
