### ISSUE TITLE
Unhandled exception occured in onPacketSending

### ISSUE THREAD

**Issue by zBornConfused** [filoghost/HolographicDisplays#199]
Error: https://gist.github.com/zBornConfused/732ea75b401aa1552f1b8d7d5366fc64
I'm using this build: http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastBuild/
Thanks in advance for your help!

**Comment by filoghost** [comment]
This is caused by ProtocolLib itself, try reporting this to its developer(s). The bug is probably due to the usage of Forge.
