### ISSUE TITLE
{online: ALL} not working

### ISSUE THREAD

**Issue by vanjavk** [filoghost/HolographicDisplays#20]
spigot: 
http://i.imgur.com/UIS0ycb.png
it just gives a white 0. Joining/leaving/restarting servers doesn't help :/ Everything else works fine tho.

**Comment by filoghost** [comment]
Are you joining through BungeeCord?

**Comment by vanjavk** [comment]
Server is closed now but yes I was. It was on my lobby server. However lists for individual server player list did work, it just that plugin didn't know how to add it all together in one number XD

**Comment by games647** [comment]
It works for me

**Comment by vanjavk** [comment]
This is one year old lol
