### ISSUE TITLE
Horses disappearing on 1.14.4 with latest Jenkins build

### ISSUE THREAD

**Issue by brian1999lin** [filoghost/HolographicDisplays#208]
HolographicDisplays version: v2.2.3-SNAPSHOT (latest Jenkins Build)
Spigot version: v1.14.4 (latest build)
Plugins:
![image](https://user-images.githubusercontent.com/12367435/63214145-7b94c500-c0e2-11e9-8f5f-22e47e9c6bd3.png)

I'm noticing that tamed horses keep disappearing on my Spigot server and I read that HolographicDisplays has previously caused these issues. Just wondering if there's any possibility that this is still the case.

**Comment by filoghost** [comment]
Holographic Displays doesn's use horses since 1.8, it's definitely not its fault.
