### ISSUE TITLE
Issue with BungeeCord variables

### ISSUE THREAD

**Issue by Malvagio87** [filoghost/HolographicDisplays#21]
- '&f&l&oHC Factions: {status: factions}'
- '&a{online: factions}/300'

I use those two lines for displays and the config is setup properly.

When i start my server, while the server is loading plugins, the display goes from Offline to Online, however, once its done loading the plugins and the server can be logged into, it goes back to Offline even though the server is now online.

Im running the latest version of spigot 1.8.8

**Comment by filoghost** [comment]
Sorry for not answering on this. I will now close the issue since it's old, and assume it was a problem on your server specifically. If not, please answer and I will reopen it.
