### ISSUE TITLE
Holographic Position Problem in 1.8.0

### ISSUE THREAD

**Issue by TheBrunoRM** [filoghost/HolographicDisplays#212]
Server version: Spigot 1.8.8
HD version: 2.3.2

Aiming near the same block
![image](https://user-images.githubusercontent.com/38665405/63642413-f8044680-c694-11e9-89af-2f2bc941135d.png)

In spectator mode, the text is not in the same position for both version
![image](https://user-images.githubusercontent.com/38665405/63642417-03f00880-c695-11e9-9a5c-6783fed0f4bc.png)

I have seen this error in my server, so I created a new one to test this without any plugins (only HolographicDisplays)
![image](https://user-images.githubusercontent.com/38665405/63642369-87f5c080-c694-11e9-8452-687e71677446.png)

**Comment by filoghost** [comment]
Haven't been able to reproduce it. Can you try on version 2.4.0? Do you just switch gamemode, without moving far away or rejoining the server, to cause this bug?
