### ISSUE TITLE
Having an internal error message

### ISSUE THREAD

**Issue by Buzz1971** [filoghost/HolographicDisplays#214]
HD commands are not working at all /hd or any of the other commands, I get a responce of
 "An internal error occurred while attempting to perform this command" 
in red writing in chat for the game
I am running spigot 1.14.4 with PEX and EssentialsX plugins also Vault and some other plugins none of which uses holograms to my knowledge!
I have the latest version of the plugin here

**Comment by filoghost** [comment]
I need the error message that appears on the console.
