### ISSUE TITLE
Constantly creates thousands of area_effect_clouds

### ISSUE THREAD

**Issue by spigelli** [filoghost/HolographicDisplays#215]
Pretty self explanatory, lots of others having the same issue. Took a while to pinpoint and made me extremely frustrated :(

**Comment by filoghost** [comment]
The plugin doesn't create or interact with effect clouds in any particular way, why do you think it's Holographic Displays fault?

**Comment by spigelli** [comment]
Because I removed it and it stopped. I put it back in and it started again. And then I removed it again and it stopped. It’s probably a conflict with some other plugin.

**Comment by filoghost** [comment]
That's probably caused by the other plugin, can you try removing all the others except HD, to find out what is the conflicting one?

**Comment by filoghost** [comment]
@spigelli Did you find the conflicting plugin?
