### ISSUE TITLE
Unhandled exception 

### ISSUE THREAD

**Issue by Ryano81** [filoghost/HolographicDisplays#218]
I keep getting unhandled expectation errors, ever since I installed protocol lib. I am using the most up to date version of both protocol lib, and holo signs. My config is all default, and I only have a few signs around the world. The plugin still seems to function, and in-game you can't even tell there is an error, but my console gets absolutely flooded. 

[latest.log](https://github.com/filoghost/HolographicDisplays/files/3587688/latest.log)

**Comment by filoghost** [comment]
Please update Holographic Displays to the latest development build, this issue has already been solved.

Development builds: https://ci.codemc.org/job/filoghost/job/HolographicDisplays
