### ISSUE TITLE
Trying to grab a Hologram from a location (API)

### ISSUE THREAD

**Issue by RexlessTazz** [filoghost/HolographicDisplays#221]
So I read through the HologramsAPI, basically leading me to the BackendAPI, which of course I fully checked. I also read through the source to try and find if there was anything I could use for this method.
Basically I'd like to be able to grab a hologram from only a location.
I thought I could possibly grab it via getNearbyEntities, but I can't use just that to set up the Holograms the way they need to be for my methods.

I was wondering if there was anyway you could possibly add to the HologramsAPI or BackendAPI something similar to HologramsAPI.getHologram(Location location)?

(Basically just return a Hologram from nothing but a Location)

It would seriously help me out and solve my issue. Thank you for your time.

**Comment by filoghost** [comment]
You have to get the list of holograms of your plugin through the API, iterate and get them by their location. It would be better to keep references of the holograms. What's the use case? You may not need to search them by location.
