### ISSUE TITLE
Add support for Item Amount

### ISSUE THREAD

**Issue by Wolf2323** [filoghost/HolographicDisplays#222]
First i am not sure if this is a limitation of Minecraft, so it it is, let me know this if it is.
I tried to set set the Amount of an floating Item over the API, so that you see the stacked item texture. But i realized, that nothing happens. So i asked my self if this is a limitation of MC, or a limitation of HolographicDisplays.  And if it is a limitation of HolographicDisplays can you change this?

**Comment by filoghost** [comment]
Added here https://github.com/filoghost/HolographicDisplays/commit/8293f8b64284877aba047732926cb2c46a88fe5c
