### ISSUE TITLE
Placeholder update exception {time}

### ISSUE THREAD

**Issue by RyderBelserion** [filoghost/HolographicDisplays#227]
![image](https://user-images.githubusercontent.com/52214219/65460838-cbbd2080-de20-11e9-971a-65aa2f317dca.png)

This was not here last night but just showed up in the past 5 minutes. I can't find anything on spigot / github or in the docs unless I am blind 

I've restarted, removed plugins one by one etc but it still keeps spamming away. I am currently on the latest version that you get on spigot from version history.

**Comment by filoghost** [comment]
Is there any error on server startup, before the spam?

Can you try resetting your config.yml (rename the old one)?

**Comment by RyderBelserion** [comment]
I did reset it yes, that worked. I must of done something wrong

**Comment by filoghost** [comment]
Could you please give me the "bugged" configuration please?

**Comment by RyderBelserion** [comment]
No, I didn't keep a backup of it nor any of the logs sorry. I'll try and reproduce it.
