### ISSUE TITLE
Feature request: Timer/timeout

### ISSUE THREAD

**Issue by SlimeDog** [filoghost/HolographicDisplays#231]
I would like a configurable option to display a specific hologram to a player for a limited period, measured in seconds. Use cases: (1) an introductory hologram could be shown only once; (2) an explanatory hologram could be shown daily; etc.

Options might include:
- Once only, the first time the hologram is encountered
- Every time the hologram is encountered
- Periodically when the hologram is encountered, say once a day (for example)

An "encounter" should be determined by entry into a specific proximity (radius) to the hologram.

**Comment by filoghost** [comment]
This is a nice idea, and there are definitely some other use cases, but I don't think this should be in the core plugin. It should rather be an external plugin using the API. 

The core plugin should just provide the tools for creating/modifying/deleting hologram, and some basic tools (like placeholders and animations).

**Comment by SlimeDog** [comment]
I thought "tools for creating/modifying/deleting hologram" is what the API provides. But I would be happy with an external plugin. Are you thinking to build it? Incentives might be available. :)

**Comment by filoghost** [comment]
Sorry, but I really have no time to develop additional plugins. However anyone can create it.
