### ISSUE TITLE
HologramsAPI not working correctly (holograms not being registered)

### ISSUE THREAD

**Issue by klokailo** [filoghost/HolographicDisplays#233]
When using holographicdisplays version 2.4.0 and paperspigot for MC 1.13.2, I am having an issue with the API.
After creating a hologram like this:
```
Hologram hologram = HologramsAPI.createHologram(Plugin.getInstance(), location);
hologram.appendTextLine(ChatColor.translateAlternateColorCodes('&', "&6My Text"));
```
The hologram will be created and be displayed in game, but after creating it, when using /hd list it states that there are no holograms. In addition, the hologram will disappear when restarting the server.

**Comment by filoghost** [comment]
That's intended. Plugin on create hologram "for themselves" and are not persistent.

The best way of doing this would be to create your own storage file, load the holograms on startup (or when necessary), and add commands to create them.

If you really want to add holograms as if they were added by the plugin, look at the code for the official commands. However, they don't use the official API and can change at any moment without notice.

**Comment by klokailo** [comment]
Alright. Thanks!
