### ISSUE TITLE
Update 1.15

### ISSUE THREAD

**Issue by FallenEmo** [filoghost/HolographicDisplays#240]
Maybe update the plugin for 1.15? I really need it

**Comment by VanillaChan6571** [comment]
#9​5 added support but it failed.

**Comment by Blamo27** [comment]
@filoghost Yes 1.15 update failed :
![image](https://user-images.githubusercontent.com/971712/70853624-c2d46c00-1eb0-11ea-8b89-dd3a10383998.png)

**Comment by Momonche** [comment]
Some news about this @filoghost ?

**Comment by filoghost** [comment]
A working dev build is now available: https://ci.codemc.io/job/filoghost/job/HolographicDisplays/
