### ISSUE TITLE
1.7 and 1.8 issue with protocollib

### ISSUE THREAD

**Issue by HydroFlare** [filoghost/HolographicDisplays#241]
Known bug (when using ProtocolLib): if a hologram is hidden and then gets shown, the players seeing it will be disconnected with a network error.

I need holograms, but i'm not sure what to do at this point. I need to use holograms and protocollib and be able to join with 1.7 and 1.8. Are there any plugin alternatives? Any plugin forks? Any fixes?

**Comment by filoghost** [comment]
Is the server 1.7 or 1.8? Either way, there are no fixes I'm aware of.
