### ISSUE TITLE
Server Timings Lag 

### ISSUE THREAD

**Issue by dabou0** [filoghost/HolographicDisplays#246]
Using paper 1.8.8
so i check the timings and was like this

http://prntscr.com/qi5zr1

http://prntscr.com/qi5zzk

http://prntscr.com/qi603t

http://prntscr.com/qi61dc

if you can help me, thank you very much

if needed i can send full timings link on private

**Comment by KarlPro123** [comment]
I have to complain too, here:

https://gyazo.com/7280de045747d3ea07160258ff0a2f79

**Comment by filoghost** [comment]
Please post actual links to timings, I can't do much with just the images.

**Comment by filoghost** [comment]
Try setting `precise-hologram-movement` to `false`, let's see if that is the mayor cause of performance issues.

Also @dabou0 can I have some info on your server machine specs and Spigot version? It looks unusually slow.

**Comment by filoghost** [comment]
See #191, the problem was solved.
