### ISSUE TITLE
Don't Run /holo create ★ &6&l★ Unless You Want A Bad Time

### ISSUE THREAD

**Issue by alexis-evelyn** [filoghost/HolographicDisplays#249]
The command below will crash the server. Tested on 1.15 Paper.

    /holo create ★ &6&l★

**Comment by Manicraft1001** [comment]
I think, you cannot use any ascii codes for the hologramm name.
Try using another one, like "mycoolhologram".

**Comment by alexis-evelyn** [comment]
I don't believe any Unicode Characters can be used for hologram names other than the plain ASCII ones and/or the Latin-1 based Unicode. I didn't test anything else other than the star though.

**Comment by filoghost** [comment]
When I try to execute the command it says `The name must contain only alphanumeric chars, underscores and hyphens.` Are you using an old version?
