### ISSUE TITLE
Error message in v2.1.11

### ISSUE THREAD

**Issue by dmulloy2** [filoghost/HolographicDisplays#25]
Message: ````Detected development version of ProtocolLib, support disabled. Related functions (the placeholders {player} {displayname} and the visibility API) will not work.
The reason is that this version of ProtocolLib is unstable and partly broken. A new version of Holographic Displays will be out when ProtocolLib gets fixed.````

HD: v2.1.11
ProtocolLib: v3.7-SNAPSHOT-b249
Spigot: git-Spigot-bc01c3a-935349e (MC: 1.9), 0 versions behind

Everything seems to be working with ProtocolLib.

**Comment by filoghost** [comment]
https://github.com/filoghost/HolographicDisplays/commit/e02f2ad7f4aca87625bcdc34a8857ce9a76d1d80
