### ISSUE TITLE
onPacketSending(PacketEvent) - java.lang.IllegalStateException: Not implemented

### ISSUE THREAD

**Issue by KernelErr0r** [filoghost/HolographicDisplays#250]
Hi, I have probably found a bug in your plugin, it occurs when I'm trying to make other players glow with [InventiveTalent's GlowAPI](https://github.com/InventivetalentDev/GlowAPI)

[Stacktraces](https://pastebin.com/GJckBq90)

**Comment by filoghost** [comment]
Should be fixed with https://github.com/filoghost/HolographicDisplays/commit/db949bcfd1b3abaacc820e427e9b7fbd79bb5dde

Please try the new development build: https://ci.codemc.org/job/filoghost/job/HolographicDisplays
