### ISSUE TITLE
Holograms disappear sometimes

### ISSUE THREAD

**Issue by car1ot** [filoghost/HolographicDisplays#251]
I'm using ProtocolSupport, and in old version holograms could disappear and bug sometimes:
https://i.imgur.com/1HcydOz.png
https://i.imgur.com/24GwuPk.png

Also updates through API is too buggy, hologram jumps, and could cut some lines in old versions.

One more question: could you explain to me, please, how to update holograms (for example timer) smoothly without flicker, using API?

**Comment by car1ot** [comment]
Bump!

**Comment by filoghost** [comment]
If you want smooth updates you should try updating lines, instead of clearing all of them and adding new ones. That's just what I assume, you should post your code.

I can't fix the problems with ProtocolSupport, you should ask the developer of that plugin.
