### ISSUE TITLE
API smooth timer update

### ISSUE THREAD

**Issue by car1ot** [filoghost/HolographicDisplays#252]
Im need to display countdown timer in hologram, using your API.
My current code (pseudo code):
time = 10
Repeat every second until time end (
Remove line 0
Setline 0 "Time left: " + time
time--
)

But sometimes armorstand shows and update isnt smooth. How to make smooth update?

**Comment by filoghost** [comment]
You shouldn't remove and add a line, just modify the existing line. Otherwise the armorstand used to display the hologram is deleted and recreated.
