### ISSUE TITLE
Kindly allow /hd create from console w/ world,x,y,z location

### ISSUE THREAD

**Issue by gmalone** [filoghost/HolographicDisplays#253]
1. Console creation
For admin users, it is essential that holgrams be able to be created from console, and not just from a player-context.  To do so, a command like `/hd create <name> <world> <x> <y> <z> [content]` would be a godsend.

2. Chat output-message suppression
It'd be preferable on a production server to be able to suppress chat output from the plugin.  Way too much 'process text' spills into that space.  Server admins would prefer to not burden players with that irrelevant-to-them information.

Thanks.

**Comment by mcdaddytalk** [comment]
Would a console entry such that you could add a hologram from console (/hd concreate <name> <world> <x> <y> <z>) suffice?  This would allow the creation via console vs player-context but then use the normal console commands to edit/delete

**Comment by filoghost** [comment]
I would like to know the context of this use case. Why is the output shown to players? Are you trying to use commands in scripting plugins?
