### ISSUE TITLE
NamedHologram#delete hologram comes back after reload or restart

### ISSUE THREAD

**Issue by mart-r** [filoghost/HolographicDisplays#254]
I'm using a custom plugin to adopt an existing hologram to a plugin based one. After I've cloned the lines, I call the delete method. The hologram successfully disappears.

However, if I do /holo reload or restart the server, the hologram reappears.

I get the hologram with CommandValidator#getNamedHologram

HolographicDisplays v2.4.2-SNAPSHOT
ProtocolLib v4.5.0

**Comment by filoghost** [comment]
Non-public API are not documented and they don't always behave as you would expect, code can be messy.

You need to also delete the hologram from the database, see the `delete` command handler.

**Comment by mart-r** [comment]
Since the design of the plugin I'm making changed, this issue is no longer a concern. (For clarity: I'm using existing HD holograms and showing as well as hiding them using their visibility managers).

But thanks for the answer.

PS:
I was aware that by using non-API methods I'd be subject to such limitations. I just felt that the #remove method should remove the hologram, but it didn't. But again, no biggy, really.
