### ISSUE TITLE
a little help please?

### ISSUE THREAD

**Issue by sagenthings** [filoghost/HolographicDisplays#258]
so, i recently updated my server from 1.13.2 to 1.14.4. i reinstalled the plugin jar and replaced it for the old one. my holograms are not showing up at all. can i get a little help?
[message.txt](https://github.com/filoghost/HolographicDisplays/files/4163187/message.txt)

**Comment by filoghost** [comment]
I don't see any error, so it could be a conflicting plugin.
How to find a potentially conflicting plugin:
* Copy your whole server
* Remove all the plugins except Holographic Displays
* If it doesn't work, stop here and tell me
* Add plugins back until Holographic Displays doesn't work anymore
* The conflicting plugin is the one that breaks Holographic Displays when enabled
