### ISSUE TITLE
Holos disappearing after User join

### ISSUE THREAD

**Issue by R4zzerYT** [filoghost/HolographicDisplays#259]
My holos disappearing after user join, without error.

Spigot 1.15.2

**Comment by filoghost** [comment]
Could be a conflicting plugin.

How to find a potentially conflicting plugin:
* Copy your whole server
* Remove all the plugins except Holographic Displays
* If it doesn't work, stop here and tell me
* Add plugins back until Holographic Displays doesn't work anymore
* The conflicting plugin is the one that breaks Holographic Displays when enabled
