### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by sebastianbinder** [filoghost/HolographicDisplays#26]
Hi @filoghost 
I was just trying to build your repository for checking compatibility with BedwarsRel plugin, since you have not updated the plugin on Bukkit so far. How can this project be built? Are you using Maven, or Ant, or … ? Since I cannot find any build files...

**Comment by sgdc3** [comment]
I already told @filoghost if he wanted to use maven as build system but he wasn't interested. :/

**Comment by filoghost** [comment]
Download is out, however you only need the default compiler. There is no main class.
