### ISSUE TITLE
Armour stands are exponentially increasing?

### ISSUE THREAD

**Issue by B-Knight49** [filoghost/HolographicDisplays#260]
![image](https://user-images.githubusercontent.com/26165117/74184412-a9e10080-4c3e-11ea-8b65-ff51a76fdd85.png)

There are 3 holograms in that chunk. Middle-right has 2 lines, bottom-middle has 3 lines and middle-left has 3 lines. In this chunk alone there are 192 armour stands. There is nothing else in this chunk at all from Y0 to Y255. 

![image](https://user-images.githubusercontent.com/26165117/74184510-d39a2780-4c3e-11ea-91c7-bc0af6719c8f.png)

PaperSpigot Build 77 
Minecraft 1.15.2 
HolographicDisplays v2.4.1

Any reason for that? I can't see how more than 1 armour stand per-line would be necessary, let alone 64 per hologram.

**Comment by TotallyNotKyle** [comment]
I am getting this exact issue as well. They duplicate every time the chunk is reloaded. https://i.imgur.com/srghgh3.png
Paper 105
MC 1.15.2
HolographicDisplays v2.4.1.

**Comment by filoghost** [comment]
Could be related to https://hub.spigotmc.org/jira/browse/SPIGOT-5228, as logic for spawning hasn't been changed. Please also try the new dev build and run `/hd debug`.

Development builds: https://ci.codemc.org/job/filoghost/job/HolographicDisplays

**Comment by filoghost** [comment]
After trying Paper 105, I can confirm it happens.  Build 154 specifically fixes this bug: https://github.com/PaperMC/Paper/commit/31e751cb40ee5558b144c64049753992b32ec3cc
