### ISSUE TITLE
Suggestion: Multiple Worlds online player placeholder

### ISSUE THREAD

**Issue by TKwSni** [filoghost/HolographicDisplays#265]
It would be great to have a placeholder Like the bungeecord  one, which lets you count how many players are in more than 2 worlds

{worlds: mining1, mining2}

**Comment by filoghost** [comment]
Since this was quick to add, here it is: https://github.com/filoghost/HolographicDisplays/commit/b589749c245977b17252dd265fcca8250f7ecafc (you can download a dev build if you want to use it now)
