### ISSUE TITLE
/hd readtext test filename.txt

### ISSUE THREAD

**Issue by cantercrow** [filoghost/HolographicDisplays#266]
Hi,

When I create a hologram with /hd readtext test filename.txt the hologram appears correctly but if I issue /hd reload or reload the server I get an error that the hologram cant be found and it does not display.

**Comment by mcdaddytalk** [comment]
Take a look at a possible solution in 
https://github.com/filoghost/HolographicDisplays/issues/275

**Comment by filoghost** [comment]
Are you sure it's related to the `readtext` command and not to holograms in general? What happens if you manually modify a hologram? It could simply be in a world that is not loaded.

**Comment by mcdaddytalk** [comment]
I test this by creating two holograms.  One created using addLine and one created using readtext.  addline saves to database.yml as expected.  readtext saves to database.yml as all nulls.
I have a fix in pull request

**Comment by filoghost** [comment]
Thanks, I fixed it in a slightly different way in https://github.com/filoghost/HolographicDisplays/commit/a41be09ef3fa158790de7bc014347ef889958804
