### ISSUE TITLE
ProtocolLib: entityID cannot be negative

### ISSUE THREAD

**Issue by iShadowboy** [filoghost/HolographicDisplays#267]
I have a error with this plugin, I have update the protocol Lib and try with a Update HD version... But nothing work, please help! :(

https://pastebin.com/LRLk8MUY

**Comment by filoghost** [comment]
Are you sure you're using the correct ProtocolLib version? If so, it may be a conflicting plugin.

How to find a potentially conflicting plugin:
* Copy your whole server
* Remove all the plugins except Holographic Displays and ProtocolLib
* If you still see the error, stop here and tell me
* Add plugins back until the error is shown again, find which one causes the problem

**Comment by filoghost** [comment]
Should be fixed in 269a4bec7275343137339a194d9d7ba09bc9e602
