### ISSUE TITLE
Apply CustomModelData to Icon Items

### ISSUE THREAD

**Issue by ArctoranDev** [filoghost/HolographicDisplays#268]
Title says it all, just want the ability to have "custom items" for use as icons using custom_model_data predicate.

**Comment by filoghost** [comment]
You can use NBT data, it's undocumented at the moment:

> Added support for NBT tags in icons. You can add NBT after the icon's material. Example: ICON: diamond {... NBT data here ...}

**Comment by filoghost** [comment]
@Andre601 do you mean, for example, an item in your hand?

**Comment by Andre601** [comment]
> @Andre601 do you mean, for example, an item in your hand?

Yes, exactly.
