### ISSUE TITLE
Different Hologram Places in Different Versions

### ISSUE THREAD

**Issue by dimitrisbey** [filoghost/HolographicDisplays#274]
Well, my server is PaperSpigot 1.8.8 and I’ve got HolographicDisplays version 2.4.1. Well I won’t explain what is happening, I just let you see...

Looking with 1.8.9 (version that i use)
![image](https://user-images.githubusercontent.com/63169632/78461441-93e93c80-76d1-11ea-9e63-5cd26b649ce0.png)

Looking with 1.8 (version that i do not use)
![image](https://user-images.githubusercontent.com/63169632/78461452-b418fb80-76d1-11ea-96cc-ba671f067546.png)

Please solve this problem!

**Comment by filoghost** [comment]
Sorry, this needs to be solved by the plugin allowing players with multiple Minecraft versions to join your server.
