### ISSUE TITLE
Holographic Displays Error

### ISSUE THREAD

**Issue by Teoxex** [filoghost/HolographicDisplays#277]
Hi everyone!, I have a problem with Holograpich Display (again XD).
When I create a hologram and modify it, it is completely normal, the problem and when for any reason I reload the plugin (/holo reload). It tells me that "`( ! ) Hologram '[name of hologram]' not found, skipping it.`". It all happened today suddenly and this fact is strange. My plugins are the ones pictured below. Someone would know how to help me is urgent, Thanks

Plugins: https://i.imgur.com/ByzfJFM.png

**Comment by filoghost** [comment]
Name of the world that hologram is in? Did you use `/hd readtext` or `/hd readimage` recently?

**Comment by super7800** [comment]
i am having exactly the same issue for my images.  (/hd readimage).

i spent quite a few hours setting them all up and now they r all gone :(

shows up as -null in database

any help to resolve this issue is appreciated. thanks

here is the database error: https://i.postimg.cc/25bXxV2Y/issue.png

**Comment by filoghost** [comment]
Please update Holographic Displays to the latest development build, this issue has been solved.

Development builds: https://ci.codemc.org/job/filoghost/job/HolographicDisplays
