### ISSUE TITLE
Fastcraft 1.22 Makes Holograms Not Appear

### ISSUE THREAD

**Issue by Zendrex** [filoghost/HolographicDisplays#28]
As the title says, with fastcraft 1.22, holograms decide not to appear. I assume this has to do with both Fastcraft and holographic displays and how the nameplates are made. I know you dont really support 1.7.10 anymore, but it would be appreciated if you could at least give some insight on this and I can hire someone tor resolve this for my network.

Many thanks, Zendrex

Fastcraft Page: http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820

**Comment by TomberWolf** [comment]
Is there something new on this?

**Comment by Zendrex** [comment]
I worked with the fastcraft Dev to fix this. V 1.23 of fastcraft works with HD. Forgot to close this (it was fixed a long time ago)
