### ISSUE TITLE
image holograms dissapearing

### ISSUE THREAD

**Issue by super7800** [filoghost/HolographicDisplays#280]
all my image holograms disapeared when the server restarted.

/holo reload It tells me that "( ! ) Hologram '[name of hologram]' not found, skipping it.".

/hd readimage command

i spent quite a few hours setting them all up and now they r all gone :(

normal holograms are fine

shows up as -null in database

any help to resolve this issue is appreciated. thanks

here is the database error: https://i.postimg.cc/25bXxV2Y/issue.png

**Comment by filoghost** [comment]
Please update Holographic Displays to the latest development build, this issue has already been solved.

Development builds: https://ci.codemc.org/job/filoghost/job/HolographicDisplays
