### ISSUE TITLE
A bunch of armor stands

### ISSUE THREAD

**Issue by slipcor** [filoghost/HolographicDisplays#281]
Hey there,

using my plugin PVPStats, and creating Holograms through PlaceholderAPI (?) it has been reported that my plugin is causing a bunch of armor stands to spawn, but most certainly my plugin is not dealing with armor stands at all, so, how can we remove a spam of hundreds of armor stands that look like this, and prevent it to happen in the future?

https://imgur.com/a/RVygkER

I will gladly refer the reporter to you if you need more information, because I do only have this image as bug report :)

**Comment by filoghost** [comment]
Please take a look at https://github.com/filoghost/HolographicDisplays/issues/260, it could be the same issue.

**Comment by slipcor** [comment]
Oh yeah, I did not see that one. Reporter said "all is good anyway" without me doing anything, thanks for the link :)
