### ISSUE TITLE
Floating Horses

### ISSUE THREAD

**Issue by nyonee** [filoghost/HolographicDisplays#282]
Hello, I am using Holographic Displays v2.1.10 for a 1.7.10 - 1.8.9 server.

Every time I make a new Holograph it just spawns Floating Horses riding a Whither Head 56 blocks above where it should spawn the Holograph on 1.8.9, on 1.7.10 it works though.

How can I fix this?

Edit: I tried v2.2.6 and I get the same issue

**Comment by filoghost** [comment]
Hello, you can't fix it, also you're using an old HD version and Minecraft 1.7.10 is not supported anymore. Holograms were a bit of a "hack" before 1.8, when armor stands were added. It's up to the plugin allowing multiple protocols to fix the issue.
