### ISSUE TITLE
Support for LightAPI Fork?

### ISSUE THREAD

**Issue by Andre601** [filoghost/HolographicDisplays#283]
It would be quite useful, if HolographicDisplays would support the Plugin [LightAPI Fork](https://www.spigotmc.org/resources/lightapi-fork.48247/) to have a light source at the holograms, to make the glow in the dark.
The only alternative would be to place a light source (glowstone, sea lantern, torch, ...) below the hologram, which isn't always possible.

**Comment by filoghost** [comment]
I honestly don't think this is really needed. It makes sense for holograms to follow environment lighting.

**Comment by Andre601** [comment]
And I don't see why not.
Like give me a legit reason as to why holograms shouldn't have this option to be bright and readable at dark places (And don't come with reasons like that you could put a light source below it, because that wouldn't work every time)

When you put a hologram at a rather dark place (i.e. in a cave) and can't put a light source underneath it, does it appear dark and unreadable.
This would make it easier to read. It could be a config option which could be turned off by default.

**Comment by filoghost** [comment]
"Why not" is not a valid reason to implement a feature. Even if optional, a feature should be added only if a good portion of users benefit from it, and I don't think that would be the case. Otherwise the plugin would be bloated with features that only few users actually benefit from.
