### ISSUE TITLE
My display it's invisible

### ISSUE THREAD

**Issue by Dmaia1000** [filoghost/HolographicDisplays#284]
I did some commands just to create the screen and it is invisible

![image](https://user-images.githubusercontent.com/64880535/81134282-a4880f00-8f2a-11ea-99a5-30bb00034368.png)
the display appears when i add a line for example and disappears right away

**Comment by filoghost** [comment]
You're using an old version that is not supported anymore, sorry. 1.7.10 was quite buggy because armor stands weren't in the game yet. The cause is usually plugins like ViaVersion and ProtocolSupport allowing players with different versions to join the server.
