### ISSUE TITLE
Save/persist API-created holograms

### ISSUE THREAD

**Issue by viveleroi** [filoghost/HolographicDisplays#289]
### What are you trying to do?
I'd like holograms made via API to save/persist with the world like ones created via the plugin.

### What have you tried so far?
Look over the docs, API docs, etc for any reference to persistance.

### Platform

- Server version (output of `/version`): 1.15.2
- Holographic Displays version (check with `/hd`): 2.4.1
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): No

**Comment by filoghost** [comment]
You currently need to save them to disk by yourself. API-created holograms are separate from command-created holograms, and they are not mean to be persistent by default. You can take a look at how Holographic Displays stores holograms here: https://github.com/filoghost/HolographicDisplays/tree/master/Plugin/src/main/java/com/gmail/filoghost/holographicdisplays/disk
