### ISSUE TITLE
Icons turning into Stone

### ISSUE THREAD

**Issue by Intriguing-RC** [filoghost/HolographicDisplays#290]
Every so often, Item Icons turn into Stone. 
![](https://i.imgur.com/Ri3bl4A.png)

The steps on how to reproduce this are unknown. It fixes it self on reboot or /hd reload.

- I am currently using a fork of PaperSpigot called iSpigot
- I am using 2.4.1 version of HolographicDisplays
- ProtocolLib: 4.5.0
- Also using ViaVersion

**Comment by filoghost** [comment]
Please try the following:
* Without ProtocolLib
* Using just plain Spigot
* Without other plugins

Does the issue persist?
