### ISSUE TITLE
Placeholders in holograms created using API

### ISSUE THREAD

**Issue by SuSeu1414** [filoghost/HolographicDisplays#291]
Is it possible to use placeholders in holograms made with ``HologramsAPI#createHologram``?

I tried doing ``hologram.setAllowPlaceholders(true)``, but my placeholders still work only on holograms created with a command.

**Comment by filoghost** [comment]
Can you provide the code to reproduce this bug?

**Comment by 1CAMOU** [comment]
Hey I am having the same issue. Placeholder do not work when creating with HologramsAPI#createHologram but they do perfectly work when creating Holograms through a command..

This is my code:
`setHologram(HologramsAPI.createHologram(PrisonEvents.getInstance(), getLocation().clone().add(0.5, 1.5, 0.5)));
        for(String textLine : PrisonEvents.getInstance().getConfig().getStringList("supply-drop.holograms.locked")) {
            getHologram().appendTextLine(ChatColor.translateAlternateColorCodes('&', textLine));
        }`

Plugin version is 1.8.8

Is there any way that can work @filoghost ?
