### ISSUE TITLE
Add option for setting how much empty space there should be between the lines.

### ISSUE THREAD

**Issue by AlexProgrammerDE** [filoghost/HolographicDisplays#292]
### Description

The lines have sometimes too few space between them. I saw a plugin that had a leaderboard that looked better than the common one: 

![2020-06-05_10 35 27](https://user-images.githubusercontent.com/40795980/83855420-511b0380-a718-11ea-84dd-9dbba3524958.png)
(The one on the left is made by me and the one on the right is from the plugin.)
I think many holograms would look better with more space between the lines.

**Comment by filoghost** [comment]
It's the first value in `config.yml`, `space-between-lines`.

**Comment by AlexProgrammerDE** [comment]
ok thx. Wow why didnt i see that myself?
