### ISSUE TITLE
Creating a Hologram for the first time

### ISSUE THREAD

**Issue by Krityug** [filoghost/HolographicDisplays#294]
Greetings,
I am using Holographic Displays for the first time. I am having trouble creating a hologram. I could not find your discord so joined. 

My Code: https://hastebin.com/usuyuredeb.java
 (Is this correct or needs to be fixed) I also don't k how to get an instance of a plugin.

Regards,
Krityug Singh

### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):

**Comment by filoghost** [comment]
Code looks fine and should work. Check that your command is actually being executed, maybe try without other plugins.
