### ISSUE TITLE
{player}

### ISSUE THREAD

**Issue by Icebluewolf** [filoghost/HolographicDisplays#296]
### What are you trying to do?

Add The {player} placeholder to my holo.

### What have you tried so far?

I have downloaded ProticolLib (After relizing i needed it. So after i got HD) 

### Platform

- Server version (output of `/version`): spigot 1.15.2
- Holographic Displays version (check with `/hd`): 2.4.2
- ProtocolLib version, if installed (check with `/protocol version`): 4.5.1
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): No

### Additional context

Nope.

**Comment by soshimee** [comment]
Use holographicplaceholders.

**Comment by Icebluewolf** [comment]
I got it and forgot about this thread closed.
