### ISSUE TITLE
Denizen Placeholders do not work

### ISSUE THREAD

**Issue by ZNChano** [filoghost/HolographicDisplays#298]
#39 # Description
I am using "{medium}%denizen_<player.flag[ravager_badge_count]>%"
In a hologram and it is not working. I have parsed the placeholder with Papi and it works just fine, and it works every where else fine, just not within Holo Grams.

### How to reproduce
I'm not sure if it even would be reproducable due to the fact that the script holding the flag from denizen is written by me. The placeholder parses exactly how it should in papi though.

### Platform

- Server version (output of `/version`): 1.15.2
- Holographic Displays version (check with `/hd`): 2.4.2
- ProtocolLib version, if installed (check with `/protocol version`): 4.5.0
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): ProtocolSupport

### Additional context

![image](https://user-images.githubusercontent.com/67173433/85185736-4f4a5780-b263-11ea-81b2-6930b483cee3.png)
![image](https://user-images.githubusercontent.com/67173433/85185759-64bf8180-b263-11ea-9b94-ff77687619e7.png)
![image](https://user-images.githubusercontent.com/67173433/85185763-6a1ccc00-b263-11ea-932e-d503f55ab7b1.png)

**Comment by Icebluewolf** [comment]
Might be differnet but i am having problems with placeholders as well. Just the default ones on there docs.

**Comment by filoghost** [comment]
PlaceholderAPI was not supported before v3.
