### ISSUE TITLE
1.16.1 Spigot Errors

### ISSUE THREAD

**Issue by MJRLegends** [filoghost/HolographicDisplays#299]
### Description

Error on server load

### How to reproduce

Use a Spigot 1.16.1 server and run with plugin installed

### Platform

- Server version (output of `/version`): CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`):  v2.4.2
- ProtocolLib version, if installed (check with `/protocol version`): v4.5.1
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
No

### Additional context

```
[22:21:06] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.4.2
[22:21:06] [Server thread/INFO]: 
 
****************************************************************************
    Holographic Displays does not support this server version.
    Supported Spigot versions: from 1.8.3 to 1.15.
 
    This plugin has been disabled.
****************************************************************************
 
```

**Comment by AtherActive** [comment]
They just need to push an update, may take a couple days most likely

**Comment by HexedHero** [comment]
https://github.com/filoghost/HolographicDisplays/pull/300
