### ISSUE TITLE
Holograms Disappearing

### ISSUE THREAD

**Issue by AaronMcHale** [filoghost/HolographicDisplays#30]
Since updating to Minecraf/Spigot 1.9.4 we have encountered an issue where Holograms around our spawn will all disappear randomly.  We have found that by going to another world (and/or unloading the chunks around spawn) then back to the spawn causes them to re-appear.  Am I the only one with this issue, we are using the Touchscreen Holograms plugin, however have been using that before updating to 1.9.4 and didn't seem to notice this issue.

**Comment by filoghost** [comment]
Sorry for not answering on this. I will now close the issue since it's old, and assume it's fixed. If not, please answer and I will reopen it.

**Comment by ItzMeLilG** [comment]
Hey I have same problem and I'm using Holographic Displays
