### ISSUE TITLE
Citizens issue with holographic display

### ISSUE THREAD

**Issue by ZeyKoYT** [filoghost/HolographicDisplays#309]
### Description

When you create a hologram above a citizen , and every one disconnect from the server , and reconnect 5 minutes later it delete the citizens.

### How to reproduce

create a hologram above a citizen , disconnect , wait 5 minutes , reconnect 

### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 

paper 1.8.8 
lasted holographic display version 
lasted protocol lib
yes

**Comment by Drago903** [comment]
I think the problem is only on paper 1.8.8, try with a new version

**Comment by ZeyKoYT** [comment]
LOL I WAIT SO LONG TIME JUST FOR THAT SUPOSITION LOL

**Comment by Drago903** [comment]
I'm not the developer, wait him

**Comment by filoghost** [comment]
Please try the new beta version on Bukkit Dev. I don't even think it was caused by HD.
