### ISSUE TITLE
i can't use color code.

### ISSUE THREAD

**Issue by filiperose** [filoghost/HolographicDisplays#314]
this is my command : "/hd create bsb &utest".
and this is the output:
![image](https://user-images.githubusercontent.com/29162342/87278009-a9120a80-c50d-11ea-84b8-c3a7a11c8a47.png)

Server Version : 1.15.2.
Holographic Displays version : 2.4.3
plugins on my server:
![image](https://user-images.githubusercontent.com/29162342/87277977-9bf51b80-c50d-11ea-8936-f7dc438d0edd.png)

**Comment by WillKeiser** [comment]
U ever get it to work?
