### ISSUE TITLE
Colored text not working 

### ISSUE THREAD

**Issue by WillKeiser** [filoghost/HolographicDisplays#315]
### Description
 Im putting the color code before the text of the hologram im trying to make but the text still comes out as white. I even copy and pasted the test command for colors and it still came out as white. Couldn't find anything about enabling color in the config ,so I'm completely lost. 

### How to reproduce
 Type in the color before the text and it will just come out as white. 

### Platform

- Server version (output of `/version`):  This server is running CraftBukkit version git-Spigot-05da6fa-b0c6dfe (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`): v2.4.3
- ProtocolLib version, if installed (check with `/protocol version`): Not installed
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): No

**Comment by filoghost** [comment]
Maybe a problem with your client? I can't reproduce the issue.

**Comment by SpyCraft3r** [comment]
Unfortunately I am having the same issue right across my bungee network using the latest protocolLib and HD using 1.16.3. No matter which color codes I use, either the normal or hex it does not work

**Comment by filoghost** [comment]
Can you please try on a clean test server without any other plugin?
