### ISSUE TITLE
Holographic Displays PlaceHolder timings

### ISSUE THREAD

**Issue by darkchroma** [filoghost/HolographicDisplays#317]
### What are you trying to do?
Reduce high ram usage from HolographicDisplays.

### What have you tried so far?
Disabling holographic displays placeholders from baltop. Using essentials economy instead of an item-based economy plugin. These all helped, but the high ram usage from holographic displays continues creeping back.

### Platform
- Paper version git-Paper-110 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
- Holographic Displays v2.4.4-SNAPSHOT-b153
- ProtocolLib v4.5.1
- No.

### Additional context

![image](https://user-images.githubusercontent.com/68187686/88473907-0c705380-cf76-11ea-80ac-382c9e01e778.png)

Thank you for your support,

**Comment by filoghost** [comment]
This is caused by an external placeholder being too slow when updating. There is no way to check which one, try disabling plugins that add new placeholders.
