### ISSUE TITLE
RGB colour

### ISSUE THREAD

**Issue by martijnpu** [filoghost/HolographicDisplays#318]
### Description
Add RGB support. This will improve the quality a lot.
I think the following format is the easiest to implement: &#FF0000

**Comment by ChoqueCastroLD** [comment]
It may be a better option to go with the <#ff00ff> as Skript did

**Comment by DragonSlayer2189** [comment]
lots of other plugins use &#FF0000, so i think it is best to stick with something more standard

**Comment by Pugabyte** [comment]
You can use spigot's internal hex format for RGB on the current version: `&x&9&1&5&b&f&5` (`#915bf5`)

Have the commands parse out `&#FF0000` would still be a very useful addition.

**Comment by filoghost** [comment]
Added in 6830699b48c9e06ec355932823ddc04665c013da, format is &#000000
