### ISSUE TITLE
Allow for arrival directions when teleporting

### ISSUE THREAD

**Issue by PLG** [filoghost/HolographicDisplays#319]
### Description

The Multiverse-Portals plugin allows for the direction on arrival to be appended to teleport commands e.g., `p:portal:se`, with `se` being South East. I would like to suggest the same feature for `/hd teleport`; append a colon and one of the following directions: `n,e,s,w,ne,nw,se,sw`. E.g., `/hd teleport hologram:nw` would teleport the player to the hologram called 'hologram' and then face them in the North West direction.

**Comment by soshimee** [comment]
Maybe yaw/pitch would be better, as it is more adjustable.

**Comment by filoghost** [comment]
Sorry, but why would you need that on teleports? The command `/hd teleport` is only for admins, don't use holograms as warps for users...

**Comment by PLG** [comment]
@filoghost Can I ask why not? Why is that feature only for admins?

**Comment by filoghost** [comment]
Because there are /warp plugins that are better suited for that task. Implementing features is time consuming and bloats the plugin, if they're not widely used.
