### ISSUE TITLE
Holograms don't hide

### ISSUE THREAD

**Issue by DevSchmidtchen** [filoghost/HolographicDisplays#32]
**Hej**
I  use this code:
`Hologram hologram = HologramsAPI.createHologram(plugin, plugin.getLocation("HOLOGRAM"));
                VisibilityManager visibilityManager = hologram.getVisibilityManager();
                
                visibilityManager.showTo(p);
                visibilityManager.setVisibleByDefault(false);
                
                ItemStack is = new ItemStack(Material.SKULL_ITEM, 1, (short)3);
                SkullMeta sm = (SkullMeta) is.getItemMeta();
                sm.setOwner(p.getName());
                is.setItemMeta(sm);
                
                hologram.appendItemLine(is);
                hologram.appendTextLine("§7» §6§lStats §7«");
                hologram.appendTextLine("§7↠ §9gespielte Spiele: §c" + plugin.getMySQLStats().getPlayed(p.getUniqueId().toString()));
                hologram.appendTextLine("§7↠ §9gewonnene Spiele: §c" + plugin.getMySQLStats().getWins(p.getUniqueId().toString()));
                hologram.appendTextLine("§7↠ §9deaktivierte Energiekerne: §c" + plugin.getMySQLStats().getDisabled(p.getUniqueId().toString()));
                hologram.appendTextLine("§7↠ §9Kills: §c" + plugin.getMySQLStats().getKills(p.getUniqueId().toString()));
                hologram.appendTextLine("§7↠ §9Tode: §c" + plugin.getMySQLStats().getDeaths(p.getUniqueId().toString()));
                hologram.appendTextLine("§7↠ §9Punkte: §c" + plugin.getMySQLStats().getPoints(p.getUniqueId().toString()));
                `
If a new player joins, both players see both holograms. But when I used isVisibleTo it says they can only see one of them!
Version: 1.10

Sorry for my bad English, I am from Germany!

**Comment by filoghost** [comment]
Are you using ProtocolLib?

**Comment by DevSchmidtchen** [comment]
No, I only use the plugin itself

**Comment by DevSchmidtchen** [comment]
Did you understand the problem or should I send you a pic later on?

**Comment by filoghost** [comment]
It's strictly needed.

**Comment by DevSchmidtchen** [comment]
Oh, I didn't know that!
