### ISSUE TITLE
Periodic tick skips

### ISSUE THREAD

**Issue by soshimee** [filoghost/HolographicDisplays#322]
### Description

The server skips around 200 ticks in every minute or so when holographicdisplays is enabled, with no tps lag. But this does not happen without holographicdisplays. (So the server is detecting lag even though there is no real lag and causing the lag while trying to clear the unexisting lag.)

### How to reproduce

Just install the plugin and the server severely lags every minute .

### Platform

- Server version (output of `/version`): This server is running Paper version git-Paper-239 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`): 2.4.3
- ProtocolLib version, if installed (check with `/protocol version`): 
ProtocolLib v4.5.0-SNAPSHOT
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): Yes

### Additional context

No errors, just server is x ticks behind.

**Comment by filoghost** [comment]
This is usually caused by placeholders added by external plugins. Try disabling those plugins if you have any, otherwise post a timings report.
