### ISSUE TITLE
HOLOGRAPHIC DISPLAYS, DOES NOT WORK FOR 1.16.2

### ISSUE THREAD

**Issue by adamm17** [filoghost/HolographicDisplays#327]
### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):

**Comment by Esophose** [comment]
Use the latest dev build. This was already reported and marked as closed in #325 

https://ci.codemc.io/job/filoghost/job/HolographicDisplays/156/
