### ISSUE TITLE
Unbearable ticking noise coming from the displays (Conflict with Multiverse Core)

### ISSUE THREAD

**Issue by EvilPandaMan** [filoghost/HolographicDisplays#328]
### Description
 Hello. I'm having a really tough issue with my holographic displays

I'm currently running a server on paper 1.16.1 and since yesterday everything was alright. From this morning, I logged in to the server just to be blasted with a million tick noises making it unbearable to stay logged in. I started pulling all my plugins offline and I pinpoint the issue being a conflict between Holographic Displays and Multiverse core (which they have been working alright all this time). 

I really don't know what to do. Has anyone else been experiencing something similar?

Regards
F

### How to reproduce
 Having Holographic Displays installed with Multiverse Core.

### Platform

- Server version (output of `/version`):  This server is running Paper version git-Paper-131 (MC:1.16.1)
- Holographic Displays version (check with `/hd`): v2.4.4 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):

**Comment by filoghost** [comment]
Does this still happen with the v3 beta version? I had (and still have) no clue what could be causing it.
