### ISSUE TITLE
Hologram Mob Hunting

### ISSUE THREAD

**Issue by Espinete87** [filoghost/HolographicDisplays#330]
### What are you trying to do?

Get fix my holograms

### What have you tried so far?

Change placeholders, tried different plugins.

### Platform

- Server version (output of `/version`): 1.15.2
- Holographic Displays version (check with `/hd`): v2.4.4
- ProtocolLib version, if installed (check with `/protocol version`): v4.5.1
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
Authme

### Additional context

Hello guys, i know maybe you are not the responsable of this, but maybe you can give me a hand.

could you tell me why is not working?
https://i.ibb.co/9rQPg5h/holographic.jpg
Im using:
MC 1.15.2
MobHunting 7.5.5
Holographic Displays v2.4.2
PlaceholderAPI-2.10.9.jar

If that error cant be fixed, could you give me a idea how to achieve that in other ways?
Thanks again!

**Comment by Espinete87** [comment]
up

**Comment by filoghost** [comment]
Sorry for the late answer. Holographic Displays doesn't support PlaceholderAPI natively. You probably want [Holographic Extension](https://www.spigotmc.org/resources/holographicextension.18461/), which is from another developer. If you have problems with that plugin, please do not ask here.

**Comment by Espinete1987** [comment]
Yes i ask becouse the problem is on the database of mobhunting, not in Holographic Extension ( which helped me to show the total kills) but it get reseted everytime i rejoin the game :(
