### ISSUE TITLE
IP based locale support

### ISSUE THREAD

**Issue by kalleswe** [filoghost/HolographicDisplays#333]
### Description
I would like to see support for different locales by IP/GeoIP lookup. I.e. a player with IP coming from country1 should see holograms from database1.yml and country2 should use database2.yml.

This is because many people in diff countries local language often are too young to know english properly. So if they come from within the same country it would be nice to have all holograms in their local language and otherwise use english.

I hope you could make such a support for the plugin that would be cool.

**Comment by filoghost** [comment]
Sorry but that's way too much for the base plugin, and too specific. This can be done with Protocol Lib externally, but it's not a small task.
