### ISSUE TITLE
Hologram Displays not Loading in worlds created by the World System Plugin

### ISSUE THREAD

**Issue by trainerlord** [filoghost/HolographicDisplays#335]
### Description
Creating world using the world system plugin and placing a hologram in it then exiting the world and entering it again causes the hologram not to load and produces this error

`[17:08:18 WARN]: [HolographicDisplays] Hologram 'Craftizz' was in the world 'ID0-ceb4922f-b5fa-4ff0-9433-e3f0f7115a28' but it wasn't loaded.
[17:08:18 WARN]: [HolographicDisplays] Hologram 'Craftizz1' was in the world 'ID0-ceb4922f-b5fa-4ff0-9433-e3f0f7115a28' but it wasn't loaded.`

### Platform

- Server version (`1.16.2`): 
- Holographic Displays version (`2.44`): 
- ProtocolLib version, if installed (4.5.1): 
- Do you use plugins to allow players to join with multiple Minecraft versions (no):

**Comment by filoghost** [comment]
Please try the new beta version on Bukkit Dev. Holograms can now be in unloaded worlds.
