### ISSUE TITLE
Add a setting to emit light from holograms

### ISSUE THREAD

**Issue by ElBananaa** [filoghost/HolographicDisplays#336]
### Description

Add an option that could be enabled on each hologram that emit a light source on the holograms. That's very useful because it makes holograms easier to read,

**Comment by filoghost** [comment]
Thanks for the suggestion.  However, holograms should be considered similar to signs: if you can't see them, add a light nearby. Emitting invisible light involves some weird "hacks" which may not work in future versions. I'm sorry, I will not adding this feature.
