### ISSUE TITLE
[Suggestion] adding this, would be extremely useful

### ISSUE THREAD

**Issue by msmanui** [filoghost/HolographicDisplays#337]
### Description
Hello. Sorry for disturbing you.

It would really nice to add "distance-activation-range" and "permission to view" to HolographicDisplay. This would be to each hologram it self. 
Like for example:

example:
location: eventos, -1333.501, 73.200, -744.142
permission-to-view: none
distance-to-activate-bocks: none
lines:
- '&6 » » »&b&l Parkour FACIL &6« « «'
- ''
- '&f¡Jaja! El titulo lo dice todo.'
- '&fAunque seguro ni este te pasas'

By default it would be none, but u could change permission to the one u like and distance also to a number.

Thanks!

**Comment by filoghost** [comment]
I finally can close this, now there is a configurable view range (for all holograms).
