### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by Fredthedoggy** [filoghost/HolographicDisplays#338]
### Description

There is an error with the Unicode character "❙" which I have seen working in other hologram plugins. It creates a space on the end of the hologram for some reason. I need this specific character, so if anyone knows how to fix this it would be appreciated. (Paper-MC 1.16.2)

### How to reproduce

Create a Hologram, and add a line that contains 10 "❙"s it will have a ton of space on the side

### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 

![Versions](https://user-images.githubusercontent.com/45927799/92999042-c9e5e480-f4eb-11ea-85ee-1434fc444545.PNG)

### Additional context

![Screenshot](https://user-images.githubusercontent.com/45927799/92999046-d2d6b600-f4eb-11ea-81eb-608b9c8885c6.PNG)

**Comment by filoghost** [comment]
If you're using the bold format, try removing it. Otherwise there's nothing that can be done, other than using a different character. Some of them are just rendered as if they were full size.

**Comment by fredthedoggy** [comment]
@filoghost may I ask why it works for some plugins and not others though?

**Comment by filoghost** [comment]
Are they displaying that symbol in a hologram, or in a name tag above a mob or a player? Because inside chat the rendering could be fine, but not on nametags. Could you try with an armor stand or a mob?
