### ISSUE TITLE
1.16.3 not supported

### ISSUE THREAD

**Issue by PengBread** [filoghost/HolographicDisplays#339]
### Description
Plugin doesn't support 1.16.3.

19.09 04:22:35 [Server] INFO [HolographicDisplays] Enabling HolographicDisplays v2.4.3
19.09 04:22:35 [Server] INFO ****************************************************************************
19.09 04:22:35 [Server] INFO Holographic Displays does not support this server version.
19.09 04:22:35 [Server] INFO Supported Spigot versions: from 1.8.3 to 1.16.
19.09 04:22:35 [Server] INFO This plugin has been disabled.
19.09 04:22:35 [Server] INFO ****************************************************************************

### How to reproduce
Load the plugin in 1.16.3 server.

### Platform

- Server version (output of `/version`): 1.16.3
- Holographic Displays version (check with `/hd`):  v2.4.4
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):

**Comment by filoghost** [comment]
You're not using v2.4.4. The log says v2.4.3.

**Comment by PengBread** [comment]
Ah.... my bad. Works now, thanks!
