### ISSUE TITLE
Add command argument tab completion to 1.15.2+

### ISSUE THREAD

**Issue by kaxlabs** [filoghost/HolographicDisplays#345]
### Description

Since 1.15.2, tab completion support for command arguments has been added:
[https://hub.spigotmc.org/javadocs/spigot/org/bukkit/command/TabCompleter.html](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/command/TabCompleter.html)

This would speed up command writing a lot if you could be able to tab the custom hologram names and command arguments.

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
