### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by LokiTheGod123** [filoghost/HolographicDisplays#349]
### What are you trying to do?

placeholder from playtime plugin
### What have you tried so far?

I have papi (they support it) I downloaded holographic placeholders addon. How can I use papa placeholders with hd?

### Platform

- Server version (output of `/version`): 1.16.3 and latest spigot
- Holographic Displays version (check with `/hd`): 2.4.4
- ProtocolLib version, if installed (check with `/protocol version`): 4.6.0
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): yes, viaversion 

### Additional context

no

**Comment by filoghost** [comment]
Sorry but you need to ask the developer of that addon. PlaceholderAPI is not yet officially supported.
