### ISSUE TITLE
New Converter

### ISSUE THREAD

**Issue by orkun1675** [filoghost/HolographicDisplays#36]
I have created a converter for users to switch over to this plugin from the "Holograms" plugin.
Here is the link: https://www.spigotmc.org/resources/holograms-to-holographicdisplays-converter.27821/
Might be useful to add it as a foot note on the plugin page so people can benefit.

**Comment by filoghost** [comment]
Thanks, I've added a note in the end. If more converters are created or Holograms becomes more used, I will give that section more visibility.
