### ISSUE TITLE
Please find a way to separate the Creation of an hologram from its Spawn

### ISSUE THREAD

**Issue by DavidTheExplorer** [filoghost/HolographicDisplays#362]
### Description

This is my first ever opened issue so I'm sorry if it will be a little bit long.

Today I ran into a difficulty when I used _HologramsAPI::createHologram_ because it violates the Single Responsibility Principle(it both creates & spawns the hologram).
What happened: I have a class that gets an hologram in the constructor and spawns it after some time, it could have been very easy if _createHologram_ did what its name suggested and only created the hologram object, instead I had to spend some time to build a wrapper in form of the Builder pattern for the Hologram and each line type - and change the constructor to take an instance of HologramBuilder so I can call its spawn() method in my desired time.

Please fix 👍

**Comment by DavidTheExplorer** [comment]
Update: okay, it can be solved by using the visibility manager ... but please still do the separation.

**Comment by filoghost** [comment]
You're right about the SRP, but right now holograms existing = spawned. I'm keeping the issue open, as I will implement something in the API (e.g. create() vs spawn())

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
