### ISSUE TITLE
Holograms Disappearing when Player Teleports

### ISSUE THREAD

**Issue by AtomixCM** [filoghost/HolographicDisplays#365]
### Description

I seem to be having a problem where the holograms disappear or get cut in half when a player teleports to a location where there haven't been players. The holograms come back when I do /hd reload. I'm running paper 1.8.8 and I'm using HD 2.4.5

I apologize if this problem has been solved. I didn't see much about my particular problem in issues!

### How to reproduce

Teleport to a location that players haven't been to (after a restart or something)

### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
HD 2.4.5
ProtocolLib 4.5.0
ViaVersion 3.1.1

### Additional context

![image](https://user-images.githubusercontent.com/29317588/100410041-79d2e480-303b-11eb-9dc6-c75c62d0b4d3.png)
![image](https://user-images.githubusercontent.com/29317588/100410052-822b1f80-303b-11eb-9035-1f3dd803390e.png)

**Comment by filoghost** [comment]
Can you please try on a clean server? Without ProtocolLib and without ViaVersion. Please also specify the server version (and in this case the client version).

**Comment by AtomixCM** [comment]
I will get back to you as soon as possible. I have a work week ahead of me until monday. Thank you for your patience!

**Comment by filoghost** [comment]
@AtomixCM any news on this?

**Comment by AtomixCM** [comment]
Thank you for following up!

I haven’t gotten around to testing this issue at all. I’ve been taking a
personal break from server related matters.

I’m sorry to leave you hanging!

I’ll try and test this out once I get back in the swing of things.

Thanks again!
