### ISSUE TITLE
Help with API

### ISSUE THREAD

**Issue by Drago903** [filoghost/HolographicDisplays#367]
-->

### What are you trying to do?

Hi, I'm having problems with the API, I'm trying to create holograms that once clicked do certain actions.
Now, once the holograms are placed, how do I "get them recognized"

Let me explain better, I would like to associate an action with a specific hologram but I cannot recall that particular hologram

### What have you tried so far?

I tried to recall it by checking the name of the hologram but it is very glitchy

### Platform

- Server version: Spigot-1.13.2-R0.1-SNAPSHOT
- Java editor?

**Comment by filoghost** [comment]
Sorry for answering late. This is more a programming question, just hold a reference to the hologram when you set a click handler. To create a line (on which you set a click handler), you must have a reference to a Hologram: use that reference inside the click handler callback.
