### ISSUE TITLE
How to change rotating? 

### ISSUE THREAD

**Issue by RockoTheWolf** [filoghost/HolographicDisplays#369]
### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 

### Additional context

hey is there a way to change the way the item rotates?

**Comment by Drago903** [comment]
You can't, this is minecraft.

**Comment by filoghost** [comment]
You can't, it's even the first question in the FAQ.
