### ISSUE TITLE
PickupHandler no longer fires unless you 'jump' over/through the hologram item.

### ISSUE THREAD

**Issue by Cryptite** [filoghost/HolographicDisplays#37]
This has been an issue for quite awhile now and does still seem to be the case. You can no longer 'run' through a Item-Holo and have the pickupHandler fire. Jumping over it or 'falling' through it seems to be the only way that works now.

**Comment by filoghost** [comment]
Sorry for not answering on this. This should have been fixed somewhen, I will now close the issue since it's old. If not, please answer and I will reopen it.
