### ISSUE TITLE
Toggle Command

### ISSUE THREAD

**Issue by Sathenet** [filoghost/HolographicDisplays#372]
### Description

Add a command to enable or disable the visibility of holograms, for many years holograms have been persevered in the minecraft community but a lot of holograms could be the destroyer of the fps of players with a bad pc, in addition to visually annoying depending on the game mode or map where you are, you would see useful to add an example command
[**/holograms toggle**] to toggle the visibility of them at the decision of the players.

**Comment by filoghost** [comment]
I think that allowing players to disable holograms could result in complaints from them: not able to read info (which is often displayed in holograms), not being able to see certain things in minigames, loot crates, etc. Holograms should be pretty efficient client-side: each hologram line is basically just a rectangle with text, no 3D models.

If your server has so many holograms that they are visually annoying or players experience FPS drops, you should probably reduce their amount.
