### ISSUE TITLE
1.7 holograms grouping together

### ISSUE THREAD

**Issue by Mitzythecat** [filoghost/HolographicDisplays#375]
### Description
Hi, I have Holographic Displays version 2.2.6. when I log on, the holograms group together like this
![image](https://user-images.githubusercontent.com/57046639/101663646-dde5a780-3a42-11eb-9b84-35f4b62852a2.png)
I don't know why it is happening. My server version is 1.7.10. 
This doesn't happen with 1.8 clients.

### How to reproduce
have a 1.7 version
use Holographic Displays version 2.2.6
log in with 1.7

### Platform
- Server version (output of `/version`): 
![image](https://user-images.githubusercontent.com/57046639/101663884-1c7b6200-3a43-11eb-88f4-fa1656a8e021.png)

- Holographic Displays version (check with `/hd`): 
![image](https://user-images.githubusercontent.com/57046639/101663908-2309d980-3a43-11eb-958e-0b737a23b9eb.png)

- ProtocolLib version, if installed (check with `/protocol version`): 
![image](https://user-images.githubusercontent.com/57046639/101664015-46348900-3a43-11eb-8aa0-0066ba85f0cf.png)
- No version command. 

- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
- No, as the 1.7 version supports 1.8 players as well

### Additional context
1.8 players see it fine: 
![image](https://user-images.githubusercontent.com/57046639/101664157-68c6a200-3a43-11eb-9273-27629ca7290a.png)

**Comment by Mitzythecat** [comment]
Solved - I removed he blocks above the hologram and replaced them with slabs.

still a weird issue and don’t think it will get fixed

**Comment by filoghost** [comment]
This is an old unsupported version, won't be fixed sorry.
