### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by STRARKTECHNOLOGIES** [filoghost/HolographicDisplays#379]
### What are you trying to do?

Create hologram or basic Usage

### What have you tried so far?

Creating a New Hologram

### Platform

- Server version (output of `/version`): This server is running CraftBukkit version git-Spigot-37d799b-3eb7236 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`): Server is running Holographic Displays v2.4.5 by filoghost
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): No

**Comment by filoghost** [comment]
Please read the documentation... https://filoghost.me/docs/holographic-displays
