### ISSUE TITLE
Support for placeholderAPI (PAPI)

### ISSUE THREAD

**Issue by Klawdek** [filoghost/HolographicDisplays#380]
### Description

Support for PAPI so placeholders from various plugins could be used in holograms.  This would be great for listing top voters, top donators, top balances. top mcMMO, winners of contests and much more.  I have seen servers that use holograms for this purpose and it is nice feature.

I was shocked, horrified and flabbergasted when I saw that HolographicDisplays does not support PAPI.  I was not expecting that.  I had to clutch my knees and rock back and forth on my bed for a few hours afterward.  This is a much needed and expected feature.

**Comment by filoghost** [comment]
Already requested in #100, and planned for v3.
