### ISSUE TITLE
Holograms don't appear when I start the server.

### ISSUE THREAD

**Issue by DavidSaguna** [filoghost/HolographicDisplays#383]
### Platform

- Server version (output of `/version`):
- This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) 
- Holographic Displays version (check with `/hd`): 
- Server is running Holographic Displays v2.2.6 by filoghost
- ProtocolLib version, if installed (check with `/protocol version`): 
- Not installed
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
- Yes, ViaVersion.

**Comment by filoghost** [comment]
You're using an old version, update first. Then you should look in the console if you have any errors.

**Comment by DavidSaguna** [comment]
I updated my version to 2.4.5 and it still happens. I have to do /holo reload

**Comment by filoghost** [comment]
Any error in the console? Does it work without Via Version?
