### ISSUE TITLE
HolographicDisplays & ProtocolLib Issue

### ISSUE THREAD

**Issue by HeyItsRed** [filoghost/HolographicDisplays#388]
### Description
https://hastebin.com/raw/suxinopari
Spams the console 3-4 times on player join, and every so often afterwards

### How to reproduce
Update from main release of ProtocolLib to the Latest Dev build.

### Platform

- Server version (output of `/version`): 1.16.4-R0.1-SNAPSHOT (Tuinity, fork of Paper)
- Holographic Displays version (check with `/hd`): 2.4.5
- ProtocolLib version, if installed (check with `/protocol version`): v4.6.0-SNAPSHOT-b492
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): No

### Additional context
None

**Comment by HeyItsRed** [comment]
A temporary jar of my fix can be located here: [HD 2.4.6](https://github.com/HeyItsRed/HolographicDisplays/releases/tag/2.4.6)

**Comment by eUipKh** [comment]
> A temporary jar of my fix can be located here: [HD 2.4.6](https://github.com/HeyItsRed/HolographicDisplays/releases/tag/2.4.6)

Thank you!

**Comment by TNTUP** [comment]
> A temporary jar of my fix can be located here: [HD 2.4.6](https://github.com/HeyItsRed/HolographicDisplays/releases/tag/2.4.6)

Was getting those errors since yesterday, thanks for this quickfix!

**Comment by filoghost** [comment]
Should be fixed now: https://ci.codemc.io/job/filoghost/job/HolographicDisplays/163/

Can anyone confirm that it's working?

**Comment by eUipKh** [comment]
> Should be fixed now: https://ci.codemc.io/job/filoghost/job/HolographicDisplays/163/
> 
> Can anyone confirm that it's working?

Tested with ProtocolLib v4.6.0-b492 and it's working without problems, thanks ;)

**Comment by Trigary** [comment]
Thank you, that build also fixed the issue for me!

**Comment by filoghost** [comment]
Release v2.4.6 with fix has been submitted to Bukkit Dev. I'm keeping this open for a while to hopefully avoid more duplicate reports.
