### ISSUE TITLE
No API implementation set. Is Holographic Displays enabled?

### ISSUE THREAD

**Issue by S4IVin** [filoghost/HolographicDisplays#390]
### Description
Simply when I start the server I get this warn: https://pastebin.com/YCvM25ct

### How to reproduce
1. Start the server

### Platform

- This server is running Yatopia version git-Yatopia-"aaeb472" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Server is running Holographic Displays v2.4.6-SNAPSHOT-b163 by filoghost
- ProtocolLib v4.6.0-SNAPSHOT-b492
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): No

**Comment by filoghost** [comment]
This is a problem of CrazyCrates, either loading before Holographic Displays (softdepend should be added to plugin.yml). Does Holographic Displays work normally?
