### ISSUE TITLE
Holographic doesn't load the parsed Hex color

### ISSUE THREAD

**Issue by LoneDevilX** [filoghost/HolographicDisplays#391]
### Description

The placeholder parsed is not loaded as the Hex colour should be.

### How to reproduce

Add %luckperm_prefix% by using Holographic Placeholder, and the Hologram doesn't load the Hex Colour.

### Platform

- Server version (output of `/version`): 
`This server is running Paper version git-Paper-334 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)`
- Holographic Displays version (check with `/hd`):
`Server is running Holographic Displays v2.4.5 by filoghost` 
- ProtocolLib version, if installed (check with `/protocol version`): 
`ProtocolLib v4.6.0-SNAPSHOT-b492`
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
Viaversion, ViaRewind, Viabackwards

### Additional context
-- Screenshots, errors, configurations (if relevant) -->
![database](https://use<!r-images.githubusercontent.com/67851836/104130712-3f37c800-53ad-11eb-8d60-224027f9521e.PNG)
![holographic](https://user-images.githubusercontent.com/67851836/104130716-419a2200-53ad-11eb-8dd4-6d1b0262fb6c.PNG)

**Comment by LoneDevilX** [comment]
![database](https://user-images.githubusercontent.com/67851836/104130752-6e4e3980-53ad-11eb-80c4-46da5260a242.PNG)
The database yaml shows the %luckperm_prefix%

**Comment by filoghost** [comment]
Hex colors don't work when coming from placeholders. This is a problem of the plugin adding that placeholder.

**Comment by tiredy** [comment]
> Hex colors don't work when coming from placeholders. This is a problem of the plugin adding that placeholder.

How is that a problem of the plugin that's adding that placeholder? if so, how do i fix it? im using parseother expansion and the hex-colored text that i get back just shows up in plain text instead of having its correct colors parseother has only like 40 or so lines of code in it  and i could not find anything that would be causing that issue
