### ISSUE TITLE
Touchable Holograms doesn't work on 1.12.2

### ISSUE THREAD

**Issue by EternalHuman** [filoghost/HolographicDisplays#393]
### Description

Touchable Holograms doesn't work on 1.12.2

### How to reproduce

Using API

### Platform

- Server version (output of `/version`): 1.12.2
- Holographic Displays version (check with `/hd`): 2.4.5
- ProtocolLib version, if installed (check with `/protocol version`): 4.5.1
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): no

**Comment by DavidTheExplorer** [comment]
I was reading random issues. your fix to the title is wrong, your first one was correct.

**Comment by filoghost** [comment]
Please elaborate, post some code to reproduce the issue.
