### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hyronymos1337** [filoghost/HolographicDisplays#397]
### Description

Console Error

### How to reproduce

IDK

### Platform

- latest 1.16.5 tuinity
- Holographic Displays version (check with `/hd`):  latest
- ProtocolLib version, if installed (check with `/protocol version`):  latest dev build
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):  yes

### Additional context

Error: https://paste.twerion.net/emecawetep.rb
Full Server Log: https://paste.twerion.net/cexemaxeqo.makefile

**Comment by Therkelsen** [comment]
I have a similar issue:

- 1.16.4 Spigot
- Holographic Displays version (check with /hd): Latest
- ProtocolLib version, if installed (check with /protocol version): The Latest Dev Build
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): ViaVersion, ViaRewind, ViaBackwards

Error: https://pastebin.com/7TJTqCVx
Full Server Log; https://pastebin.com/SRkFSVWB

**Comment by Kod3ntz** [comment]
Also having this error. [https://pastebin.com/F7vgmvRg](https://pastebin.com/F7vgmvRg)

Purpur 1.16.5
HolographicDisplays 2.4.5
ProtocolLib 4.6.0-SNAPSHOT-b492
ViaVersion 3.2.1

**Comment by filoghost** [comment]
Duplicate of #388
