### ISSUE TITLE
Individual holograms become armor stands to other players

### ISSUE THREAD

**Issue by guipenedo** [filoghost/HolographicDisplays#40]
So I create a hologram:
`Hologram hologram = HologramsAPI.createHologram(this, location);`
I then show the hologram to player P:
`VisibilityManager vm = hologram.getVisibilityManager();
vm.showTo(P);
vm.setVisibleByDefault(false);`

If then another player joins (who has his own hologram on the same location), he sees a stack of armor stands with a floating stone block on top.
![2016-11-26_16 16 07](https://cloud.githubusercontent.com/assets/3883401/20642347/4a0c58b0-b404-11e6-9f79-db76eb41fc9c.png)

**Comment by guipenedo** [comment]
Using protocollib 4.1.0, HolographicDisplays v2.2.3 and spigot 1.8.3

**Comment by filoghost** [comment]
Confirmed

**Comment by pedroo21** [comment]
Could you please release a version containing this fix? Thank you.

**Comment by pedroo21** [comment]
@filoghost
