### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JustJP2K** [filoghost/HolographicDisplays#401]
https://pastebin.com/LZNKmCB2 

### Platform

- Server version 1.16.5
- Holographic Displays version 2.4.5: 
- ProtocolLib version, if installed 4.6.0: 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):
ViaVersion, ViaBackwards, Geyser

doubt thats the issue though since this error was even before i installed those plugins

**Comment by Kod3ntz** [comment]
Also having this error. [https://pastebin.com/F7vgmvRg](https://pastebin.com/F7vgmvRg)

Purpur 1.16.5
HolographicDisplays 2.4.5
ProtocolLib 4.6.0-SNAPSHOT-b492
ViaVersion 3.2.1

**Comment by filoghost** [comment]
Duplicate of #388
