### ISSUE TITLE
Player get kicked when hit other player

### ISSUE THREAD

**Issue by VenusClietnt** [filoghost/HolographicDisplays#404]
### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):

**Comment by filoghost** [comment]
Follow the template please. I can't fix issues without having any detail.
