### ISSUE TITLE
Hologram update issue

### ISSUE THREAD

**Issue by DebuffPvP** [filoghost/HolographicDisplays#405]
### Description
So i use a plugin called crazy crates and it uses holographic displays as a soft dependency to display holograms with placeholders and other plugins i use with yours as well but the placeholders don't update unless i switch worlds is it possible you could add interval updater for holograms per tick so people can change to update holograms and fix this issue?

### How to reproduce
Stated above ^^^^

### Platform

- This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
- Server is running Holographic Displays v2.4.5 by filoghost
- ProtocolLib v4.5.1
- ViaVersion

**Comment by filoghost** [comment]
Placeholders already do update periodically. Might be Crazy Crates using a high interval, or an unconventional way to update them?
