### ISSUE TITLE
[API] Add some hide/show methods.

### ISSUE THREAD

**Issue by crysis992** [filoghost/HolographicDisplays#41]
Hey, 

I did not found a way to "hide" holograms and "show" them at a later state. I would like to see a methode like hologram.hide() and hologram.show() to hide & show holograms. Like, make them invisible/remove them.

Currently I'm deleting the hologram, creating it at a later state. But its just not a good way to re-add it, add all lines etc.
I would like to see a method, to hide the hologram, and show it at a later state.

**Comment by Kezz101** [comment]
So there's the [`VisibilityManager`](https://github.com/filoghost/HolographicDisplays/blob/master/HolographicDisplays/API/com/gmail/filoghost/holographicdisplays/api/VisibilityManager.java) which you can use to hide/show the hologram to individual players. This isn't really ideal as it requires ProtocolLib and an ideal method wouldn't need ProtocolLib to do this, but it's a suggestion for now!

**Comment by MarkehMe** [comment]
Most servers come with ProtocolLib though. These used to be `hide()` and `show()` methods but they were removed. Maybe these was a reason for this?

**Comment by filoghost** [comment]
The plugin now doesn't require ProtocolLib anymore.
