### ISSUE TITLE
Missing config options?

### ISSUE THREAD

**Issue by Loonyy** [filoghost/HolographicDisplays#415]
### What are you trying to do?
I appear to be missing config options. This is my config:
https://pastebin.com/vyjEKmK0
I'm specifically trying to use the `precises-hologram-movement: false` config option to attempt to fix the lag issue, but when I add it and start up the server the plugin removes it.

### What have you tried so far?
I've tried using previous versions of HD and regenerating my config, it's still the same. I'm using the latest dev build of HD

### Platform

- Server version (output of `/version`): 
- 1.16.5
- Holographic Displays version (check with `/hd`): 
- Latest dev build
- ProtocolLib version, if installed (check with `/protocol version`): 
- 4.6.0

**Comment by filoghost** [comment]
Sorry for the late answer. The option has been removed because is now always active, implemented in a different way that doesn't cause lag.
