### ISSUE TITLE
HD Lag

### ISSUE THREAD

**Issue by Loonyy** [filoghost/HolographicDisplays#416]
### Description
Been getting server lag and after viewing the TPS, the only thing that shows up is Holographic Displays

### Platform
- Server version (output of `/version`): 
- Tuinity version git-Tuinity-"f8c0db4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`): 
- Holographic Displays v2.4.6-SNAPSHOT-b163
- ProtocolLib version, if installed (check with `/protocol version`): 
- ProtocolLib v4.6.0-SNAPSHOT-b492
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
- ViaVersion, ViaBackwards

### Additional context
https://gyazo.com/b602c19adecedd0e72c36f3ad697b6dc The HD part of timings
https://timings.aikar.co/?id=44366e7007e34be4b2b548658cad762e Timings

Would appreciate help ASAP

**Comment by filoghost** [comment]
Some plugin is registering a slow placeholder.  Try removing other plugins, especially the ones that may add their own placeholders.
