### ISSUE TITLE
I can't see holograms.(alse checked faq)

### ISSUE THREAD

**Issue by DarkSerpent67** [filoghost/HolographicDisplays#420]
### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):

**Comment by filoghost** [comment]
Without details, I cannot help you at all.
