### ISSUE TITLE
Wiki has invalid images

### ISSUE THREAD

**Issue by Andre601** [filoghost/HolographicDisplays#421]
### Description

The wiki on this repo uses images from imgur, which no longer exist (Are deleted).
I suggest to upload the images to a more secure place, like this repository and then update the images on the wiki.

More recommended would be to upload the images directly into an image folder on the wiki, which is doable using Git. Then you could basically have `![image](images/image_name.jpg)`

**Comment by filoghost** [comment]
Thanks, I think I fixed all of them, also updated dead links. Feel free to reopen this if I missed anything.
