### ISSUE TITLE
Hologram duplicate

### ISSUE THREAD

**Issue by darksider1010** [filoghost/HolographicDisplays#423]
### What are you trying to do?
I'm trying to show the stats for each player via the hologram. My problem is, when a player joins the game, a hologram appears with the player's stats. As soon as another player enters the game, another hologram appears. I want only one hologram to appear.

### What have you tried so far?
I don't know how to solve the problem.

### Platform
- Server version: git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
- Holographic Displays version: 2.4.6 (latest)
- ProtocolLib version, if installed: 4.6.0 (latest)
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): NO

### Additional context
![duplicaze](https://user-images.githubusercontent.com/78508663/108117159-d5da6180-709c-11eb-83dd-f4667a1f8255.png)

**Comment by Gregor-Davies** [comment]
Are you using placeholderApi? If not placeholderapi is perfect for this.

**Comment by darksider1010** [comment]
> Are you using placeholderApi? If not placeholderapi is perfect for this.

I installed PlaceholderAPI on the server. I would like to create the holograms via the API. What exactly do you mean?

**Comment by Gregor-Davies** [comment]
If your kitpvp plugin supports placeholderapi you could make it so the stats are on a player to player basis.

**Comment by darksider1010** [comment]
> If the plugin supports placeholderapi you could make it so the stats are on a player to player basis.

As far as I don't know. Do you have another idea?

**Comment by Gregor-Davies** [comment]
> > If the plugin supports placeholderapi you could make it so the stats are on a player to player basis.
> 
> As far as I don't know. Do you have another idea?

Sorry that's all I can think of you might have to switch plugins if you can.

**Comment by darksider1010** [comment]
@filoghost

**Comment by filoghost** [comment]
Please try the new beta version on Bukkit Dev. If I remember correctly, it was a Paper or Spigot issue.
