### ISSUE TITLE
MOTD Not Appearing

### ISSUE THREAD

**Issue by adenosine1** [filoghost/HolographicDisplays#425]
### Description
MOTD does not appear when using the {motd: <server>} placeholder. {status: <server>}, {online: <server>} and {max_players: <server>} are working as expected. Pinger is enabled and server IP:Port are correct. 

### How to reproduce

Add {motd: <server>} placeholder to hologram, restart server, MOTD does not appear in the hologram. 

### Platform

- Server version (output of `/version`): git-Paper-468 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`): 2.4.6
- ProtocolLib version, if installed (check with `/protocol version`): v4.6.0
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): ViaVersion

### Additional context

https://pastebin.com/ZkQrgNH1
![2021-02-16_17 49 13](https://user-images.githubusercontent.com/23322409/108136592-f8aa4d00-707f-11eb-92e9-d508b364a4c9.png)

**Comment by Gregor-Davies** [comment]
Try using placeholderapi if not already.

**Comment by adenosine1** [comment]
I tried Pinger from placeholderapi and that worked great. It works perfectly for what I'm wanting however the built in motd placeholder isn't working.

**Comment by GewoonYorick** [comment]
Also experiencing this on my server.

Getting the motd of a 1.12.2 server works fine. 1.16 servers seem to not work.

**Comment by filoghost** [comment]
Confirmed, I was able to reproduce the bug.

**Comment by filoghost** [comment]
Should be fixed in the latest dev builds.
