### ISSUE TITLE
Who can help me with the error I am getting

### ISSUE THREAD

**Issue by Mansitoh** [filoghost/HolographicDisplays#427]
https://prnt.sc/zva08g

### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):

**Comment by Gregor-Davies** [comment]
Seems to be some lines involving FrostyKitmap maybe try contacting them 👍

**Comment by Mansitoh** [comment]
> Seems to be some lines involving FrostyKitmap maybe try contacting them 👍

Si es un plugin que estoy haciendo y utilizo esta api de hologramas

**Comment by filoghost** [comment]
Update, this was fixed.
