### ISSUE TITLE
1.11.2

### ISSUE THREAD

**Issue by TWSSYesterday** [filoghost/HolographicDisplays#43]
Hello my darling, obviously with a new minecraft/server version this plugin needs to be patched for it. Any update would be fantastic. 
Thank you,
Your one and only love

**Comment by filoghost** [comment]
Already works on 1.11.2, no update neeeded

**Comment by TWSSYesterday** [comment]
Not working for me? :o Paper Spigot latest version

**Comment by filoghost** [comment]
Tested with paperclip-991 and it works, even with Protocol Lib. What is the similar issue? Also, what is your problem with the plugin?

**Comment by TWSSYesterday** [comment]
Similar as in holograms have armour stands in them. Holograms still display and 0 errors.

**Comment by TWSSYesterday** [comment]
Issue seems to be with ProtocolLib, I've removed it and armour stands are there on latest paper spigot. Odd how it worked fine with you.

**Comment by filoghost** [comment]
Oh wait, the bug that you referenced was fixed for the newest version of Protocol Lib, I thought it was for the old one. If you compile it the bug will probably go away, I was testing with the patched version.
