### ISSUE TITLE
Gradient Support

### ISSUE THREAD

**Issue by RealCallum** [filoghost/HolographicDisplays#430]
### Description

Add gradient support to the holograms, an example of what it could look like is below.
<#FFFF00>Text Here</#FF8C00">

**Comment by Inxity** [comment]
Just add MiniMessage Adventure support pls

**Comment by Alv5ro** [comment]
I agree with this, please do this!

**Comment by THEqqBULDIpp** [comment]
http://rgb.birdflop.com/
i am using this to create gradients
works fine for me

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
