### ISSUE TITLE
Help with CustomModelData and Clickable Holograms.

### ISSUE THREAD

**Issue by Gohu1** [filoghost/HolographicDisplays#433]
### What are you trying to do?

Hi,

I'm looking for a way to set up customModelData into the ICON feature. I saw in a github issue that's possible but don't really know how handle it. I don't know what i need to write exactly. I'm looking for a way to make my holograms clickable and execute commands too. 

Thanks for help.

### Platform

- Server version (output of `/version`): 1.16.5
- Holographic Displays version (check with `/hd`): v.2.4.6 
- ProtocolLib version, if installed (check with `/protocol version`): v4.5.1
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): Yes.

**Comment by filoghost** [comment]
You need to use NBT data, documented here: https://filoghost.me/docs/holographic-displays/icons

I can't help you with the specific NBT tag, but you can check if it's working with the vanilla /give command.
