### ISSUE TITLE
ProtocolLib issue, infinite packetloop on 1.8.8

### ISSUE THREAD

**Issue by LIWKK** [filoghost/HolographicDisplays#436]
### Description

When HolographicDisplays is used with ProtocolLib it spams an terrible amount of Relmove and RelmoveLook packets, this causes lag on the serverside and also on players side due to the crazy amount of packets being received from server.

This actually causes an infinite loop and the server continues to send you those packets even when they are out of your render distance, normally Minecraft doesn't send those packets if you don't see the entities.

### How to reproduce

Having protocollib and HD in the plugins folder and join the server.

### Platform

- Server version (output of `/version`): This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`):  Server is running Holographic Displays v2.4.6 by filoghost
- ProtocolLib version, if installed (check with `/protocol version`): ProtocolLib v4.6.0-SNAPSHOT
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): Yes, but I have tested this bug and it happens even with only ProtocolLib and HolographicDisplays

**Comment by filoghost** [comment]
Are you sure there is an infinite loop? From looking at the code, I don't any. This is definitely not happening normally with just ProtocolLib and HolographicDisplays, there must be something else causing it. Try without other plugins, just ProtocolLib and HolographicDisplays.

**Comment by filoghost** [comment]
Might be similar to this: https://github.com/filoghost/HolographicDisplays/issues/363

**Comment by filoghost** [comment]
Please try the new beta version on Bukkit Dev. It doesn't use ProtocolLib anymore.
