### ISSUE TITLE
The wiki site is down

### ISSUE THREAD

**Issue by Licoricethecat** [filoghost/HolographicDisplays#437]
### Description
This isn't a bug with the actual plugin, but there's a problem with the site. I need to access the faq and things like that but the site is down and I can't read the FAQ.

### How to reproduce
Going to the FAQ site

### Platform
Chrome? (but it says my browser is working fine)

### Additional context
![Screen Shot 2021-03-11 at 10 33 15 AM](https://user-images.githubusercontent.com/75284785/110812061-4b2cf280-8255-11eb-9328-d5ad13e137e5.png)

**Comment by oskarkk** [comment]
You can find the copy here: 
https://web.archive.org/web/20201204093859/https://filoghost.me/docs/holographic-displays/faq

**Comment by magneticflux-** [comment]
This was caused by the recent catastrophic fire in the OVH datacenter. There's more info on the site now: https://filoghost.me/
![image](https://user-images.githubusercontent.com/9124288/111455672-194bde00-86e4-11eb-8cba-9f0124df347a.png)

**Comment by filoghost** [comment]
I'm late, but this is fixed.
