### ISSUE TITLE
"ICON:" isn't parsed when used in animiations

### ISSUE THREAD

**Issue by HexedHero** [filoghost/HolographicDisplays#439]
### Description

ICON/dropped items in animations don't get parsed.

### How to reproduce

Make an new anmiation called **test.txt** and add
**speed: 0.2
ICON: DIAMOND_SWORD
ICON: IRON_SWORD**

then use 
**{animation: test.txt}**
the ICON's won't get parsed as actual items.

### Platform

- Server version (output of `/version`): 
This server is running Paper version git-Paper-564 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

- Holographic Displays version (check with `/hd`): 
v2.4.6

- ProtocolLib version, if installed (check with `/protocol version`): 
ProtocolLib version 4.6.1-SNAPSHOT-b498

- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
Nope

**Comment by filoghost** [comment]
This is not a bug, animations are placeholders, and placeholders only contain text.
