### ISSUE TITLE
{player} doesn't work I have protocolLib

### ISSUE THREAD

**Issue by AskJayden** [filoghost/HolographicDisplays#440]
### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):

**Comment by TheCiROMG** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ UwU Use this (the latest version)

**Comment by filoghost** [comment]
Also please provide more details, the template exists for a reason.
