### ISSUE TITLE
Java 16 Error stop server

### ISSUE THREAD

**Issue by DoctaEnkoda** [filoghost/HolographicDisplays#442]
### Description
Error when stop server Java 16

### How to reproduce
Purpur 1.16.5 / Java 16

### Platform

- Server version (output of `/version`): >....=>....[11:47:17 INFO]: Checking version, please wait...
>.... [11:47:17 INFO]: This server is running SinonMC version git-Purpur-"f39a5af" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`): 2.4.6 and build test and v3 rebuild test
- ProtocolLib version, if installed (check with `/protocol version`): 4.6.0
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): no

### Additional context
https://hastebin-plus.herokuapp.com/wr8XAN0zuO

**Comment by filoghost** [comment]
Paste is not working
