### ISSUE TITLE
Item holograms falling to the ground

### ISSUE THREAD

**Issue by Esronn** [filoghost/HolographicDisplays#444]
### Description

Item holograms fall to the ground.
After creating item hologram through BetonQuest, I've discovered that the items fall to the ground after a while. I have now tried it directly through HD and not using beton, still happens for us. We assume it's a plugin mis-match and something to do the areas being unloaded and then loaded.
It could take up to 20min after loading up before we discover a item hologram fallen to the ground.

### How to reproduce

So far we've tried everything we can think of + devs from the Beton team have tried and we can not report a 100% safe reproduction step by step.

### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 

Server version: git-Tuinity-"502d57b" (MC: 1.16.5)
HolographicDisplays (2.4.6-SNAPSHOT-b163)
ProtocolLib (4.6.0-SNAPSHOT-b492)
We do have viaversion.

Full plugin list of that server:
`AdvancedAchievements, AdvancedRegionMarket, AnnouncerPlus, AntiTNTDupe, ARIA, AuctionHouse, BetonQuest, BigDoors, BigDoorsOpener, BlockParticles, BungeeGuard, CalebCompass, ChatControlRed, Citizens, CMI, CMIPaperLib, CoreProtect, CraftingStore, CrazyCrates, CustomCrafting, CustomGUI, DailyBonus, DeluxeMenus, Denizen, DiscordSRV, DungeonsXL, dynmap, Dynmap-Towny, EcoEnchants, EffectLib, Emotes, EntityTrackerFixer, FakeBlock, FastAsyncWorldEdit, HolographicDisplays, InteractionVisualizer, InteractiveBoard, Jobs, LibsDisguises, LightAPI, LiteBans, LuckPerms, LWC, LWCTrust, MCJukebox, mcMMO, MineSecure, MiniaturePets, MIReplacer, MMOItems, MobFarmManager, ModelEngine, ModelEngineEX, Multiverse-Core, MyCommand, MysqlPlayerDataBridge, MythicLib, MythicMobs, PacketListenerApi, PlaceholderAPI, Plan, PlugMan, PrometheusExporter, ProtocolLib, PvPManager, SelectionVisualizer, Shop, ShopGUIPlus, SilkSpawners, spark, StaffFacilities, SuperTrailsPro, SurvivalInvisiframes, TAB-BukkitBridge, TeleCraft, TokenManager, Towny, TownyNameUpdater, TradeMe, UltimateVotes, Vault, Vehicles, VehiclesFlags, ViaVersion, ViewDistanceTweaks, WolfyUtilities, WorldBorder, WorldGuard, WorldGuardExtraFlags`

### Additional context

We have tried disabling plugin after plugin and are not yet successful in finding what it could be, it takes a while for the bug to appear at times.

Example Screenshot:
https://i.imgur.com/dybU0F2.png
What it looks like before the bug happens:
https://i.imgur.com/TAbA1cV.png

**Comment by filoghost** [comment]
Please try without ViaVersion, and if that doesn't work try using Spigot instead of Tuinity. This is probably be a server issue, I remember that the same bug was happening on old versions. I will add a workaround if this also happens on standard Spigot without other plugins (and if it's possible to do it).

**Comment by Drc-DEV** [comment]
I use Paper and this does not happen. This is most probably a Tuinity-related issue. I would suggest using Paper instead of Tuinity as it's more stable and has most of the optimizations you need (most of Tuinity additions get merged in Paper after being tested)

**Comment by Esronn** [comment]
Hello, can confirm now that it's not viaversion or tuinity, must be a third party plugin we run.
