### ISSUE TITLE
VisibilityManager doesn't work for making holograms invisible

### ISSUE THREAD

**Issue by DavidTheExplorer** [filoghost/HolographicDisplays#445]
### Description
Hello! I'm trying to spawn an **invisible** hologram above the player, but it just spawns and is clearly visible.

### How to reproduce
This is my code: 
`Hologram hologram = HologramsAPI.createHologram(Plugin.getInstance(), player.getLocation().add(0, 2.2, 0));
hologram..appendTextLine(ChatColor.GREEN + player.getName() + " Test");
hologram.getVisibilityManager().setVisibleByDefault(false);
`

### Platform
- Server version (output of `/version`): _This server is running CraftBukkit version git-Spigot-9639cf7-4b9bc9d (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)_
- Holographic Displays version (check with `/hd`): _v2.4.6_
- ProtocolLib version, if installed (check with `/protocol version`): Uninstalled
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): Not at all.

**Comment by filoghost** [comment]
Protocol Lib is required for this feature.

**Comment by DavidTheExplorer** [comment]
@filoghost may I request that you completely remove this issue? I don't want it to appear

**Comment by filoghost** [comment]
Why? It can be helpful for others facing the same issue. And it's not a stupid question.
