### ISSUE TITLE
Trying to save holograms in a HashMap

### ISSUE THREAD

**Issue by juststopp** [filoghost/HolographicDisplays#448]
### What are you trying to do?

When I start my server, I call a function to create my holograms. Then, I would like that at each kill I can retrieve these holograms in another function that will edit the hologram to display the top 10 best killers.

### What have you tried so far?

J'ai essayé de sauvegarder mon hologramme dans une HashMap nommée holograms après sa création, pour ensuite la récupérer dans mon autre fonction, mais quand je fais `System.out.println(holograms)`, il revient en tant que `null`.

### Platform

- Server version (output of `/version`): 1.8.8
- Holographic Displays version (check with `/hd`): 2.4.6
- ProtocolLib version, if installed (check with `/protocol version`): Not installed
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): ViaVersion (1.6.0)

### Additional context

![image](https://user-images.githubusercontent.com/69150118/115020762-4f36da80-9ebb-11eb-9c93-e4d84c5fab73.png)
![image](https://user-images.githubusercontent.com/69150118/115020771-5362f800-9ebb-11eb-9bc0-9f8b7fb1587f.png)
![image](https://user-images.githubusercontent.com/69150118/115020797-5b229c80-9ebb-11eb-8a12-a3844bc8d8c5.png)

**Comment by filoghost** [comment]
Sorry for the late answer, but this looks like a programming question, not related to the use of the API.
