### ISSUE TITLE
HologramAPI bug

### ISSUE THREAD

**Issue by EpicGodMC202** [filoghost/HolographicDisplays#450]
### Description
HologramAPI#createHologram is not spawning a hologram and fails to create it
this ONLY happens about 40 ticks after startup when i am trying to load an object that contains an hologram.
after debugging i noticed the code stops after the line with HologramAPI#createHologram. im also sure the parameters were valid. when i attempt to spawn a hologram at a later time it works correctly

### How to reproduce
attempt to create hologram using HologramAPI#createHologram about 40 ticks after startup using a scheduler

### Platform

- git-Paper--408 (MC: 1.16.4) (API version: 1.16.4-RO.1-SNAPSHOT)
- Holographic Displays v2.4.6
- ProtocolLib v4.6.0
- No interfering plugins used

**Comment by filoghost** [comment]
Please provide a code snippet to reproduce this issue. Also try updating your server version, using just Spigot, and without any other plugin installed.
