### ISSUE TITLE
Ping and USer Count Not Updating

### ISSUE THREAD

**Issue by Minecav** [filoghost/HolographicDisplays#451]
### What are you trying to do?

Fix issue with HD not showing spigot servers online nor showing the player count in the lobby.

### What have you tried so far?

Updated HD and ProtocolLib to latest verisions. Checked IP address and ports of servers in Bungee's config.yml, confirmed those IP's and ports match the spigot servers server properties file. Confirmed syntax is correct inside of dataybase.yml is correct.

### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
Server 1.11
HD v2.4.6
PL 4.6.0
Yes we have ViaVersion's latest version installed.

### Additional context

Here's all the config info:
https://pastebin.com/EcdjgST1

All servers (bungee plus spigot) are running on a dedicated centos7 box. I've tried disabling firewalld to see if it was a firewall problem, same thing. It won't ping the other servers, or update the player count. Another plugin that shows server info in a compass does in fact show the player count ok..

**Comment by Minecav** [comment]
Issue Fixed.

**Comment by KagetaneHiruko** [comment]
Hey, can you tell us what you have done to resolve your problem?
