### ISSUE TITLE
Entire text not showing using code hexadecimal (with gradient effect)

### ISSUE THREAD

**Issue by cercus** [filoghost/HolographicDisplays#456]
### Description

When I use the command setline ou addline with some hexa format code, only a part of text is showing (in my case, I would create a hologram with gradient effet (yellow to red) with text "Bienvenue dans le monde minage", but only the text "Bienvenue dans le monde" is showing)

### How to reproduce

- Create an hologram with command /hd create test
- Edit the hologram (/hd edit test )
- Execute the command : /hd setline test  1 &eB&#fef63fi&#feef3fe&#fee73fn&#fee03fv&#fed93fe&#fdd13fn&#feca3fu&#fec33fe &#febb3fd&#feb43fa&#fead3en&#fea53fs &#fe9e3fl&#fe973fe &#fe8f3fm&#fe883fo&#fe813fn&#fe793fd&#fe723fe &#fe6b3fm&#fe633fi&#fe5c3fn&#fe553fa&#fe4d3fg&#fe463fe &c!

### Platform

- Server version (output of `/version`): CraftBukkit version 3069-Spigot-bd6b566-51e2981 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`): Holographic Displays v2.4.6
- ProtocolLib version, if installed (check with `/protocol version`): No installed
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): No

**Comment by filoghost** [comment]
There's a limit on text length, 300 characters, to avoid client side lag with very long lines. I will check if this limit can be raised and/or make it ignore colors.
