### ISSUE TITLE
Holograms Created Via API are removed after restart.

### ISSUE THREAD

**Issue by NiceCraftz** [filoghost/HolographicDisplays#457]
### Description

Upon stopping and starting the server holograms created using the API are removed.

### How to reproduce

Stop the server and restart.

### Platform

- Server version (output of `/version`):  git-PaperSpigot-"4c7641d"
- Holographic Displays version (check with `/hd`):  v2.4.6
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): No.

### Additional context

![2021-05-20_19 24 23](https://user-images.githubusercontent.com/47219477/119022512-07ffa600-b9a1-11eb-80b5-24d5ccdb3271.png)

**Comment by filoghost** [comment]
This is intended, they are not persistent. You need to save them explicitly.
