### ISSUE TITLE
update 1.17

### ISSUE THREAD

**Issue by Longplay1** [filoghost/HolographicDisplays#470]

**Comment by filoghost** [comment]
Added in development builds: https://ci.codemc.io/job/filoghost/job/HolographicDisplays/

**Comment by PremiereSetups** [comment]
Not sure if it's just me but that latest build is failing.

**Comment by VanillaChan6571** [comment]
@filoghost No. Your build failed so there is none. Request to reopen since this isn't fully closed.

**Comment by filoghost** [comment]
It's fixed now.

**Comment by VanillaChan6571** [comment]
Tested and works on spigot-1.17-3145.jar+ Thanks for the update!
