### ISSUE TITLE
1.17 does not start 

### ISSUE THREAD

**Issue by thiagogebrim13** [filoghost/HolographicDisplays#474]
### Description
Does not start on my server and gives an error

### How to reproduce
Install plugin on 1.17 server and start

### Platform

- Paper 1.17 latest: 
- 2.4.7: 
- 4.7.0: 
- no: 

### Additional context
 ![image](https://user-images.githubusercontent.com/75040244/122275282-e7504080-ceb9-11eb-8180-e2c8e8aeb601.png)

**Comment by filoghost** [comment]
Please try the latest dev build: https://ci.codemc.io/job/filoghost/job/HolographicDisplays/

**Comment by thiagogebrim13** [comment]
Resolved!
