### ISSUE TITLE
API bug

### ISSUE THREAD

**Issue by kadenscott** [filoghost/HolographicDisplays#477]
### Description
When attempting to create a hologram with `HologramsAPI#createHologram`, the [plugin errors out](https://bytebin.lucko.me/5s0YhqhrsR). I've experienced this bug with both 2.4.7 and 2.4.8-SNAPSHOT (build #173).

### How to reproduce
[Relevant code.](https://gist.github.com/kadenscott/20975293fe55f4571641601e3a18bc5e)

`HologramManager` is constructed and `createHologram` is called within my plugin's onEnable method.

### Platform

- Server version (output of `/version`):
```
[05:36:50 INFO]: This server is running Paper version git-Paper-777 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 1 version(s) behind
Previous version: git-Paper-775 (MC: 1.16.5)
```
- Holographic Displays version (check with `/hd`):
```
[05:37:09 INFO]: Server is running Holographic Displays v2.4.8-SNAPSHOT-b173 by filoghost
```
- ProtocolLib version, if installed (check with `/protocol version`): 
Not installed, but the same issue occurs if it is.
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
Nope. I've produced this bug with just HolographicDisplays and my test plugin installed.

**Comment by filoghost** [comment]
Did you add a softdepend or depend to Holographic Displays in your plugin.yml?

**Comment by kadenscott** [comment]
Yep, tried both depend and softdepend. Looking in the console confirms HD was enabled before my plugin.

**Comment by kadenscott** [comment]
Solved. The issue was with my Gradle project setup; the HolographicsDisplays dependency was set as `api` instead of `compileOnly`. Sorry for bothering you with this, such a dumb mistake, haha

**Comment by filoghost** [comment]
Glad to hear it was fixed.
