### ISSUE TITLE
Update v2.4.7 changelog to documentation site.

### ISSUE THREAD

**Issue by PlayingWithPi** [filoghost/HolographicDisplays#479]
### Description
Update the documentation to reflect the v2.4.7 update that was released with Changelog(s).

Also, CI isn't working, fails on the final CloudFlare check.
![image](https://user-images.githubusercontent.com/82283945/122628218-d3206500-d0ac-11eb-8c64-f856f28142f8.png)

**Comment by rhystedstone** [comment]
You can't go directly to codemc.io.
Try this: https://repo.codemc.io/#browse/browse:maven-public

**Comment by Amelia-exe** [comment]
> You can't go directly to codemc.io.
> 
> Try this: https://repo.codemc.io/#browse/browse:maven-public

Using the link in the GitHub repo, that's what happens....

May want to fix that 😬

**Comment by filoghost** [comment]
CI was under maintenance and is back online. I'll update the changelog, thanks.
