### ISSUE TITLE
Add clickable messages for /hd list (Teleport one)

### ISSUE THREAD

**Issue by danirod12** [filoghost/HolographicDisplays#482]
### Description

Add clickable messages for /hd list. So users will click on message and teleport to hologram
![2021-06-19_19 37 46](https://user-images.githubusercontent.com/69750264/122649354-21c61180-d136-11eb-9a27-7f07473f4475.png)

```
TextComponent text_component = new TextComponent("- NAME at x: X y: Y z: Z (lines: LINES, world \"WORLD\")");
text_component.setClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/hd teleport NAME"));
Player.spigot().sendMessage(text_component);
```

**Comment by filoghost** [comment]
Good idea. Will be implemented later, in v3.

**Comment by Official-DenBeKKer** [comment]
Also add clickable buttons "next page" and "previous page" if not yet

Look to CoreProtect lookup command. Thay have very cool arrows

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
