### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays

### ISSUE THREAD

**Issue by rkfsociety** [filoghost/HolographicDisplays#488]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

after restart or at startup ...

### How to reproduce

[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@459bf537[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@459bf537[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@7de88ea5[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@7de88ea5[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@2bebfad2[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@2bebfad2[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@7f52f397[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@7f52f397[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@481758a5[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@481758a5[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@6744d15[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:48 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:48 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@6744d15[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:49 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:49 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@30115690[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:49 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:49 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@30115690[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:49 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:49 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@8a1914c[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:49 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:49 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@8a1914c[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:49 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:49 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@3b5cdf9f[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:49 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:49 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@3b5cdf9f[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:49 UTC ERROR] [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
[ср, 23. июн. 2021 15:31:49 UTC ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@31d4f838[
    a=2572
    b=0
    c=0
    d=0
    e=88
    f=0
    g=true
    h=true
    i=true
  ]
[ср, 23. июн. 2021 15:31:49 UTC ERROR] [HolographicDisplays] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for HolographicDisplays

### Server version

 CraftBukkit version 3160-Spigot-f773da8-295ab08 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Holographic Displays version

HolographicDisplays version 2.4.7

### ProtocolLib version (if installed)

ProtocolLib version 4.7.0-SNAPSHOT-b521

**Comment by rkfsociety** [comment]
just installed version HolographicDisplays-2.4.8-SNAPSHOT

**Comment by filoghost** [comment]
The full error is missing, because it only displays it a few times to avoid spamming the console. Can you go back in the server log and find the first occurrence?

**Comment by filoghost** [comment]
Does it work with the newer dev build?

**Comment by rkfsociety** [comment]
> Does it work with the newer dev build?

With the developer's version, everything works fine, without errors.
