### ISSUE TITLE
Animated items

### ISSUE THREAD

**Issue by MatsG23** [filoghost/HolographicDisplays#489]
### Description

It would be cool if you could animate items.
I tried `ICON: {animation: swords.txt}` and `{animation: swords.txt}` (with the corresponding animation text) and couldn't get it working. I believe it's not possible yet.

**Comment by Redblock6YT** [comment]
+1 I would like to see this!

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
