### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by GunacP40** [filoghost/HolographicDisplays#490]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

HolographicDisplays appears to be lagging my server https://spark.lucko.me/P7LCHGARfI
Using java 16 and purpur 1.16.5

### How to reproduce

I cannot really tell how to reproduce this since it just happens

### Server version

This server is running Purpur version git-Purpur-1169 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) You are 16 version(s) behind Previous version: git-Purpur-1115 (MC: 1.16.5)

### Holographic Displays version

 HolographicDisplays version 2.4.8

### ProtocolLib version (if installed)

ProtocolLib version 4.6.1-SNAPSHOT-b505

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards

### Additional information

https://spark.lucko.me/P7LCHGARfI

**Comment by blake-tisbury** [comment]
Getting the exact same issue. On a 40-60 player server. 
![image](https://user-images.githubusercontent.com/61334533/123339682-06ce1580-d519-11eb-9548-bdf9480f78b1.png)

**Comment by filoghost** [comment]
@GunacP40 caused by an externally added placeholder being slow. @blake-tisbury please share the timings.
