### ISSUE TITLE
Holograms teleporting when initially created

### ISSUE THREAD

**Issue by NoneTakenjvm** [filoghost/HolographicDisplays#494]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

So when a hologram is initially created (I created it via the API) it appears to teleport about a block higher for a what seems like one tick and then goes to the intended location.

These are individual holograms and I am using the visibility manager before writing any lines.

GIF here to illustrate: https://gyazo.com/f62eb2dadfea62eb198b9326fac89182

### How to reproduce

Create a 1.8 spigot server
Create a hologram using the API - For specificity, these steps:
  - Create hologram
  - Show to player
  - Set default visibility to false
  - Edit lines or etc

### Server version

This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Holographic Displays version

HolographicDisplays version 2.4.8

### ProtocolLib version (if installed)

ProtocolLib version 4.6.0

### Installed plugins that allow players to join with multiple Minecraft versions

None

**Comment by filoghost** [comment]
Please try the new v3 beta version. The implementation has changed substantially.
