### ISSUE TITLE
TouchHologram sometime not firing, it's quite random

### ISSUE THREAD

**Issue by Oskang09** [filoghost/HolographicDisplays#495]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I'm a developer currently working with touch hologram for my own plugins. so the issues was sometime the touchHandler is firing, sometimes is not and is able to fix with, rejoin, refresh chunk. And tried debug with PlayerInteractEntityEvent listener with monitor priority and ignoreCancellation, also sometimes is firing and sometimes is not and the entity is CraftSlime ( when click firing ).

### How to reproduce

1. Create Hologram using DeveloperAPI
2. Set touchable for single or each line
3. Keep clicking and spamming

### Server version

Paper version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Holographic Displays version

2.4.6

### ProtocolLib version (if installed)

ProtocolLib version 4.6.1-SNAPSHOT-b505

### Installed plugins that allow players to join with multiple Minecraft versions

only 1.16.5

### Additional information

All i put is quite near, but it's work fine and randomly break.

![image](https://user-images.githubusercontent.com/15674107/124380065-58328d80-dced-11eb-8b28-3eab47c7b710.png)

---

Plugin List: ChestSort, Citizens, DeathMessages, DiceFurniture, DiscordSRV, EternalCentury, FartherViewDistance, FastAsyncWorldEdit (WorldEdit), FeatherBoard*, FurnitureLib, HolographicDisplays, Hyperverse, ImageDisplays, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, LightAPI, MangoQuest, mcMMO, MVdWPlaceholderAPI*, NBTAPI, NetheriteShield, PlaceholderAPI, PlayerParticles, PlotSquared, ProtocolLib, RandomTeleport, React*, Reactant, Resquare, SkinsRestorer, SuperVanish, TabList, UniversalGUI, Vault, VoidGenerator, WorldGuard

Example code for generating hologram
```kotlin
        val premiumPrev = HologramsAPI.createHologram(ECCore.instance, Location(world, 118.5, 72.5, 40.0))
        premiumPrev.visibilityManager.isVisibleByDefault = true
        premiumPrev.appendTextLine("&f[&5令牌&f] &a上一页".toColorized())
        premiumPrev.appendItemLine(ItemStack(Material.SOUL_CAMPFIRE))
        premiumPrev.onTouch {
               // some handler
        }
```

---

Sometime hologram is collidable, when collidable mean clickable, when not collidable touchHandler not firing at all. so is it something wrong or issues can cause the entity not spawning? like spawning limit

**Comment by filoghost** [comment]
Please try the new beta version on Bukkit Dev. It doens't use real entities anymore.
