### ISSUE TITLE
Total player count 0 when pinger is enabled.

### ISSUE THREAD

**Issue by htbrown** [filoghost/HolographicDisplays#502]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

When the pinger is enabled in the config, `{online: ALL}` displays 0 even though there are players online.

### How to reproduce

1. Enable the pinger and configure servers in the config.yml file.
2. Try to add `{online: ALL}` to a hologram.

### Server version

Paper 1.17.1 bulid 98

### Holographic Displays version

2.4.8 (development)

### ProtocolLib version (if installed)

4.7.0

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards, ViaRewind (all on proxy)

**Comment by filoghost** [comment]
Sorry for not answering back then. I'm closing this assuming the issue was solved.
