### ISSUE TITLE
When using VisibilityManager (not visible by default and showing to a player) the hologram text disapears but not the item

### ISSUE THREAD

**Issue by Redblock6YT** [filoghost/HolographicDisplays#503]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

When you use the VisibilityManager and set invisible by default and show to a player with the Holographic Displays API:
`Hologram holo = HologramsAPI.createHologram(plugin, tutloc);

            VisibilityManager visibilityManager = holo.getVisibilityManager();
            visibilityManager.setVisibleByDefault(false);
            visibilityManager.showTo(p);

            holo.appendTextLine(translate("&4&lCLICK TO PLAY"));
            holo.appendTextLine(translate("&fTour Guide"));
            ItemStack holoitem = new ItemStack(Material.WOOL, 1, DyeColor.RED.getWoolData());
            holo.appendItemLine(holoitem);`
            
The text will not appear to the other players, but the icons will:
First Player:
![Screenshot_34](https://user-images.githubusercontent.com/37982990/125211832-49ad1e80-e277-11eb-9e8a-48cf8100c824.png)

Second Player:
![Screenshot_35](https://user-images.githubusercontent.com/37982990/125211823-34d08b00-e277-11eb-9da4-03736e65446b.png)

Side-by-side:
![Screenshot_36](https://user-images.githubusercontent.com/37982990/125211829-3ac66c00-e277-11eb-9490-de80695af73e.png)

### How to reproduce

1. Using the Holographic Displays api, create a hologram that is not visible by default and has text and an item
2. Show the hologram to 1 player
3. Get 2 players on the same server, and you will see the icon on one of the player's screens

### Server version

This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Holographic Displays version

HolographicDisplays version 2.4.8

### ProtocolLib version (if installed)

ProtocolLib version 4.7.0

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards, ViaRewind, ViaPotions

**Comment by filoghost** [comment]
Please use the new beta version on Bukkit Dev.
