### ISSUE TITLE
Could not pass event EntityDamageByBlockEvent

### ISSUE THREAD

**Issue by Deathinflames** [filoghost/HolographicDisplays#506]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Hello, i updated my server to paper 1.17.1 and in addition to HolographicDisplays v2.4.8 i am also using the following:

MMOItems v6.6.0
ProtocolLib v4.7.0

I seem to be receiving the following error when stepping in lava or being hit by a hostile entity. The damage indicator doesn't seem to be working and this error displays each tick making it pretty spammy.
https://pastebin.com/raw/JrMX6xqK

I've reported it to the MMOItems dev team and they have advised that this is an issue with HolographicDisplays.

### How to reproduce

Install HolographicDisplays v2.4.8 and MMOItems v6.6.0 on a 1.17.1 server and then step into lava.

### Server version

This server is running Paper version git-Paper-112 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bc127ea)

### Holographic Displays version

HolographicDisplays v2.4.8 and dev build 178

### ProtocolLib version (if installed)

ProtocolLib v4.7.0

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards, ViaRewind

**Comment by Sixsoul** [comment]
Same issue. Confirmed with MMOItems support that it is in fact a holographic displays issue. Hopefully we get a resolution soon!

**Comment by filoghost** [comment]
Should be fixed with 11664497cc31583dcaff2d95f45250594a85c667, try latest dev build please

**Comment by Deathinflames** [comment]
This error is no longer appearing in the console with the latest dev build on my end. Thank you so much!
