### ISSUE TITLE
there are no holograms yet create one with /holo create Yet i see holograms i dont want there

### ISSUE THREAD

**Issue by bramfreul** [filoghost/HolographicDisplays#508]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

well i got these old holograms here and i cant get rid of them
![image](https://user-images.githubusercontent.com/88008488/127070275-453894ca-3184-40eb-8c11-7922c4e5e4b8.png)

### Holographic Displays version

version 2.4.8

**Comment by filoghost** [comment]
Please try the new beta version on Bukkit Dev.
