### ISSUE TITLE
(HologramAPI) getName() doesn't exist?

### ISSUE THREAD

**Issue by WallyTube** [filoghost/HolographicDisplays#509]
### Description

I'm fairly new to the HologramAPI, so it was very surprising that there was no way to get a hologram by its name. This seems like a pretty necessary feature to have, so here's my suggestion. (Side Note, yes, I did look on the API website beforehand. If such a thing does exist, forgive me.)

How it would work:

```java
            for (Hologram holo : getHolograms(Main.get())) {
                if (holo.getName().equals("HologramName")) {
                    Hologram selectedHolo = holo;
                }
            }```

**Comment by filoghost** [comment]
When you create a hologram, the method returns the created hologram. Create an object wrapping it and give it a name, then store it in a collection.
