### ISSUE TITLE
Being able to animate whole hologram, not only make one changing line with animated placeholder.

### ISSUE THREAD

**Issue by THEqqBULDIpp** [filoghost/HolographicDisplays#510]
### Description

It would be great if we would be able to somehow set up 2-3 versions of same hologram that change over time.
With placeholders it is possible to set up only one line this way, and no possibility to synchronize them. 

It would be nice to have only one hologram changing over time than having 0 of them all around spawn.

**Comment by THEqqBULDIpp** [comment]
Or beong able to put couple of lines at once in SampleAnimation.txt

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
