### ISSUE TITLE
Delayed movement with API usage

### ISSUE THREAD

**Issue by BenHall-1** [filoghost/HolographicDisplays#515]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [x] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I'm attempting to move the holograms above someone's head whenever they move (to use them as extra nametags above heads) and there appears to be a slight delay between using `.teleport` and it actually teleporting.

Is there anything I can do to fix that? 

### Holographic Displays version

HolographicDisplays version 2.4.9

### Additional information

A link to see the delay: https://drive.google.com/file/d/1bx0wKDMkznmjZnb5BRfs8llgXaD-TSyF/view?usp=sharing

**Comment by filoghost** [comment]
This is a client side issue, that tries to "smooth" the movement. There is also a delay between the client and the server.
