### ISSUE TITLE
RelativePlaceholder's doesn't work in API.

### ISSUE THREAD

**Issue by xVorttex** [filoghost/HolographicDisplays#518]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I'm using this code, and the placeholder is not replacing to each player's name:
hologram.appendTextLine("Hello, {player} !");

### How to reproduce

Read desc

### Server version

Doesnt matter

### Holographic Displays version

Latest

### ProtocolLib version (if installed)

Latest

### Installed plugins that allow players to join with multiple Minecraft versions

no any

**Comment by nathanosoares** [comment]
Did you use `hologram.setAllowPlaceholders(true)`? (https://github.com/filoghost/HolographicDisplays/blob/master/Plugin/src/main/java/com/gmail/filoghost/holographicdisplays/bridge/protocollib/current/ProtocolLibHookImpl.java#L150)

Are you using protocollib? (https://github.com/filoghost/HolographicDisplays/blob/e406dfc9a5/Plugin/src/main/java/com/gmail/filoghost/holographicdisplays/HolographicDisplays.java#L261)

**Comment by filoghost** [comment]
Please try the new beta version on Bukkit Dev. I assume ProtocolLib was enabled, you probably needed to allow placeholders.
