### ISSUE TITLE
Support for holographic displays of chests.

### ISSUE THREAD

**Issue by ErythroCraft** [filoghost/HolographicDisplays#519]
### Description

Hi

Have you got an example or can you create an update to see hologramms of containers
without opening the container?

My idea is to see a hologramm of the inner of any chest as an hologramm.
Watch this [video](https://www.youtube.com/watch?v=G2LA7tzSF48&t=24s) what I meen.

I know it will take many time to create this future.

**Comment by filoghost** [comment]
It could be an addon, but it won't be like in the video. Sorry, it will not be added to the base plugin.
