### ISSUE TITLE
ProtcollLib spamming my ocnsole.

### ISSUE THREAD

**Issue by XipsAhoy** [filoghost/HolographicDisplays#520]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

My console is getting spammed with this error:

https://pastebin.com/Yy1TBqV1

### How to reproduce

1. Log onto the server
2. Check the console.

### Server version

git-Paper-266 (MC: 1.17.1)

### Holographic Displays version

2.4.9

### ProtocolLib version (if installed)

4.7.0

**Comment by wearenoobsuk** [comment]
Same here,

**Comment by filoghost** [comment]
Please use the new beta version on Bukkit Dev, it doesn't use ProtocolLib anymore.
