### ISSUE TITLE
Possible to hide holograms when not looking at them

### ISSUE THREAD

**Issue by srnyx** [filoghost/HolographicDisplays#524]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I was wondering if it was possible to make it so holograms are only shown when looking at them instead of all the time.
This would be a great alternative to being able to cull holograms.

### Holographic Displays version

2.4.9

### Additional information

If not, I would like this to be implemented into the API. Or maybe just an option in `config.yml` that's called `holograms-always-visible`.

**Comment by filoghost** [comment]
I think the client already does this. Doing it from the server would degrage performance.
