### ISSUE TITLE
Make line visible to only one player

### ISSUE THREAD

**Issue by Elikill58** [filoghost/HolographicDisplays#527]
### Description

Now, if we want to show a line to only one player, we should make lot of holograms. I propose to change the visibility for each line.

So:
- The visibility for the global hologram stay the same
- By default, all lines visible for everyone
- Can show/hide ONE line only of an hologram

This can be very useful when showing lot of data, specially like 7 lines for everyone and 2 lines for each players.

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
