### ISSUE TITLE
No-Tick-View-Distance - Hiding Holo grams 

### ISSUE THREAD

**Issue by Tabletopcheese** [filoghost/HolographicDisplays#528]
### Description

This has been suggested before, but I am also looking for something similar, but wanted to throw some ideas out there. 

I know Spiggot has a way to check if someone is looking at an entity, and now mojang is adding one as well. So I was curious if hiding them when not looked at or through walls would now be possible.

Alternatively, I know name plates hide when you enter sneak and are behind a wall. Curious to see if there is anyway to implement that.

Recap.

Hide when out of view, or have them "sneaking" so you can't see them through walls.

**Comment by filoghost** [comment]
Is it even possible to make armor stands "sneak"? Hiding them when behind walls server side is too performance intensive. There will be a configurable view distance in the future.

**Comment by Tabletopcheese** [comment]
Sounds good. I was just brain storming with the recent updates

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.

**Comment by filoghost** [comment]
This is now possible through configuration.
