### ISSUE TITLE
Deletes the config

### ISSUE THREAD

**Issue by Deeptanil** [filoghost/HolographicDisplays#531]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

When making changes in database,
If I make a mistake s the database just deletes everything!
It shouldn't so that and should just stay like that and send a error while reloading the plugin! 

### How to reproduce

1. Make a mistake in the database
2. Reload the plugin

### Server version

This server is running Paper version git-Paper-386 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e22a1a9)

### Holographic Displays version

2.4.9

### ProtocolLib version (if installed)

4.7.0

### Installed plugins that allow players to join with multiple Minecraft versions

Viaversion, Viabackward

**Comment by filoghost** [comment]
You shouldn't manually edit the database. Did you use a command to create a hologram after loading the plugin with the bad database?

**Comment by Deeptanil** [comment]
No just reloading the plugin with a bad or poorly formatted database removes the file data completely!

**Comment by filoghost** [comment]
Can you try with the v3 beta? It didn't happen when I tried.

**Comment by Deeptanil** [comment]
Cool, thanks for fixing it :D
