### ISSUE TITLE
Adventure Component

### ISSUE THREAD

**Issue by kamcio96** [filoghost/HolographicDisplays#532]
### Description

Hi,
Can you please add [Adventure](https://github.com/KyoriPowered/adventure) support for names and lines?

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
