### ISSUE TITLE
Creating and moving holograms on specific coordinates using command

### ISSUE THREAD

**Issue by MadPanCake** [filoghost/HolographicDisplays#535]
### Hello!

- My idea is basically, adding a **command to create hologram**, but instead of spawning it on a specific player, **spawning it on specific coordinates**. Also, a command to **move specific hologram to specific coordinates** would be amazing too. Both these commands should be executable by console, so we can use it with other plugins, which let us send commands on specific events, etc. or in Skript plugin.
- It would greatly improve our potential to use this plugin for dynamic cases, like spawning holograms live, in the middle of someone's gameplay, not only as pre-spawned holograms on spawn - that's super boring! I am actually surprised it's not possible yet, since the plugin is 7 years old! I appreciate the plugin, but you know, that's a wasted opportunity which many people could use in very creative ways.

### Example use cases:

- Adding holograms on PvP server to enhance the fun out of combat, by adding holograms like "Ouch!" "Hurts!", etc. popping out of players that are getting damage. It's not possible right now, because we can only create holograms on players, but this feature would require us to offset them a bit, otherwise the holograms will all be stacked inside of players and it'll break the effect.
- Making block-devices that can display information as holograms above themselves, instead of on chat
- Letting mobs talk, making NPC's dialogues above their heads

### Summary:
So, the command to create hologram would look like:
`/hd create-oc hologram_name X Y Z hologram_text`
The move hologram, command would look like:
`/hd move-oc hologram_name X Y Z`.
Only two commands to let us do amazing things with just one plugin!

**Comment by oskarkk** [comment]
I would really like this command, as right now I'm constantly editing database.yml and reloading the plugin to align my holograms to specific coords, or move them when I move the building they are in. A command to move a hologram by a specific number of blocks would also be nice. Something like `/hd move hologram-name 5 1 0` would move the hologram 5 blocks in X direction and 1 block upwards. Additionally some command could work like `/move` `/shift` etc. commands in WorldEdit - moving the hologram in the direction you are facing.

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
