### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by DrakMC** [filoghost/HolographicDisplays#536]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

This error will probably appear in the log when I change worlds. I'm not 100% sure.

### How to reproduce

1. Change world
2. The error is displayed in the log

### Server version

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

### ProtocolLib version (if installed)

ProtocolLib version 4.7.0

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards

### Additional information

https://pastebin.com/raw/r93y6YYg

**Comment by ElBananaa** [comment]
Hey, same issue on my end!
I did notice the issue only happens the first time you change world.

**Server version:** ```
This server is running Purpur version git-Purpur-"4ff0630" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4ff0630 on ver/1.17.1) - It is basically Purpur 1.17.1 b1428 with the log4j2 fix```

**Holographic Displays version:** `HolographicDisplays version 3.0.0-SNAPSHOT`

**ProtocolLib version:** `4.7.0`

**Installed plugins that allow players to join with multiple Minecraft versions:** `None`

**Full error:** https://pastebin.com/2nSYCwsC

**Comment by filoghost** [comment]
Should be fixed in the latest dev build: https://ci.codemc.io/job/filoghost/job/HolographicDisplays

**Comment by DrakMC** [comment]
Placeholders from PlaceholderAPI are not working in HolographicDisplays-3.0.0-SNAPSHOT.

**Comment by filoghost** [comment]
It uses a new format: {papi: placeholder}. E.g.: {papi: player_name}

**Comment by ElBananaa** [comment]
> Should be fixed in the latest dev build: https://ci.codemc.io/job/filoghost/job/HolographicDisplays

Awesome, thanks!
I did notice color codes '&` + `whatever the letter you use` don't work anymore if used in an animation file, is that normal?

**Comment by filoghost** [comment]
It was not, also fixed.
