### ISSUE TITLE
v3 entities

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [filoghost/HolographicDisplays#538]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Hey, I saw there is a beta of the 3.0 HD which is packet based. Should that improve performance and does it include entities in holos now such as Withers, Bees etc.?

Best regards

### Holographic Displays version

3 beta?

**Comment by filoghost** [comment]
Performance should be similar or better. Holograms are still holograms, they are not bees or withers.
