### ISSUE TITLE
HD reload breaks all holograms

### ISSUE THREAD

**Issue by JHarris12345** [filoghost/HolographicDisplays#539]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

When using /hd reload it comes up with this in console and despawns all the holos. I have to plugman reload to fix:

https://gyazo.com/5d528423106b0f2b6eb0640c3314e344

### How to reproduce

1. Load the lateat 3.0.0 snapshop
2. hd reload

### Server version

Airplane 1.17.1

### Holographic Displays version

3.0.0-SNAPSHOT

### ProtocolLib version (if installed)

4.7.0

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards, ViaRewind

**Comment by filoghost** [comment]
Did you manually edit the database? Please provide a copy of `database.yml`, I can't reproduce the error.
