### ISSUE TITLE
Add access to HolographicDisplays holograms through the API

### ISSUE THREAD

**Issue by mart-r** [filoghost/HolographicDisplays#542]
### Description

Right now the API does not allow access to the holograms created by HolographicDisplay in game (i.e the named holograms).

It would be great if there was a way to access these holograms through the API.

Use case is the following extension:
[pHD](https://www.spigotmc.org/resources/phd.77631/)
(It currently uses HD internals)

**Comment by filoghost** [comment]
It's available with `HolographicDisplays.getInternalHologramEditor().getHolograms()`.

**Comment by SlimeDog** [comment]
Thank you. Very much appreciated. Works great.
