### ISSUE TITLE
Math placeholderapi not working

### ISSUE THREAD

**Issue by Askarionn** [filoghost/HolographicDisplays#544]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

https://imgur.com/a/f6gl6aZ

test:
  lines:
  - Default hologram. Change it with &b/holo edit test
  - '%math_{bungee_lobby1}+{bungee_sz02}+{bungee_sz03}+{bungee_sz04}+{bungee_ss01}%'
  - '%bungee_lobby1%'
  - '%math_{bungee_lobby1}+{bungee_lobby1%%'
  - '%math_{bungee_lobby1}+{bungee_lobby1}%'
  position:
    world: world
    x: 13.74671894145164
    y: 20.2
    z: -140.592181791763

### How to reproduce

1. create hologram
2. use a math placeholder

### Server version

This server is running vanilla version git-NachoSpigot-"be07467" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ProtocolLib

**Comment by Askarionn** [comment]
the "1" in hologram is the placeholder %bungee_lobby1%, so bungee placeholders and any other placeholders are working, i also do /papi parse me %math_{bungee_lobby1}+{bungee_sz02}+{bungee_sz03}+{bungee_sz04}+{bungee_ss01}% and the placeholder it's working (i tested in other plugins such as DeluxeMenus). The problem is only when i use it on HolographicDisplays

**Comment by RubenArtz** [comment]
I think the latest version of HolographicDisplays is broken with HolographicExtension.
https://prnt.sc/23o7a4u
https://prnt.sc/23o7c93

**Comment by filoghost** [comment]
The problem is the nested placeholder that uses the same delimiters as Holographic Displays (`{` and `}`). I will need to either find a workaround or add escapes (`\` before each nested delimiter), but it's not a pretty solution.

**Comment by Thin-Troll** [comment]
what solution is there now for this problem?

**Comment by filoghost** [comment]
I just added a solution in the latest build, you have to use the escape character `\`. A correct example would be
`{papi: math_\{bungee_lobby1\}+\{bungee_lobby1\}}

**Comment by Thin-Troll** [comment]
after that, papi stopped working, everything except math
output format changed for all placeholders?

**Comment by filoghost** [comment]
@Thin-Troll Yes it changed for all placeholders from PlaceholderAPI.
