### ISSUE TITLE
Error while ticking holograms java.lang.NullPointerException

### ISSUE THREAD

**Issue by ebicep** [filoghost/HolographicDisplays#546]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Switched from v2 API to beta API

### How to reproduce

Switched from v2 API to beta API

### Server version

This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b185

### Additional information

https://pastebin.com/Sn7DPgjg
Maybe related, some of my holograms start to appear like this - 
![image](https://user-images.githubusercontent.com/34175525/147002787-490c1429-2d8e-447d-a50f-751d9155519f.png)

**Comment by andrewkm** [comment]
@filoghost we are experiencing the same issues on our 1.12.2 server.
https://pastebin.com/raw/cyQRJmLM

**Comment by filoghost** [comment]
Code to reproduce this issue please?

**Comment by andrewkm** [comment]
The issue is happening on our 1.12.2 server. We don't even use the API. We are on the latest version of Paper 1.12.2.

**Comment by ebicep** [comment]
> Code to reproduce this issue please? Possible a small snippet that I can copy paste.

```
Hologram hologram = HolographicDisplaysAPI.get(Warlords.getInstance()).createHologram(player.getLocation().add(0, 5, 0));
hologram.getLines().appendText("TEST");
```

The error only happens when (hologram.getLines().appendText("TEST");) is added

**Comment by filoghost** [comment]
Please try the latest dev build.

**Comment by ebicep** [comment]
> Please try the latest dev build.

Its fixed now
