### ISSUE TITLE
API Question 

### ISSUE THREAD

**Issue by silverfox0000** [filoghost/HolographicDisplays#547]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

HologramsAPI version `2.4.9` in README.md is not exsists on maven repo

### Holographic Displays version

2.4.9

**Comment by filoghost** [comment]
It does and it should work: https://repo.codemc.io/service/rest/repository/browse/maven-public/com/gmail/filoghost/holographicdisplays/holographicdisplays-api/2.4.9/

**Comment by silverfox0000** [comment]
Sorry for inactivity. In the README.md specifies `me.filoghost.holographicdisplays` but not `com.gmail.filoghost.holographicdisplays`
