### ISSUE TITLE
Holographic placeholder updater (Holographic Extension doesnt work)

### ISSUE THREAD

**Issue by ReformedHooper** [filoghost/HolographicDisplays#548]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Hi, what can I do to make the holograms update normally as before? Holographic extension used to take care of it, but now it doesn't work due to the update, is there such a possibility directly in holographic displays, or is it just not possible to update placeholders now?

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b186

**Comment by filoghost** [comment]
You no longer need that plugin for PlaceholderAPI, it's already built in v3. I will try to fix compatibility with v2 placeholders but it's not easy.

**Comment by SlimeDog** [comment]
With HD 2.4.9 we used `{he-%server_online_world_westeros%-1-value}`. What is the equivalent in HD 3.0.0?

**Comment by SlimeDog** [comment]
Found it: `{world: world}`
