### ISSUE TITLE
Color codes not working anymore (animations)

### ISSUE THREAD

**Issue by Jeppa** [filoghost/HolographicDisplays#549]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Colorcodes in animations in latest dev builds (e.g. #187) are not working anymore...
You are displayed as text ....

### How to reproduce

something like this in a animation.xml:

interval-seconds: 0.5
animation-frames:
- '&6HighScores : '
- ' &6HighScores :'

and a line like this in the scoreboard:
  - '{animation: animation.yml}'

### Server version

paper/spigot 1.18.1

### Holographic Displays version

build 187

**Comment by filoghost** [comment]
Thanks, fixed in the latest dev build.
