### ISSUE TITLE
Cannot use Placeholders of PlaceholderAPI

### ISSUE THREAD

**Issue by iFlyinq** [filoghost/HolographicDisplays#550]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [x] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

(I only saw an issue about the Math extension, but custom extensions don't seem to work) 
Use a placeholder from PlaceholderAPI in the `database.yml` file and it won't parse in-game.

```yml
test:
  lines:
  - '&7%luckperms_prefix%'
  position:
    world: world
    x: 0.5
    y: 62.8
    z: -15.5
 ```

You will see an unparsed placeholder
![image](https://user-images.githubusercontent.com/20583400/147480478-48826271-6e01-4002-88ea-b7d8bc2613fa.png)

### How to reproduce

Create a custom Placeholder via the PlaceholderAPI API

```Java
PlaceholderAPI.registerExpansion(new PlaceholderExpansion() {
            @Override
            public String getIdentifier() {
                return "astrax";
            }

            @Override
            public String getAuthor() {
                return "iFlyinq";
            }

            @Override
            public String getVersion() {
                return "1.0";
            }

            @Override
            public String onPlaceholderRequest(Player player, String params) {
                return "0";
            }
        });```

You can see this doesn't work, I don't think PlaceholderAPI is supported at all anymore? 

### Server version

PaperSpigot 1_8_R3 (MC: 1.8.8)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b187 & PlaceholderAPI  version 2.11.1

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards (Tested on 1.8 and server is running 1.8)

### Additional information

_No response_

**Comment by Jeppa** [comment]
Syntax has changed:
use PAPI like this now:
{papi:placeholder_name}

**Comment by iFlyinq** [comment]
> {papi:placeholder_name}

Thanks for this big brain action, haha. Maybe worth writing it down in the documentation @filoghost
