### ISSUE TITLE
API 3.0.0 beta->production

### ISSUE THREAD

**Issue by SlimeDog** [filoghost/HolographicDisplays#551]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Please finalize the 3.0.0 API so that plugins like pHD can update to support MC 1.18. Currently, the API is "temporarily beta".

### How to reproduce

Review code: Temporarily move API to "beta" package

### Server version

Spigot 1.18.1 or Paper 1.18.1

### Holographic Displays version

3.0.0

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion

**Comment by filoghost** [comment]
It will take a while, first the plugin needs to be out of beta. You can use the v2 API, it will not be removed anytime soon.
