### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by DasYannic** [filoghost/HolographicDisplays#553]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

It seems that the 3.0.0 is the 2.4.9 Version. I downloaded it now multiple times. Where can I find the right Version for 1.18.1?

### Holographic Displays version

HolographicDisplays 2.4.9 /3.0.0

**Comment by filoghost** [comment]
Maybe you have two versions of the JAR file in the plugins folder. The one on Bukkit Dev is correct.
