### ISSUE TITLE
High % of Server Tick

### ISSUE THREAD

**Issue by James-Cotterill** [filoghost/HolographicDisplays#554]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

The server TPS will suddenly drop randomly which we have identified on the timings report it is due to this task:

HolographicDisplays::Task: me.filoghost.holographicdisplays.plugin.tick.TickingTask (interval:1)

This will last for a couple minutes and then the TPS will increase again

### How to reproduce

Run server with latest 3.0 version

### Server version

This server is running Paper version git-Paper-402 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 1bc077b on ver/1.17.1) You are 2 version(s) behind Download the new version at: https://papermc.io/downloads Previous version: git-Paper-401 (MC: 1.17.1)

### Holographic Displays version

Holographic Displays v3.0.0-SNAPSHOT

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion

### Additional information

![image](https://user-images.githubusercontent.com/76694654/147708609-1f2602ff-8031-48ae-80f7-a6614de7bd41.png)

**Comment by kixmc** [comment]
Can confirm I'm also having this issue. Using 1.18.1

**Comment by filoghost** [comment]
I assume it's a slow placeholder from PlaceholderAPI, try removing them. Also in the latest dev builds there have been improvements where possible. A report with [spark](https://www.spigotmc.org/resources/spark.57242/) would be helpful, as the ticking task does many things.

**Comment by James-Cotterill** [comment]
Thank you for the reply. I have had to revert back to v2 currently and the performance issue has been resolved. I will migrate back to 3 shortly and will send a spark report when possible. Thanks

**Comment by filoghost** [comment]
Keep in mind a lot of performance cost is "hidden" in v2, because it uses real entities. So the actual work is done by Bukkit. I'll keep the discussion open in #533
