### ISSUE TITLE
I cannot edit a display with A capital letter.

### ISSUE THREAD

**Issue by Zepwon** [filoghost/HolographicDisplays#555]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I have a display that is named "Welcome" so I use /hd edit Welcome but it says cannot find a hologram named "welcome" even though I put a capital letter W at the start. I suspect this is a bug fixed by an update but I do not know how to import my old ones from the old version.

### Holographic Displays version

vision 2.1.10

**Comment by filoghost** [comment]
You're on an ancient version, please update.
