### ISSUE TITLE
Command interface suggestion

### ISSUE THREAD

**Issue by kmecpp** [filoghost/HolographicDisplays#558]
### Description

Instead of `/hd` showing the version and URL information, could `/hd` instead show a list of commands like `/hd help` currently does? Then add a `/hd info` and/or `/hd version` sub command to display that information?

It's much more common to get the command list/info than the plugin version/URL so it's shorter and more intuitive.

If you care about the your name being displayed prominently, perhaps include it in the command list title?

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
