### ISSUE TITLE
Deploy API snapshots of 3.0.0

### ISSUE THREAD

**Issue by NotMyFault** [filoghost/HolographicDisplays#559]
### Description

Heyo,

I'm kindly asking if it would be possible to deploy API snapshots like you did for prior releases in the 2.x line?

Thanks in advance!

**Comment by filoghost** [comment]
They are already there, but the groupId was changed (`com.gmail.filoghost...` -> `me.filoghost...`): https://repo.codemc.io/service/rest/repository/browse/maven-public/me/filoghost/holographicdisplays/holographicdisplays-api/

**Comment by NotMyFault** [comment]
Good to know, thanks for the clarification! I was going of the information in the readme.
