### ISSUE TITLE
console error (spigot 1.11.2

### ISSUE THREAD

**Issue by friishon** [filoghost/HolographicDisplays#56]
![holograma](https://cloud.githubusercontent.com/assets/19889173/23953039/c1cee77a-0993-11e7-826c-9dd209775761.png)
happends when player go to the server

**Comment by filoghost** [comment]
It looks like you're using an old version of ProtocolLib. The automatic check failed (now fixed: https://github.com/filoghost/HolographicDisplays/commit/f3c03a9c2482277d9572d9ab6236e49bfaa7863c)

**Comment by friishon** [comment]
thanks, i update protocolLib and fix it
