### ISSUE TITLE
Default Placeholders not working 1.18.1

### ISSUE THREAD

**Issue by iAmReprisal** [filoghost/HolographicDisplays#560]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

As the title says, the default placeholders for Holographic Displays are not working.

For example: Adding "[x]" returns "[x]" instead of the full block as the wiki says it should.
Photo example can be found [here](https://gyazo.com/bb65e3e1eabb2a30de86edef64f7519e).

Not sure if there's something wrong that I'm doing or the placeholders been changed and not updated on the wiki or if this is a bug.

Thanks in advance!

### How to reproduce

1. Run command "/hd create test [x]"
2. Done.

### Server version

This server is running Paper version git-Paper-136 (MC: 1.18.1)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

**Comment by filoghost** [comment]
Default placeholders have changed, they can be found in `custom-placeholders.yml`. You can re-add them if you wish.
