### ISSUE TITLE
Snapshot not parsing objective expansion for PlaceholdersAPI

### ISSUE THREAD

**Issue by mstaffa** [filoghost/HolographicDisplays#561]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

As the title states, the latest stable build of HolographicDisplays (version v3.0.0-SNAPSHOT) is not parsing the updated placeholders from the objectives expansion of PlaceholdersAPI.

The expected behavior is that the new syntax as outlined by [the Spigot page](https://www.spigotmc.org/resources/placeholderapi-scoreboard-objectives-placeholder.48236/) will show the player name that has the highest score of the given dummy objective "temp".

The the following syntax "%objective_entryposhigh_{temp}_{1}%" should yield my player name at the top spot. Instead, it shows only the literal text of the placeholder and displays no errors on the screen or console.

### How to reproduce

1. Create a dummy scoreboard objective with `/scoreboard objectives add temp dummy`
2. Set my objective to "5" with `/scoreboard players set PlayerName temp 5`
3. Create a display with `/hd create HoloName`
4. Set the first line to a placeholder to display top entry with `/hd setline HoloName 1 %objective_entryposhigh_{temp}_{1}%`

The display HoloName will have a first line that reads "%objective_entryposhigh_{temp}_{1}%" and does not display the data.

### Server version

CraftBukkit version 3397-Spigot-f4ff00f-f3828bb (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

### Installed plugins that allow players to join with multiple Minecraft versions

N/A

### Additional information

The below screenshot shows a holographic display with 2 lines. The first is the result of a placeholder from the objectives expansion for a simple objective score.

The second line is a placeholder from the same expansion that is the subject of this issue.
![exibit-a](https://user-images.githubusercontent.com/17129288/148655800-b45eb99e-edaf-4aa5-9d7b-39ad0822d781.png)

The first and second lines are successfully parsed by the PlaceholderAPI as shown below.
![exibit-b](https://user-images.githubusercontent.com/17129288/148655907-60998dc6-0ef1-4d9f-9c15-2d74ddc33ae1.png)
![exibit-c](https://user-images.githubusercontent.com/17129288/148655911-cf86d18c-9fc1-4988-9aff-fe670dfbda23.png)

**Comment by filoghost** [comment]
The syntax should be now `{papi: objective_entryposhigh_\{temp\}_\{1\}}`

Please try it, keep the escapes (`\`).

**Comment by NovaPixell** [comment]
> The syntax should be now `{papi: objective_entryposhigh_\{temp\}_\{1\}}`
> 
> Please try it, keep the escapes (`\`).

I used it with AjParkour and worked. I recommend you update the wiki (documentation) please :)

**Comment by filoghost** [comment]
I will update the wiki after uploading another beta version to Bukkit Dev. Thanks for the reminder
