### ISSUE TITLE
Placeholders not updating

### ISSUE THREAD

**Issue by Darkwolf202** [filoghost/HolographicDisplays#562]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Bungeecord environment with displays in the lobby for each server
The 'status' and player count aren't changing for one of 3 server info displays
The IP in the config for the server matches the bungeecord
in the config I am specifying the port as it is non-standard (one of the other servers are like this as well and they show correctly)

I have tried using the domain name and the resolved ip but didn't work
When I use the domain name I get a message in console 'unknown host address', though I can connect to the server using the name

not sure if I'm missing something somewhere

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

### Additional information

![image](https://user-images.githubusercontent.com/57463653/148671162-9643e371-4d8a-41e0-828d-3fcea0a16a2c.png)
![image](https://user-images.githubusercontent.com/57463653/148671166-2a3ecbb9-1d7c-460b-ac40-1df82cb7aeae.png)

**Comment by filoghost** [comment]
Are you using a SRV record on the DNS? This might explain why it says unknown host address. But I don't know why it's not working even by specifying the IP. Might be some firewall? While you can connect from your client, the server might not be able to.
