### ISSUE TITLE
Expose hologram visibility management

### ISSUE THREAD

**Issue by mart-r** [filoghost/HolographicDisplays#564]
### Description

In previous versions of the plugin, it was possible to change the visibility of the holograms using the visibility manager.
This is no longer the case.

Would be nice to have this opportunity again.
Right now, the pHD project is having to jump through quite a few hoops to obtain the same functionality.

PS:
If this the functionality is not going to be added, then that's fine, but please do give a response if possible.

**Comment by filoghost** [comment]
What do you mean? The old API is still there. In the new API it's called VisiblitySettings, e.g. `Hologram#getVisibilitySettings()`

**Comment by mart-r** [comment]
I suppose I didn't describe the issue in enough detail.

The pHD project was designed to add functionality to existing HolographicDisplays holograms.
It was designed to manage the visibility of these holograms.
Previously, this was rather trivial. Now it is not.

While there may be visibility management for "API holograms", there is not for "internal holograms" which we're trying to manage.

**Comment by filoghost** [comment]
Ok, I will re-implement it.

**Comment by filoghost** [comment]
Added in 045f363adbde1c914b916328e5a5480047c9e75b

**Comment by SlimeDog** [comment]
Nice. Thank you.

**Comment by mart-r** [comment]
It would seem that this functionality was removed again in https://github.com/filoghost/HolographicDisplays/commit/bf02837f9e57a4b81ee8750f80bbffc93075eafd

Is there any plans of reintroducing it or can I consider it forever gone?

**Comment by filoghost** [comment]
Sorry, the internal API has changed. Now HD uses the same API other plugins use. You can get an instance of the API used by HD itself with `HolographicDisplaysAPI.get(Bukkit.getPluginManager().getPlugin("HolographicDisplays"))`, or as before you can try accessing internal structures.

**Comment by SlimeDog** [comment]
Thanks.The API seems to have changed again at build 231 (in any event, it broke our usage, which was fine with build 226). Is it stable now?

**Comment by filoghost** [comment]
The official API is stable, so accessing HD's holograms through that will stay. You can access the VisibilitySettings, but it might be updated by HD for example when refreshing the hologram or reloading the plugin. The internal code is subject to changes so I can't say it's stable.

**Comment by SlimeDog** [comment]
Thanks.

**Comment by SlimeDog** [comment]
Is there an (estimated) release date for HD 3.0.0?

**Comment by filoghost** [comment]
I'm back working on it hopefully, might release a last beta the next few days. v3 might be in a 1-3 weeks.

**Comment by SlimeDog** [comment]
Thanks.
