### ISSUE TITLE
Registered placeholders are not displayed properly

### ISSUE THREAD

**Issue by PapiCapi** [filoghost/HolographicDisplays#566]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Registering placeholders using the API ( v2 ) does not seems to work anymore.

### How to reproduce

1) Create a plugin containing : 

```
HologramsAPI.registerPlaceholder(this, "%papicapi_placeholder%", 1, new PlaceholderReplacer() {

				@Override
				public String update() {
					return "Placeholders are working";
				}
				
			});
```

2) Create a hologram with this placeholder inside.
3) It displays only "%papicapi_placeholder%"

### Server version

This server is running Paper version git-Paper-130 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: eb98398) You are 20 version(s) behind Download the new version at: https://papermc.io/downloads Previous version: git-Paper-404 (MC: 1.17.1)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b191

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards

### Additional information

I saw other reports about the placeholders and i suppose their issues are related to mine but none was talking about the API.

**Comment by filoghost** [comment]
Unfortunately old placeholders did not have strict rules on formatting, so they were more like arbitrary replacements. The fix is to wrap with curly braces those who do not respect the traditional format, in your example you would need to use `{%papicapi_placeholder%}` to display it. The plugin will also print a warning when they are registered to inform server admins.
