### ISSUE TITLE
all i want is the string of a line, not a crafttextline

### ISSUE THREAD

**Issue by Jerfch** [filoghost/HolographicDisplays#567]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

when i try to use hologram.getLine it returns a hologram line but when you turn that into a string it says its a crafttextline... and when displaying that on a hologram it says CraftTextLine [text=<text>] when it should just  be the text, so not sure how to actually get the context of the line

### Holographic Displays version

2.4.9

**Comment by filoghost** [comment]
It's `TextLine#getText()`
