### ISSUE TITLE
Memory leak with TickingTask's cachedPlayersMap 

### ISSUE THREAD

**Issue by Kopo942** [filoghost/HolographicDisplays#568]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

https://github.com/filoghost/HolographicDisplays/blob/90e26af19bdc9c645e99c3a097fdfd1bed0fe571/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/tick/TickingTask.java#L26
The `cachedPlayerMap` in `TickingTask` seems to be leaking a lot of memory, especially on larger servers where there's a lot of players online concurrently. In the screenshot below, the map can be observed to be having about 3000 entries (over 500M of memory), even though there are less than 10 players online (this is on our hub server).

This seems to be caused by the `CachedPlayer` object holding a strong reference to `Player`, which is also the value's own key in the map. From WeakHashMap's javadoc:

> **Implementation note:** The value objects in a WeakHashMap are held by ordinary strong references. Thus care should be taken to ensure that value objects do not strongly refer to their own keys, either directly or indirectly, since that will prevent the keys from being discarded. 

### How to reproduce

1. Install Holographic Displays build 186 or newer
2. Let players join server and wait
3. Take a heap dump / attach debugger or analyzer, and observe map growing in size

### Server version

This server is running Purpur version git-Purpur-"66e5b11" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 66e5b11 on ver/1.17.1)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b189

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards, ViaRewind

### Additional information

![image](https://user-images.githubusercontent.com/13612979/149629341-9717b9d1-8ff1-42b5-9b0e-9da3f6524e20.png)

**Comment by Dymeth** [comment]
Confirm this issue

**Comment by filoghost** [comment]
Thank you very much, an oversight that can cause much trouble.

**Comment by filoghost** [comment]
Should be fixed by b89e6264bba11c42fbad056018fd4833cdd4cbd9. Can you please confirm? I don't think there are other places causing memory leaks, but I want to be sure.

**Comment by Kopo942** [comment]
Heap dump looked fine after about 10 hours of uptime, so the isssue seems to be fixed :) Thanks!

**Comment by filoghost** [comment]
Nice, thanks for checking.
