### ISSUE TITLE
How can i get all hologram in HolographicDisplays

### ISSUE THREAD

**Issue by ChrisRak** [filoghost/HolographicDisplays#569]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I cant get any hologram in .getHolograms(Bukkit.getPluginManager().getPlugin("HolographicDisplays"))
how can i get all holograms in HolographicDisplays

### Holographic Displays version

3.0.0 SnapShot

**Comment by filoghost** [comment]
Why are you trying to get the plugin's own holograms?

**Comment by ChrisRak** [comment]
there are something i need to do
