### ISSUE TITLE
crappy getStacktrace code is laggier than before.

### ISSUE THREAD

**Issue by jeinine** [filoghost/HolographicDisplays#57]
getStacktrace on getId should be replaced with a real method, the stack trace check, is running on more methods.

**Comment by gonzalociocca** [comment]
pd: there is any side effect removing the packet check? i couldn't see a difference at all. on 1.8.3

**Comment by filoghost** [comment]
Now the method is replaced with a proper API call for Java 9+. I will add an option to remove the packet check, as it's probably not needed for the most (unless you have holograms that teleport really frequently).
