### ISSUE TITLE
No holograms visible after respawn

### ISSUE THREAD

**Issue by ivenassenkamp** [filoghost/HolographicDisplays#572]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

In 3.0.0-SNAPSHOT, holograms are not displayed in the closer radius of the player's respawn point.
As soon as you move away from this point and back again, the holograms appear again

### How to reproduce

1. Create a Hologram near the spawn point
2. Die

### Server version

git-PaperSpigot-"4c7641d" (MC: 1.8.8)

### Holographic Displays version

3.0.0-SNAPSHOT-b193

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion 4.1.1

### Additional information

No error appears in the log

**Comment by filoghost** [comment]
Thanks, should be fixed in the latest dev build.
