### ISSUE TITLE
An error has occured

### ISSUE THREAD

**Issue by Leodk1** [filoghost/HolographicDisplays#573]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I have the right version 1.16.4 and all that but when i type the commands it just say "an internal error has occured"
I have tried everything but nothing works. Help!

### Holographic Displays version

Holographic Displays v1.1.1 [1.6.4]

**Comment by filoghost** [comment]
Can you please not use a version from 8 years ago? 😂
