### ISSUE TITLE
Maven Dependency on ReadMe

### ISSUE THREAD

**Issue by Obliviated** [filoghost/HolographicDisplays#574]
### Description

I am not sure correctness of maven dependency on readme
I tried this maven code (as shown on readme.md):

```
<dependency>
    <groupId>com.gmail.filoghost.holographicdisplays</groupId>
    <artifactId>holographicdisplays-api</artifactId>
    <version>2.4.9</version>
    <scope>provided</scope>
</dependency>
```

But this api doesn't introduces some methods (hologram.getLines() etc...).

I used this maven dependency its works. (and its not legacy api)
```
        <dependency>
            <groupId>me.filoghost.holographicdisplays</groupId>
            <artifactId>holographicdisplays-api</artifactId>
            <version>3.0.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by filoghost** [comment]
For now the new API is not complete. Use the v2 please, methods can be changed without warning.
