### ISSUE TITLE
Per player (permission based) hologram visibility

### ISSUE THREAD

**Issue by VladOliinyk** [filoghost/HolographicDisplays#575]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Hello! 

Is there a way to make some displays visible to the specific group of players via permissions? 
I'm not sure if it is even possible, but most of the plugins also look like "magic" so why not? 

I bet it could be a nice feature! 

Best regards :)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
