### ISSUE TITLE
Icon placeholder

### ISSUE THREAD

**Issue by JustRave** [filoghost/HolographicDisplays#576]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Heyo, I'm trying to add placeholders to icon in a hologram. The goal behind this is to have each player see their own skull in a hologram. Is this achievable, if yes, how?

### Holographic Displays version

2.4.9

**Comment by filoghost** [comment]
Sorry, this is no possible. Placeholders are only valid for text lines.
