### ISSUE TITLE
Error while ticking holograms java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by UsainSrht** [filoghost/HolographicDisplays#578]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Error spams in console.
```
[14:59:10 ERROR]: [HolographicDisplays] Error while ticking holograms
java.lang.NullPointerException: null
```
every 1 second

### How to reproduce

idk i just had some holograms

### Server version

Current: git-Purpur-1544 (MC: 1.18.1)* Previous: git-Purpur-1533 (MC: 1.18.1) * You are running the latest version

### Holographic Displays version

3.0.0 build 194

### Installed plugins that allow players to join with multiple Minecraft versions

nope

### Additional information

When I start the server, no error for few minutes and holograms are working. But after error spams in console every one second and no holograms working.

Protocollib build 4.8.0-build 540

**Comment by filoghost** [comment]
The error is not complete. If you just see those two lines, it is cut after being spammed for a while. In that case, you can find the full error the first times it starts spamming.

**Comment by Fireblaster819** [comment]
I am also have this issue
![image](https://user-images.githubusercontent.com/33851969/155827763-92307276-8574-469a-9f13-edfad22da248.png)

**Comment by filoghost** [comment]
This error is trimmed, I need the full error to find the reason. It's full printed the first few times it occurs, then it's trimmed.

**Comment by Fireblaster819** [comment]
> This error is trimmed, I need the full error to find the reason. It's full printed the first few times it occurs, then it's trimmed.

![image](https://user-images.githubusercontent.com/33851969/155892485-5bcd615e-82d6-4f34-b6f5-94a7cc5940b6.png)
Thats right after I join, and that's the full error

**Comment by filoghost** [comment]
You need to get a full `.log` file and check at the start. After a few times it gets trimmed. This "anti-spam" is reset on a server restart, so you need to check in the first part of the logs.

**Comment by TheekshanaA** [comment]
I've got the same issue on Purpur 1.19.2 while using Holographic Displays API with MythicDungeons from spigot.

**Comment by filoghost** [comment]
@TheekshanaA If you can provide a full log with the error stacktrace it would really help.
