### ISSUE TITLE
Holograpic display permission with luckperm

### ISSUE THREAD

**Issue by PtitCrissGaming** [filoghost/HolographicDisplays#579]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

On the HD website, they say that "holograms.*" will give all permissions to a group.. except that for me.. it doesnt work.. i managed to give permission to few command with "holographicdisplays.command.addline" or few other examples like this but not all the commands are available.. im only able to give like.. 2 or 3 command..

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

**Comment by filoghost** [comment]
The website is updated for v2. In v3, permissions have been changed, so replace "holograms" with "holographicdisplays". E.g.: `holographicdisplays.*`

**Comment by OtakuNL** [comment]
Please update the website. I have been searching for a solution for this for quiet a while.

**Comment by filoghost** [comment]
The website still has the documentation for the v2 version, I will update it.
