### ISSUE TITLE
Errors when used in combination with BKCommonLib

### ISSUE THREAD

**Issue by DynamicThijs** [filoghost/HolographicDisplays#58]
Hey, I'm getting errors on startup when using Holographic Displays and BKCommonLib together. Both of the plugins seem to work fine, but can you take a look at it please?
Thanks

https://pastebin.com/Dw6mdvTt

(PS: I've also contacted the BKCommonLib dev, but he said it's probably caused by this plugin)

**Comment by bergerkiller** [comment]
Reason for this error is your stack trace checking in your function. You blindly assume there to be a caller at index 2, but when Im invoking it there is no such stack trace element, and a NPE occurs. A bounds check would work. https://github.com/filoghost/HolographicDisplays/blob/master/HolographicDisplays/Plugin/com/gmail/filoghost/holographicdisplays/nms/v1_11_R1/EntityNMSArmorStand.java#L138

**Comment by filoghost** [comment]
I've also added a check for null filenames, thanks for finding the source of the problem @bergerkiller
