### ISSUE TITLE
Placeholder api not displaying placeholders in holograms

### ISSUE THREAD

**Issue by jokbon** [filoghost/HolographicDisplays#583]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Placeholder api not displaying placeholders in holograms.

https://pasteboard.co/0qKIJFKn9roD.png

### Holographic Displays version

3.0.0-SNAPSHOT-b197

**Comment by filoghost** [comment]
The format has changed, you need to use `{papi: bungee_factions}`
