### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by CrashHost** [filoghost/HolographicDisplays#584]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

![image](https://user-images.githubusercontent.com/89753571/153678915-a0d3e2c7-4fed-4029-bb86-e4a6468d0cfb.png)

### How to reproduce

Load Plugin 

### Server version

1.12.2

### Holographic Displays version

 HolographicDisplays version 2.4.9

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards

### Additional information

![image](https://user-images.githubusercontent.com/89753571/153679054-0962116a-2094-47e8-84c2-9becab5b0b59.png)

**Comment by filoghost** [comment]
Update to the beta v3 version please.
