### ISSUE TITLE
1.18.1 support plz 

### ISSUE THREAD

**Issue by PiglinPlayz** [filoghost/HolographicDisplays#585]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Im using papermc 1.18.1 and im getting an internal error saying that the plugin dose not work(not supported). If you could add support that would be amazing

### Holographic Displays version

Holographic Displays v3.0.0-SNAPSHOT

**Comment by Jeppa** [comment]
Here i have no issues using it on Paper 1.18.1 ...

**Comment by filoghost** [comment]
Please run `/version HolographicDisplays` to be sure you're using 3.0.0. Also show the error please.
