### ISSUE TITLE
"Unexpected error while modifying the channel pipeline"

### ISSUE THREAD

**Issue by TheosisOfficial** [filoghost/HolographicDisplays#586]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Unfortunately I'm not sure what caused this error because I was asleep at the time, but I saw it in my console when I woke up. Thought it might be worth sharing here because I've never seen it before and would have no idea how to reproduce it.

It can be found in the "Additional information" area.

### How to reproduce

N/A

### Server version

This server is running Paper version git-Paper-197 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: a8f2d67) You are 3 version(s) behind Download the new version at: https://papermc.io/downloads Previous version: git-Paper-175 (MC: 1.18.1)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

### Additional information

https://pastebin.com/dmcTbt0C

**Comment by Jeppa** [comment]
User Weltherrschaft (63aa4994-b190-47a3-abfe-a11dd70492ca) is known to be a hacker / server crasher...
Maybe he has found a new method or is searching for a new method to crash a server ;(

**Comment by TheosisOfficial** [comment]
> User Weltherrschaft (63aa4994-b190-47a3-abfe-a11dd70492ca) is known to be a hacker / server crasher... Maybe he has found a new method or is searching for a new method to crash a server ;(

Never heard of him lmao

**Comment by Jeppa** [comment]
Had issues with him on a server, and after a quick search in google i found his UUID in some more posts with server issues ;)

**Comment by filoghost** [comment]
Thanks for reporting, should be fixed in the latest build but not 100% sure. It could happen if the player was immediately kicked after joining.
