### ISSUE TITLE
[Server] WARN Location for hologram is null. Did you removed the world ?

### ISSUE THREAD

**Issue by PappoYT** [filoghost/HolographicDisplays#587]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I get this error in console:
`[Server] WARN Location for hologram is null. Did you removed the world ?`

but I cannot understand if it is related to HolographicDisplays.

### Holographic Displays version

HolographicDisplays-3.0.0-SNAPSHOT.jar

**Comment by ChezCoder** [comment]
It means you deleted the world that the hologram was in... just read the error.
