### ISSUE TITLE
1.18.2 unsupported

### ISSUE THREAD

**Issue by SlimeDog** [filoghost/HolographicDisplays#588]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

On server start-up, HD is disabled due to lack of support for 1.18.2

### How to reproduce

- Update Spigot (or Paper) to 1.18.2
- Start server
- Read the log

### Server version

This server is running CraftBukkit version 3445-Spigot-fb0dd5f-05a38da (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b202

**Comment by Tsoccerguy3** [comment]
somethings changed
https://hub.spigotmc.org/javadocs/bukkit/

**Comment by jonaas13** [comment]
Any eta to when the plugin will be updated to work with 1.18.2?

**Comment by filoghost** [comment]
Just released a new dev build with 1.18.2 support. Please test it so I can publish it to Bukkit.

**Comment by Saharo4eks** [comment]
> Just released a new dev build with 1.18.2 support. Please test it so I can publish it to Bukkit.

https://pastebin.com/Dvrs68MG

**Comment by vandon1** [comment]
build #203 on paper 1.18.2 can confirm not working with same message as above

[12:14:16] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v3.0.0-SNAPSHOT-b203
[12:14:16] [Server thread/INFO]: [HolographicDisplays] Encountered 1 error(s) on load:
 
1) Could not get the NMS entity ID generator. There is a small chance of entity ID conflicts, causing client-side issues on single entities.
------------[ Exception details ]------------
java.lang.ReflectiveOperationException: java.lang.ClassCastException: Cannot cast org.apache.logging.slf4j.Log4jLogger to java.util.concurrent.atomic.AtomicInteger

**Comment by filoghost** [comment]
I released another build. That bug is fixed.

**Comment by benfoster04** [comment]
I was just about to make a pull request about this haha

**Comment by jonaas13** [comment]
Seems to work. I had the same bug after the first build, it's fixed now. Thanks

**Comment by benfoster04** [comment]
Starts up ok, no exception. No surface issues when using commands. Holograms spawn as expected. I personally see that it's functional, if you want to do your own testing @filoghost let me know as I have the plugin running live.

**Comment by SlimeDog** [comment]
b204 looks good on Spigot 1.18.1 and Spigot 1.18.2. Holograms display, and work with my pHD. Thanks.
