### ISSUE TITLE
Hologram lines limited length

### ISSUE THREAD

**Issue by NeutralPlasma** [filoghost/HolographicDisplays#589]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I tried putting longer placeholders on holograms but they get cut off, example with HEX colours, they return already parsed colours. If check them with /papi parse me <placeholder>
they output just fine, but as soon as I put it on hologram it gets cut off, I had the same issue while trying to make HEX colour animations placeholders. Where I parse colours in my own plugin.

### How to reproduce

1. Create long hex coloured papi placeholder
2. Put placeholder on hologram

### Server version

This server is running Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

### Additional information

https://images.virtusdevelops.eu/XUwSY8.png

**Comment by filoghost** [comment]
The current limit is 300 characters, but the problem with HEX colors is that each letter is actually 15 (!) characters. I will raise the limit, if someone makes clients lag because of long holograms lines (visible characters, not colors) it will be their fault.

**Comment by filoghost** [comment]
I raised the limit to 5000. On my machine it doesn't cause issues, I checked just in case someone creates a line that long for error.
