### ISSUE TITLE
Change PlaceholderAPI format back to %placeholder%

### ISSUE THREAD

**Issue by cj89898** [filoghost/HolographicDisplays#591]
### Description

This format change to `{papi: placeholder}` will be confusing a TON of people (yes I know it's beta).

I personally think the best choice going forward for the next beta and release would be to leave it as `%placeholder%` or, if not, possibly `{placeholder}` to avoid mass confusion of how to use them.

Already got somebody coming into our discord asking about it.

**Comment by ajgeiss0702** [comment]
I've had at least 5 people in my discord in the past week or so asking about this. Please just use the standard PlaceholderAPI format.

**Comment by itsmemac** [comment]
The current format is more confusing and doesn't work sometimes
we had to redo all the placeholders in the server (there were literally 100+ placeholders)
It would be better to use old placeholder format or simplify it so its not complex

**Comment by HexedHero** [comment]
I've had people come to me complaining my plugin placeholders aren't working and it's due to people not knowing about this change and disliking it.

**Comment by xmorose** [comment]
I dont think this change to the new format makes any sense, should be reverted. HolographicDisplays is one of the essential plugins on ANY server nowadays, everyone uses it, randomly changing the placeholder syntax makes no sense at all to anyone.

**Comment by ConsoleLogLuke** [comment]
The old format is universally used in nearly every plugin that supports PlaceholderAPI, even used in PlaceholderAPI itself. By itself that should be sufficient reason to abandon the new format, however if you insist on keeping it the way it is now, it would still be better to include a config option for it so that server owners don't have to go around and change every single hologram that uses placeholders.

**Comment by ajgeiss0702** [comment]
> The old format is universally used in nearly every plugin that supports PlaceholderAPI, even used in PlaceholderAPI itself. By itself that should be sufficient reason to abandon the new format, however if you insist on keeping it the way it is now, it would still be better to include a config option for it so that server owners don't have to go around and change every single hologram that uses placeholders.

That’s a good idea. Having a config toggle would allow the few people who might like the new placeholders  to use them, but the majority of people can use the standard placeholderapi format

**Comment by cj89898** [comment]
I would like to still mention that I am still getting people every week asking about this and wondering why their placeholders don't work.

As far as I can see, it is also not documented on the current wiki for Holographic Displays.

**Comment by ajgeiss0702** [comment]
> I would like to mention that I am still getting people every week asking about this and wondering why their placeholders don't work.
> 
> As far as I can see, it is also not documented on the current wiki for Holographic Displays.

Same here. I’ve been recommending another hologram plugin in all of my guides because of this.

**Comment by filoghost** [comment]
This was added back.
