### ISSUE TITLE
Change gradle dependency from implementation to compileOnly

### ISSUE THREAD

**Issue by WallyTube** [filoghost/HolographicDisplays#593]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

As said on the README, it suggests to shade the dependency, but doing so gives the following error:
`java.lang.IllegalStateException: No API implementation set. Is Holographic Displays enabled?`

### How to reproduce

Add implementation dependency to project, functionality doesn't work.

### Server version

Spigot 1.18.1

### Holographic Displays version

holographicdisplays-api:2.4.9

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ProtocolSupport

**Comment by Kopo942** [comment]
Have you installed Holographic Displays as a plugin on the server? You're not supposed to shade the API since the plugin provides it.

**Comment by filoghost** [comment]
Changed the readme, thanks.
