### ISSUE TITLE
"An internal error has occured while attempting to perform this command"

### ISSUE THREAD

**Issue by JasonIsIronMan** [filoghost/HolographicDisplays#595]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I am trying to make a leaderboard for a pvp server. My plugins look like this:
![image](https://user-images.githubusercontent.com/66700682/158292166-c99fd019-b660-4c56-b3b2-8c35c8e806dd.png)
I am trying to do the command /hd create and no matter what I put in there it doesn't work. It just returns the error message in the title every time. I suspect it has something to do with it's dependencies because when I do /plugins it displays holographic displays in red. 
![image](https://user-images.githubusercontent.com/66700682/158298847-5d65d020-6b65-4b82-80ce-12818b5db460.png)

### Holographic Displays version

Holographic Displays 3.0.0-SNAPSHOT

**Comment by yzaimoglu** [comment]
Hey,
would you mind stating which server software & version you use. Could also help if you could provide the latest.log, so we can take a look at any errors thrown by the plugin.

**Comment by filoghost** [comment]
Please provide more details, such as server version. Also try updating. Will reopen if you reply.
