### ISSUE TITLE
Error while decoding player count from Bungeecord (NachoSpigot)

### ISSUE THREAD

**Issue by ghost** [filoghost/HolographicDisplays#599]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

![image](https://user-images.githubusercontent.com/43071315/159135464-2b5f8dcd-7e4e-4ea8-8508-cd003502d786.png)
i got this error

### How to reproduce

Idk because in my hologram there isn't a bungeecord counter 

### Server version

This server is running NachoSpigot version git-NachoSpigot-"9c02430" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT [20:22:14 INFO]: Author: filoghost

### Installed plugins that allow players to join with multiple Minecraft versions

Viaversion,Viabackwards and viarewind

### Additional information

Nomore

**Comment by filoghost** [comment]
This was fixed.
