### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KonoromiHimaries** [filoghost/HolographicDisplays#60]
logs
https://gist.github.com/KonoromiHimaries/2ce18f1fa993d744daea0d3cabeabf5d

timings
https://timings.aikar.co/?id=0c7d1f4a4fa44cb3aeccc1851897a588

torch
https://github.com/TorchSpigot/Torch
https://yivesmirror.com/downloads/torch

**Comment by MarkehMe** [comment]
Confirmed

**Comment by MarkehMe** [comment]
Works fine with cake though. Perhaps this type is not supported?

**Comment by MarkehMe** [comment]
Fixed in https://github.com/filoghost/HolographicDisplays/issues/60

**Comment by MarkehMe** [comment]
Fix available in v2.3.0:
https://github.com/redstone/HolographicDisplays/releases/tag/v2.3.0

**Comment by filoghost** [comment]
Original paste is deleted, but the bug is probably fixed: https://github.com/filoghost/HolographicDisplays/commit/49d6930389d5aa8eb7040926a92f9d6ebf3b9e36
