### ISSUE TITLE
Image Not Displaying

### ISSUE THREAD

**Issue by RocketManKian** [filoghost/HolographicDisplays#600]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Images not showing when importing them to a hologram with "/hd readimage <hologram> <ImageWithExtension> <width>" and instead just showing a bunch of "[x]" rather than the Square.

### How to reproduce

1. Update to latest dev build.
2. Create a hologram.
3. Add a PNG file to your HolographicDisplays folder.
4. Import the PNG in game using the readimage command.

### Server version

Current: git-Purpur-1596 (MC: 1.18.2)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b206

### Installed plugins that allow players to join with multiple Minecraft versions

N/A

### Additional information

![2022-03-27_16 27 36](https://user-images.githubusercontent.com/47107486/160288857-9e8ffc03-0ebd-4bf5-823d-dd7c2ab2d4c7.png)

**Comment by MrClean1337** [comment]
With the latest version it works, simply put this in the config

  solid-pixel: '█' #█ \u2588
  transparent-pixel: '&7 ⎹ ' #⎹ \u23B9

**Comment by filoghost** [comment]
I updated the default config, but if you already updated to v3 you need to do it manually as MrClean1337 shows. If you want to reset it just delete config.yml and reload the plugin.
