### ISSUE TITLE
Performance Fixes for Placeholder Update

### ISSUE THREAD

**Issue by linsaftw** [filoghost/HolographicDisplays#601]
### Description

When updating PlaceholderAPI too fast it lags the server when too many players are present.

1. Make the update time configurable to avoid lag.
2. Check distance between hologram and player before updating.

This would help reducing the lag with too many placeholders.

**Comment by filoghost** [comment]
Added the configurable refresh interval for PlaceholderAPI (default every 10 seconds now, instead of every tick), in the future I should make it configurable for each individual placeholder.

Please try the most recent dev build, performance should be better.
