### ISSUE TITLE
Issue with the 1.18.2 beta snapshot

### ISSUE THREAD

**Issue by RealDestroy** [filoghost/HolographicDisplays#605]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I want to implement the API into my plugin for a 1.18.2 plugin. I'm using 

        <repository>
            <id>codemc-repo</id>
            <url>https://repo.codemc.io/repository/maven-public/</url>
        </repository>

        <dependency>
            <groupId>me.filoghost.holographicdisplays</groupId>
            <artifactId>holographicdisplays-api</artifactId>
            <version>3.0.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

Which should work but now I'm stuck on what code to use to get the hologram to actually function

The old code is deprecated and what I came up with is this

https://paste.md-5.net/xuqefelofo.nginx

but i get an error when i do this

I also use the check in onEnable to make sure its loaded and so far thats not triggering

### Holographic Displays version

3.0.0-SNAPSHOT-b205

### Additional information

Code: https://paste.md-5.net/xuqefelofo.nginx

Error Log: https://paste.md-5.net/cujimuhuta.md

**Comment by filoghost** [comment]
Please use the old API for the moment, new one isn't finished nor documented. Compatibility will be maintained for a long time.
