### ISSUE TITLE
Holograms Disappearing on server reload

### ISSUE THREAD

**Issue by Gagafeee** [filoghost/HolographicDisplays#606]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

In 1.18.2 on the Paper server, the plugin works fine, but all the holograms disappear when I run reload (with /rl confirm) and they don't reappear when the reload is complete.

### How to reproduce

1. Setup paper server
2. Creates Holograms
3. Run /rl confirm
4. All the holograms disappear

### Server version

This server is running Paper version git-Paper-299 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 76ed156) You are running the latest version Previous version: git-Paper-271 (MC: 1.18.2)

### Holographic Displays version

3.0.0-SNAPSHOT-b206

### Additional information

I have on my server:
Multivers-Core
Vault,
ProtocolLib,
PluginConstructorAPI,
Placeholder

**Comment by Sapu98** [comment]
I have the same problem.

**Comment by lashiam** [comment]
I also have this issue

**Comment by filoghost** [comment]
Avoid reloading the plugin like that. You should have seen the warning from Spigot and the warning from Holographic Displays itself, use /hd reload.
