### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by HexedHero** [filoghost/HolographicDisplays#607]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

There is very poor performance since the v3 update where HD is always number 1 on timings and spark reports. Seems to be from the line tracker.
![](https://i.imgur.com/h9yjesk.png)

### How to reproduce

Use the plugin

### Server version

This server is running Paper version git-Paper-301 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: c449f6a)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b205

**Comment by filoghost** [comment]
Please keep the discussion about performance in #533. Also try updating since I've added optimizations in the latest builds.
