### ISSUE TITLE
1.18.2 - after "/holo create test" the hologram creates but doesn't displays

### ISSUE THREAD

**Issue by Axepecticle** [filoghost/HolographicDisplays#609]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

after typing "/holo create test1" the hologram creates but doesn't displays.
also, I've tried earlier versions, but they don't work at all.

### Holographic Displays version

3.0.0-snapshot-b205

**Comment by filoghost** [comment]
Sorry, I can't reproduce the issue. Try without other plugins and updating your Spigot version.
