### ISSUE TITLE
java.lang.IllegalStateException: Holographic Displays did not load properly (no API implementation was set)

### ISSUE THREAD

**Issue by ABravePanda** [filoghost/HolographicDisplays#610]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Im trying to hook into the new API however I keep getting this error. Right now im just implementing it via
` this.holographicDisplaysAPI = HolographicDisplaysAPI.get(plugin);`

I see this references the HolographicDisplaysAPIProverider however im not sure how to use it.

### Holographic Displays version

3.0.0-SNAPSHOT

**Comment by ABravePanda** [comment]
also i cant use the previous versions of the plugin as they dont support 1.18.2

**Comment by filoghost** [comment]
Don't look at the implementation. Just store a field of type `HolographicDisplaysAPI` with the API instance you get from that method.

After you get the error, are you able to use the /hd command and modify holograms normally?

**Comment by filoghost** [comment]
> Hi, I've got same problem as in topic, creating and editing hologram by /hd command works properly, I'm using 1.19.2 paper server, same thing happening on holographicdisplays 3.0.0 and 3.0.1 https://hastebin.com/ulecipiyet.sql - log

Can't access the link

**Comment by Varunda** [comment]
i also had this issue. it was caused by including the api in the shaded jar. by adding an exclusion i was able to get it to work fine

**Comment by filoghost** [comment]
@Varunda thanks, that explains the error. For everyone having this problem, make sure the Maven dependency has `<scope>provided</scope>`
