### ISSUE TITLE
Add 1.7 & Via-Version Support

### ISSUE THREAD

**Issue by ignMixha** [filoghost/HolographicDisplays#611]
### Description

This would be an amazing thing to do and add . So many server owners would like to see an updated version of holographic display working on 1.7 version and supporting 1.7 clients while support higher versions etc.... Via-Version & Via-Rewind do an amazing job but they do not fix the problems you get with holographic.

Example -
Running a 1.8.8 server jar and having all plugins made for 1.8 but then you add support for 1.7 players to join they will have problems seeing the holographic as its not supported at all. No plugins can fix this problem and this will benefit everyone who is running any kind of 1.8 server.

Suggestion -
Add 1.7 server & client support (if not client should do the trick)

**Comment by filoghost** [comment]
Sorry, it's up to the plugin allowing 1.7 players to correctly displaying holograms. Nothing I can do on my part. Besides, 1.7 is almost 10 years old.
