### ISSUE TITLE
addline limitations

### ISSUE THREAD

**Issue by zeya69** [filoghost/HolographicDisplays#612]
### Description

Hello, First off thank you for all your hard work! 

I am running a server with player shops that use a GUI, I would like the players name to automatically show up under the shop HD. I am able to get it work work just find, But the same button is used to also add time to the shop. could/is there a way to make it so a HD can only have a set number of lines. ie, my shops all have HD names D-1, D-2 and so on. Under the D-1 I would like their name to appear with they rent the shop. But it just keeps adding the name every time they renew the plot.  Also when I sell the plot back to the server it will only remove one name. I have attached some screenshots. Hope they help.

![2022-05-23_17 43 36](https://user-images.githubusercontent.com/1424798/169926387-c1505e50-0880-405e-b44c-1fa6180d1565.png)
![2022-05-23_17 43 50](https://user-images.githubusercontent.com/1424798/169926389-be5788e4-53c3-4078-9c65-99a7d31b9018.png)
![2022-05-23_17 44 02](https://user-images.githubusercontent.com/1424798/169926390-dd1a802f-6654-41f1-9a36-7e8eeb3802a9.png)

**Comment by zeya69** [comment]
Sorry put two of the same. 

![2022-05-23_17 43 28](https://user-images.githubusercontent.com/1424798/169926533-eeb838f3-a0d6-43b4-bad6-f2cc74e58036.png)

**Comment by filoghost** [comment]
That is an issue of the plugin adding those lines. If you're simply running commands automatically, always remove a line before adding a new one, and start with an empty line if you don't want to show anything (use {empty})
