### ISSUE TITLE
API placeholders seems to be not working

### ISSUE THREAD

**Issue by GrayR0ot** [filoghost/HolographicDisplays#613]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

When i create an hologram using placeholder API: 

/hd create test {papi: anarchyprison_mine_progress_7}

![image](https://user-images.githubusercontent.com/59394359/170026924-353bbfee-a430-4386-aed2-be01cc5add76.png)

Here is what I'm having

This is working fine.

But when I create the same hologram using API:

```hologram.appendTextLine("§6  › {papi: anarchyprison_mine_progress_" + mine.getId() + "}");```

Here is what I'm getting:

![image](https://user-images.githubusercontent.com/59394359/170027069-0b626afc-da43-45cc-b23b-076cc69d1e11.png)

### How to reproduce

...

### Server version

1.18.2 paper latest stable

### Holographic Displays version

3.0.0-SNAPSHOT-b205

**Comment by GrayR0ot** [comment]
I just solved the issue, there is an ```setAllowPlaceholders(boolean)``` function that is not visible in javadoc/wiki. But it is working

**Comment by filoghost** [comment]
Sorry, now it should be visible.
