### ISSUE TITLE
Laggy hologram spawn (menu animation)

### ISSUE THREAD

**Issue by ZeTioZ** [filoghost/HolographicDisplays#614]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

So, I made a menu that is navigable through key press with holograms. In previous version the menu was really fluid. Now, even though the code hasn't changed at all, the menu is now laggy. I tried with other entities as "holograms" and it does not lag with other entities.

### How to reproduce

1. Have a multiline hologram spawned
2. Clear the holograms lines
3. Add new lines
4. Do it multiple times, and it's not fluid like it should

### Server version

This server is running Paper version git-Paper-372 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: bed5cb2)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b218

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackward

**Comment by filoghost** [comment]
I might have solved this, please try the dev build 230 or higher: https://ci.codemc.io/job/filoghost/job/HolographicDisplays/
