### ISSUE TITLE
Holographic Image Issue

### ISSUE THREAD

**Issue by kattnap671** [filoghost/HolographicDisplays#618]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Hello! So, I have friend who owns a server. They created an image and posted using "/hd readimage". For some reason when It ried to do it. The image comes out wonky. I followed the instructions and format on the Wiki page. However, it still won't work. I also made sure that the plugin was updated to support 1.18.1. I am not sure what is going on or if I am still doing it wrong. I did give it a go for a week before asking for help. So, now I am in need of help. please and thanks. Lolz. So, Im trying to get to look like Image B, but it comes out looking like image A
![Image B](https://user-images.githubusercontent.com/107374556/173259222-1bdb3201-0bed-4e50-a5b3-c33f31cc5160.png)
![Image A](https://user-images.githubusercontent.com/107374556/173259230-4374c9d3-cffd-47f2-b7ac-3a164925953b.png)
.

### Holographic Displays version

Version: 3.0.0 - Mar 12, 2022 - Beta

**Comment by nkomarn** [comment]
Image B looks like it was made with maps inside of transparent item frames. If not that, it might also be done with a resource pack. Holographic images unfortunately cannot look like image B!

**Comment by filoghost** [comment]
The image needs to be way bigger to show details properly, and it's also limited to 16 colors right now. Maps with item frames are a better option than holograms.
