### ISSUE TITLE
High load from HD

### ISSUE THREAD

**Issue by DeriksonTM** [filoghost/HolographicDisplays#620]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Is it normal that the plugin loads the server so much? I ran a server test on my PC yesterday. And there were 5 players logging in to test it. For 3 hours HD in timings shows the result as in the screenshot below. Can this be due to the fact that my computer just can not cope with the load of the server and because of this your plugin gave the load? I have a total of 30 holograms in the spawn area, but they are far away from each other. What could be the problem?

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

### Additional information

![image](https://user-images.githubusercontent.com/92043849/174093136-d9530f71-5484-46c1-80b9-88ebace647a5.png)

**Comment by filoghost** [comment]
Please update to the latest dev build if you haven't. There will be also more optimizations, but are harder and will require more time.

**Comment by filoghost** [comment]
More optimizations added. Please continue the discussion in #533
