### ISSUE TITLE
How to translate this plugin? String file?

### ISSUE THREAD

**Issue by quswadress** [filoghost/HolographicDisplays#621]
### Description

Hello! 

After reading all the documentation, I found no way to translate the sentences in the plugin. As far as I understood, all the [s](https://github.com/filoghost/HolographicDisplays/blob/bf02837f9e57a4b81ee8750f80bbffc93075eafd/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/subs/CopyCommand.java#L38)[t](https://github.com/filoghost/HolographicDisplays/blob/bf02837f9e57a4b81ee8750f80bbffc93075eafd/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/subs/CopyCommand.java#L24)[r](https://github.com/filoghost/HolographicDisplays/blob/5bab55fb79e11623cfe06fa501e6dbaf9535dba2/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/format/DisplayFormat.java#L97)[i](https://github.com/filoghost/HolographicDisplays/blob/5bab55fb79e11623cfe06fa501e6dbaf9535dba2/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/format/DisplayFormat.java#L80)[n](https://github.com/filoghost/HolographicDisplays/blob/cb125157551ab90f97cdb142584aaa3c3edefb4d/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/HologramCommandManager.java#L179)[g](https://github.com/filoghost/HolographicDisplays/blob/cb125157551ab90f97cdb142584aaa3c3edefb4d/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/HologramCommandManager.java#L167)[s](https://github.com/filoghost/HolographicDisplays/blob/cb125157551ab90f97cdb142584aaa3c3edefb4d/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/HologramCommandManager.java#L162) [a](https://github.com/filoghost/HolographicDisplays/blob/cb125157551ab90f97cdb142584aaa3c3edefb4d/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/HologramCommandManager.java#L156)[r](https://github.com/filoghost/HolographicDisplays/blob/cb125157551ab90f97cdb142584aaa3c3edefb4d/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/HologramCommandManager.java#L150)[e](https://github.com/filoghost/HolographicDisplays/blob/cb125157551ab90f97cdb142584aaa3c3edefb4d/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/HologramCommandManager.java#L147) [h](https://github.com/filoghost/HolographicDisplays/blob/014f53dbcee6451450101bb7e275434fac467f0b/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/subs/TeleportCommand.java#L27)[a](https://github.com/filoghost/HolographicDisplays/blob/5bab55fb79e11623cfe06fa501e6dbaf9535dba2/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/HolographicDisplays.java#L57)[r](https://github.com/filoghost/HolographicDisplays/blob/5bab55fb79e11623cfe06fa501e6dbaf9535dba2/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/subs/CreateCommand.java#L31)[d](https://github.com/filoghost/HolographicDisplays/blob/5bab55fb79e11623cfe06fa501e6dbaf9535dba2/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/subs/CreateCommand.java#L77)[-](https://github.com/filoghost/HolographicDisplays/blob/014f53dbcee6451450101bb7e275434fac467f0b/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/subs/DeleteCommand.java#L25)[c](https://github.com/filoghost/HolographicDisplays/blob/014f53dbcee6451450101bb7e275434fac467f0b/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/subs/DeleteCommand.java#L37)[o](https://github.com/filoghost/HolographicDisplays/blob/5bab55fb79e11623cfe06fa501e6dbaf9535dba2/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/subs/AlignCommand.java#L27)[d](https://github.com/filoghost/HolographicDisplays/blob/5bab55fb79e11623cfe06fa501e6dbaf9535dba2/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/subs/AlignCommand.java#L59)[e](https://github.com/filoghost/HolographicDisplays/blob/014f53dbcee6451450101bb7e275434fac467f0b/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/subs/ReloadCommand.java#L24)[d](https://github.com/filoghost/HolographicDisplays/blob/014f53dbcee6451450101bb7e275434fac467f0b/plugin/src/main/java/me/filoghost/holographicdisplays/plugin/commands/subs/ReloadCommand.java#L35), and you can only change them by compiling the "translated" source code. 

Why is there no way to translate the plugin? Why not make a file with all sentences like in larger plugins like [FastAsyncWorldEdit](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/02a6bb9b27bc06ccc213292736d49c0e7e15f025/worldedit-core/src/main/resources/lang/strings.json), [LuckPerms](https://github.com/LuckPerms/LuckPerms/blob/34873914bd30ba00a861b61e8c68d8486afeabec/common/src/main/resources/luckperms_en.properties), [Negativity](https://github.com/Elikill58/Negativity/tree/master/src/assets/negativity), and others?

**Comment by filoghost** [comment]
Correct, there is no way to translate them. I feel like it's low priority, as this is an admin-only plugin.
