### ISSUE TITLE
Holographs disappearing

### ISSUE THREAD

**Issue by kingkaden123** [filoghost/HolographicDisplays#622]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I have a few holographic displays in different areas in my world, but if I teleport a player to a location, they all disappear. This problem fixes itself when I send the command /hd reload but I can't have a command constantly running that every time I teleport a player. How can I fix this?

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b205

**Comment by filoghost** [comment]
Try updating both Holographic Displays and Spigot. There was a Spigot bug related to chunks.
