### ISSUE TITLE
Visibility Manage is not working anymore since 1.19 support

### ISSUE THREAD

**Issue by Hyronymos1337** [filoghost/HolographicDisplays#624]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Latest development build broke the visibility manage on every version (only testet on 1.19 and 1.18.2). All Players see all Holograms.

### How to reproduce

1. create a holo
2. let them spawn only for certain users?

### Server version

git-Purpur-1668 (MC: 1.19)

### Holographic Displays version

3.0.0-SNAPSHOT-b224

**Comment by filoghost** [comment]
Please provide the code that you are using to spawn them only for certain users.

**Comment by Hyronymos1337** [comment]
the whole class: https://paste.twerion.net/bufivepuxu.typescript

the important part of the code: https://paste.twerion.net/akusikifoq.typescript

**Comment by Hyronymos1337** [comment]
any update on this? :(

**Comment by AerWyn81** [comment]
Hi, having the same issue here

**Comment by Rixafy** [comment]
Same issue here, when I apply `hologram.visibilityManager.isVisibleByDefault = false` it's still visible for everyone, I have translated holograms to 2 languages and both are visible and overlaying, so I need to turn off some language to deal with it.

**Comment by Wolf2323** [comment]
I can also confirm this issue

**Comment by XLordalX** [comment]
Same issue

**Comment by XLordalX** [comment]
Seems to be caused by `V2VisibilityManager`, inside the constructor there's an unused variable `visibilitySettings`. I was able to fix it by setting `this.v3VisibilitySettings = visibilitySettings;`. Not sure if that's intentional or not, can you confirm @filoghost ?

**Comment by filoghost** [comment]
I was testing with the new VisibilitySettings (the v3 API) which was working. The old one (v2 API) was not working properly because of a simple mistake. https://github.com/filoghost/HolographicDisplays/commit/4431605a3a9feed66abf45b61fa59dc377336921

**Comment by filoghost** [comment]
> Seems to be caused by `V2VisibilityManager`, inside the constructor there's an unused variable `visibilitySettings`. I was able to fix it by setting `this.v3VisibilitySettings = visibilitySettings;`. Not sure if that's intentional or not (saw you were refactoring visiblity settings not long ago), can you confirm @filoghost ?

Nice timing, we discovered it at the same time. That was the problem indeed.

**Comment by Hyronymos1337** [comment]
Its now fixed thanks, but now, newest dev build is causing much laggs.

https://spark.lucko.me/8r7m0jkGuv
