### ISSUE TITLE
Kyori Adventure integration

### ISSUE THREAD

**Issue by apatuka** [filoghost/HolographicDisplays#625]
### Description

Greetings, i don't know if this is the right place to request a feature

This is Kyori Adventure 
https://docs.adventure.kyori.net/index.html

It's an amazing library to create some cool [text effects](https://docs.adventure.kyori.net/minimessage/format.html#minimessage-format) like rainbox and gradient.

**Comment by filoghost** [comment]
It's cool, but I need to check if it works with holograms (text on holograms is different from text in the chat) and placeholders. Also low priority at the moment, but an easy way to do rainbows and gradients would be great.
