### ISSUE TITLE
configurable refresh rate for placeholders

### ISSUE THREAD

**Issue by KoltaiArmy** [filoghost/HolographicDisplays#626]
### Description

Hi!

Since your 3.0 version, its better just using holographic extension which is not updated since years. The server performance is so bad even with just a few placeholders, because the plugin refreshes them every single tick.

So we can say the newer versions of the plugin are unusable since months on servers where there are more than 3 active players, and where there are placeholders inside holograms. (they are almost in every hologram, that is like the point of holograms)
Please could you prioritize fixing the financial parts of the plugin?
Also, why would you change the working placeholders %...% to some weird crap "{papi: ...} which doesn't even supports more complicated placeholders, like math placeholders, where you are using other placeholders inside placeholders.

Thank you in advance for your answer.

![image](https://user-images.githubusercontent.com/36732586/174497782-10bb5803-d493-4288-88cd-bbf64804db49.png)

**Comment by filoghost** [comment]
I changed the format to unify them, Placeholder API is not the only plugin that can add placeholders, but I will consider using a simpler format (without "papi" prefix, or going back to this "special" format for PlaceholderAPI). It should support complicated placeholders though, can you post one that doesn't work?
