### ISSUE TITLE
Placeholders from other plugins are not working

### ISSUE THREAD

**Issue by thevalleyy** [filoghost/HolographicDisplays#627]
### Confirmation

- [x] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

![image](https://user-images.githubusercontent.com/74456686/175825954-13c6b7ab-3e3e-4f9a-9044-46fab9f12373.png)
As you can see here, I tried to create a hologram with the simple text `%luckperms_prefix%`, it does not work.
However, `papi bcparse me %luckperms_prefix%` is working. 
I observed this issue with other placeholders and I am sure this is a problem with hd.

### How to reproduce

1. Download a plugin with integrated placholders (hd integrated placeholders work)
2. Create a hologram with the placeholder

### Server version

Current: git-Purpur-1684 (MC: 1.19)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b225

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards, ViaRewind

**Comment by BlueFyreMatt** [comment]
Also experiencing this issue on HolographicDisplays build 226, I believe it to be a 1.19 issue with HolographicDisplays, no console error output to report

**Comment by filoghost** [comment]
The format has changed: {papi: your_placeholder_here} e.g. {papi: luckperms_prefix}
