### ISSUE TITLE
Can't get server status and online data through placeholder

### ISSUE THREAD

**Issue by zopn333** [filoghost/HolographicDisplays#628]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I'm hosting a bungeecord server network. I made a hologram to show server status and online data, but one of my server always show "Offline" and online number is 0, however players can enter that server.
I confirmed the server name and bungee settings, and there's no error on console. Can anybody give some suggestions to help me?

### Holographic Displays version

HolographicDisplays-3.0.0-SNAPSHOT#224

**Comment by filoghost** [comment]
I need to know the version of that server and the config.yml of Holographic Displays.
