### ISSUE TITLE
Holos aren't visible

### ISSUE THREAD

**Issue by Comthefox2486** [filoghost/HolographicDisplays#633]
### Confirmation

- [x] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Holo's aren't visible at all, yes I have tried stuff in the faq

### How to reproduce

1. use git-Paper-378 (MC: 1.18.2)
2. use latest dev build
3. add holo
4. ????

### Server version

This server is running Paper version git-Paper-378 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 4b27254)

### Holographic Displays version

3.0.0-SNAPSHOT-b205

### Installed plugins that allow players to join with multiple Minecraft versions

N/A

### Additional information

No console output, everything functions apart from seeing holos.
Plugins:

Plugins (7): Citizens, HolographicDisplays, SkBee, SkQuery, skRayFall, Skript, WorldEdit

**Comment by filoghost** [comment]
Please update both Spigot (1.18) and Holographic Displays to the latest development builds and try again.

Holographic Displays dev builds: https://ci.codemc.org/job/filoghost/job/HolographicDisplays
