### ISSUE TITLE
Protection Stone Hologram 

### ISSUE THREAD

**Issue by dronsyy** [filoghost/HolographicDisplays#634]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Hello, I need to make it so that when I put a private block (Protection Stone plugin), then a hologram with information about the private block (its size) and the owner is automatically created. How can this be implemented?

### Holographic Displays version

2.4.9

**Comment by PinkLolicorn** [comment]
https://github.com/filoghost/HolographicDisplays/wiki/Basic-tutorial

**Comment by filoghost** [comment]
You'll have to learn to use the API using the link PinkLolicorn provided, but I won't be able to guide you on how it can be implemented.
