### ISSUE TITLE
Pinger Error

### ISSUE THREAD

**Issue by DarkOakHD** [filoghost/HolographicDisplays#638]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Error happens when i restart one of the servers HolographicDisplays is pinging.

https://pastebin.com/13uD4tNm

### How to reproduce

1. Enable Pinger in config.yml
2. Create a hologram using "{online: skypvp}"
3. Restart the skypvp server

### Server version

TacoSpigot 1.8.8 and Paper 1.18

### Holographic Displays version

HolographicDisplays 3.0.0 Build #226

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaRewind, and ViaRewind Legacy Support

**Comment by filoghost** [comment]
Could you please try creating a fresh Spigot (not Paper/Taco) and using the pinger to check its status?

**Comment by DarkOakHD** [comment]
> Could you please try creating a fresh Spigot (not Paper/Taco) and using the pinger to check its status?

I get the same error.

**Comment by filoghost** [comment]
Seems a network error. Are you sure IP and port are correct, and that there are no firewall rules (e.g. iptables) to prevent the connection?
