### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by wasder** [filoghost/HolographicDisplays#64]
https://pastebin.com/xhVHiH5R

**Comment by didjee2** [comment]
I also have this error. It may be related with or ProtocolSupport or Citizens (I think Citizens).
Anyways, if you do not need ProtocolLib or personal Holograms, then simply remove it.

**Comment by filoghost** [comment]
Attempt to fix in commit https://github.com/filoghost/HolographicDisplays/commit/98e5827a8a0e33940454a7e6e1014a3d1c2baea4 

Please try this build:
[HolographicDisplays.zip](https://github.com/filoghost/HolographicDisplays/files/1193798/HolographicDisplays.zip)
