### ISSUE TITLE
TPS drop to 5, with papi holograms 

### ISSUE THREAD

**Issue by steveminecraft2** [filoghost/HolographicDisplays#640]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [x] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

When 20 people entered the game server I had 2 holograms after a total of 40 papi placholders (from other plugins), then suddenly TPS in minecraft were continuously at 5-6. Timings I checked and there were very large results for holographic displays. As I added the plugin on 1.19 holographic extension (not supported on 1.19) and changed the names from "{papi:placeholder}" to "%placeholder%" and restarted the server again. This juz the problem with TPS was gone, so it is a problem with placeholder holographic displays.
![image](https://user-images.githubusercontent.com/85501146/181209147-c0bbe694-68ef-41f0-8c22-43e007643781.png)

### How to reproduce

1. set 2 holograms, for 1 hologram there would be 20 placeholders with 10 lines of text, for example:
&c{papi:playtimenick1} &a: &c{papi:playtime1} and such with 10 lines and the second hologram the same only with a different placeholder.
2. preferably to enter the server and there are a lot of players (in my case it was 20) and there would be players at the holograms immediately. TPS then will be continuously at 5-6. 
When I tested with these plugins what I had on that server only in single player, such drops in TPS were not by maybe 0.5

### Server version

git-PufferfishPlus-7 (MC: 1.19)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b226

**Comment by filoghost** [comment]
Right now external placeholders are updated 20 times per second per player viewing them, so if a placeholder is not optimized (for example, if it reads from a file) it slows down the whole server. I will add a config option to specify the refresh interval (which will be every 1 second or more, by default).

In the future I will also try to profile the performance of individual placeholders and warn about slow ones.

**Comment by filoghost** [comment]
Please try the latest dev build, the refresh interval is configurable (default 10 seconds, instead of every tick).
