### ISSUE TITLE
Not working in 1.18.2

### ISSUE THREAD

**Issue by MaierAlin** [filoghost/HolographicDisplays#641]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [x] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

**So Im using the latest version of the plugin and i can t activate the plugin here is what console says:**

29.07 09:29:29 [Server] INFO [HolographicDisplays] Enabling HolographicDisplays v2.4.9
29.07 09:29:29 [Server] INFO ****************************************************************************
29.07 09:29:29 [Server] INFO Holographic Displays does not support this server version.
29.07 09:29:29 [Server] INFO Supported Spigot versions: from 1.8.3 to 1.16.4.
29.07 09:29:29 [Server] INFO This plugin has been disabled.
29.07 09:29:29 [Server] INFO ****************************************************************************

**And under is this error with update:**

29.07 09:29:35 [Server]  [HolographicDisplays] Unable to check for updates: unhandled exception.
29.07 09:29:35 [Server] INFO org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
29.07 09:29:35 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:29:35 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:29:35 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:29:35 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:176) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:29:35 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTask(CraftScheduler.java:145) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:29:35 [Server] INFO at com.gmail.filoghost.holographicdisplays.updater.UpdateChecker.lambda$run$1(UpdateChecker.java:63) ~[HolographicDisplays.jar:?]
29.07 09:29:35 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:29:35 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:29:35 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:29:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
29.07 09:29:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
29.07 09:29:35 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]

**And i tried execute „hd” command and this errors occurs:**

29.07 09:52:13 [Server] ERROR null
29.07 09:52:13 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'hd' in plugin HolographicDisplays v2.4.9 - plugin is disabled.
29.07 09:52:13 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
29.07 09:52:13 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
29.07 09:52:13 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:52:13 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
29.07 09:52:13 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2118) ~[?:?]
29.07 09:52:13 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2099) ~[?:?]
29.07 09:52:13 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
29.07 09:52:13 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
29.07 09:52:13 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
29.07 09:52:13 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:52:13 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
29.07 09:52:13 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
29.07 09:52:13 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:52:13 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:52:13 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
29.07 09:52:13 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:52:13 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:52:16 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
29.07 09:52:16 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:52:16 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:52:16 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-"df630a2"]
29.07 09:52:16 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]

### How to reproduce

idk

### Server version

This server is running Paper version git-Paper-"df630a2" (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2) Error obtaining version information

### Holographic Displays version

it says 2.4.9 but i installed the latest version

### Installed plugins that allow players to join with multiple Minecraft versions

no

**Comment by filoghost** [comment]
Update to the beta version, it supports newer MC versions.
