### ISSUE TITLE
Bolding Certain Text In Holograms Doesn’t Work

### ISSUE THREAD

**Issue by Aqenda** [filoghost/HolographicDisplays#643]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I am using Holographic Displays Version 3.0.0 and the holograms were working as normal. All of a sudden I open my server once more and I find all of my holograms that were bolded become unbolded. Some lines stayed bolded but the most were effected.

This may not be an issue about the hologram because my friend told me he sees it normally and I don’t see it normally. I don’t have enough evidence so when I try to ask more people if they see this same issue then I can deal with it later. I can notify you once I have screenshots and also if my other friends have the same issue as me.

### How to reproduce

Just started server 
Looked at an Existing Hologram that has parts of it unbolded.
Voila, there is the bug.

### Server version

CraftBukkit (Unknown Version)

### Holographic Displays version

HolographicDisplays Version 3.0.0-SNAPSHOT-b205 

### Installed plugins that allow players to join with multiple Minecraft versions

I am using ViaVersion, ViaRewind and ViaBackwards

**Comment by filoghost** [comment]
Please try without those 3 plugins, it might be one of them.
