### ISSUE TITLE
Holographic displays some causing server to not let anyone join, even after disabling plugin.

### ISSUE THREAD

**Issue by bakedpotato132** [filoghost/HolographicDisplays#645]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

When a player attempts to join the server, the console displays [this](https://pastebin.com/wR7vYUy7) error message, and then instantly kicks the player. I have no idea if the holographicdisplays error is related to the internal exception error, but i assume it somehow is. I also disabled holographicdispalys and you still cannot join. I tried replacing the scoreboard.dat file (i thought it may have something to do with it, as it says "scoreboardteam"), and it was still happening.

### How to reproduce

I have absolutely no idea. I didn't even restart the server. Someone was online, playing just fine, and then left. A couple minutes later i tried joining, and then got this error. Every attempt for someone to join afterwards have caused this same error. I did not run any commands, change any plugin files or do absolutely anything in between the player leaving and me joining. This just randomly started happening.

### Server version

This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b205

### Installed plugins that allow players to join with multiple Minecraft versions

VisVersion, ViaBackwards, ProtocolLib

### Additional information

https://pastebin.com/wR7vYUy7

**Comment by filoghost** [comment]
I see that something using the scoreboard is causing a disconnection, the error shown by Holographic Displays might be just because the player is instantly disconnected. Holographic Displays doesn't use the scoreboard at all. Try removing other plugins one by one.
