### ISSUE TITLE
(Startup error)

### ISSUE THREAD

**Issue by gerardsr14** [filoghost/HolographicDisplays#646]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

The plugin gives me an error, and install the latest version.

error: [TouchscreenHolograms] Task #141 for TouchscreenHolograms v1.4.4 generated an exception

### Holographic Displays version

TouchscreenHolograms v1.4.4

**Comment by gerardsr14** [comment]
How can it be solved?

**Comment by filoghost** [comment]
Please post the issue in https://github.com/filoghost/TouchscreenHolograms with the complete error. It might be because you're using an incompatible combination of Holographic Displays + Touchscreen Holograms. Update HD to the beta version if you haven't.
