### ISSUE TITLE
Holograms partially disappear

### ISSUE THREAD

**Issue by LuckyKuka** [filoghost/HolographicDisplays#648]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Holograms disappear partially after you go or teleport far away:
![normal](https://user-images.githubusercontent.com/77095872/188636428-29200410-50f9-4fba-9018-c68e9596acef.PNG)
And normal behavior is:
![bug-2](https://user-images.githubusercontent.com/77095872/188636449-14bc3f94-2de9-453c-8585-da8d1700df1e.PNG)
Help, what should I do?

### How to reproduce

1. use holographic displays version 3.0.0 snapshot b205
2. go far away or teleport (it happens more often when you teleport far away and come back)
3. tadam, hologram partially disappeared

### Server version

1.12.2-spigot-latest.jar

### Holographic Displays version

3.0.0-SNAPSHOT-b205

### Installed plugins that allow players to join with multiple Minecraft versions

i do not use them!! 😡😡

**Comment by LuckyKuka** [comment]
up

**Comment by LuckyKuka** [comment]
sorry for closing this as completed, it was accidentally, u know

**Comment by filoghost** [comment]
If I remember correctly, this was a Spigot bug. Please try updating to the latest version of 1.12.2, if that doesn't work please try on a newer version (1.13+) to check if the bug is specific to that version.
