### ISSUE TITLE
placeholder issues

### ISSUE THREAD

**Issue by jman13378** [filoghost/HolographicDisplays#649]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I have an issue with PAPI placeholders im trying to get a value from a placeholder and it just shows the placeholder itself      

placeholder %ajpk_stats_top_name_<number>_<area>%                                                     

### How to reproduce

create a hologram and add a placeholder

### Server version

This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2) You are running the latest version

### Holographic Displays version

3.0.0-SNAPSHOT-b250

### Installed plugins that allow players to join with multiple Minecraft versions

viaback and viaver

**Comment by hkkongou** [comment]
use the latest release uploaded 4 days ago
it works with 
{papi : <your placeholderapi placeholder }

**Comment by filoghost** [comment]
I've added the short format in the latest dev build.
