### ISSUE TITLE
No hologram shows.

### ISSUE THREAD

**Issue by Xsm0deus** [filoghost/HolographicDisplays#65]
`Plugin plugin = Main.getPlugin(Main.class);
                    Location hd = new Location(world, 527, 48, -954);
                    Hologram display = HologramsAPI.createHologram(plugin, hd);
                    TextLine t = display.appendTextLine("The core is big!");`

I wrote this up, no hologram shows, says local variable t isn't used, wiki doesn't explain anything.

**Comment by MarkehMe** [comment]
You didn't create a hologram, just the text line. Need to add the text line to the hologram.
