### ISSUE TITLE
RGB Gradient?

### ISSUE THREAD

**Issue by ApoCalispsiS** [filoghost/HolographicDisplays#650]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I have searched and searched but I can't find anywhere if it is possible to place Holograms with gradient colors. Is it not implemented in the plugin or did they forget to add the information?

If it is the case that this option is not added, they should add it as something new, because the holograms would really look incredible.

### Holographic Displays version

HolographicDisplays-3.0.0-SNAPSHOT

**Comment by filoghost** [comment]
Right now there is no way to automatically create a gradient. The feature is already requested in #430
