### ISSUE TITLE
Null pointer

### ISSUE THREAD

**Issue by voodootje0** [filoghost/HolographicDisplays#654]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

It seem seems like that we're getting random null pointers in console: https://haste.cgsys.net/isonaziponiwafob.css
This errors comes by every few seconds or so.

We don't have non existing worlds or anything in the database.

### How to reproduce

NPE should say enough

### Server version

This server is running CraftiSpigot version git-PaperSpigot-"0520d90" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Holographic Displays version

3.0.0

### Installed plugins that allow players to join with multiple Minecraft versions

Not related

**Comment by filoghost** [comment]
I've checked, that should not be possible normally, I suspect a plugin is invoking the API asynchronously. Can you provide a list of plugins that interact in any way with holograms?
