### ISSUE TITLE
Use image display, why the game does not display the image, but the Unicode code

### ISSUE THREAD

**Issue by itwxb** [filoghost/HolographicDisplays#656]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Use image display, why the game does not display the image, but the Unicode code

![OYMT2GYJAGG20`8D)LJ}~6A](https://user-images.githubusercontent.com/84020439/200470231-1e1ed2aa-d030-4ba1-b106-b88496e0e01a.png)

### How to reproduce

Upload an image into the folder /plugins/HolographicDisplays/, for example the [Bukkit logo](https://filoghost.me/data/holographic-displays/docs/bukkit.png).
/hd create example (example is the name of this hologram)
/hd readimage example bukkit.png 12 (bukkit.png is the name of the image in the plugin's folder, 12 is the width of the hologram. The symbols used to render the image are taken from your configuration).

### Server version

1.13.2

### Holographic Displays version

3.0

### Installed plugins that allow players to join with multiple Minecraft versions

have this

**Comment by adiantek** [comment]
same for me, paperspigot 1.19.2

**Comment by BrotherMole** [comment]
same here. Paper 1.18.2

**Comment by filoghost** [comment]
Fixed in the latest dev build, but you have to manually remove the configuration values to make the plugin re-generate them:
```yaml
image-rendering:
  solid-pixel: ...
  transparent-pixel: ...
```
Alternatively, update them with the new default values:
```yaml
image-rendering:
  solid-pixel: █
  transparent-pixel: '&7 ⎹ '
```
