### ISSUE TITLE
error holo with papi

### ISSUE THREAD

**Issue by quocn9042** [filoghost/HolographicDisplays#657]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

hi, why i installed the latest placeholderapi and protocollib but when using your holo to %% it doesn't work? (even with %% of other plugins)

### How to reproduce

idk help me

### Server version

Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Holographic Displays version

Holographicdisplays v3.0.0

### Additional information

![image](https://user-images.githubusercontent.com/116498360/200813446-c2b7559a-d394-4f69-aeb1-097096ad5e5e.png)

**Comment by Drakemlumme** [comment]
this happens to me too

**Comment by filoghost** [comment]
The format is {papi: placeholder}. Also you don't need ProtocolLib anymore.
