### ISSUE TITLE
HologramAPI usage issues

### ISSUE THREAD

**Issue by RedCarl** [filoghost/HolographicDisplays#658]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I developed a plug-in using HologramAPI, I want to update the text of a certain line, and I want to ask if there is a setLine method.
![image](https://user-images.githubusercontent.com/71010647/202672103-ec15b306-acef-4a9f-b54d-2c1e9b0b5c6e.png)
I use this method to display flickering, I want to eliminate this flickering

### Holographic Displays version

HolographicDisplays version 3.0.0

**Comment by filoghost** [comment]
You can set the text by using getLine() and casting to TextHologramLine

**Comment by RedCarl** [comment]
thanks, it's perfect
