### ISSUE TITLE
For noobs

### ISSUE THREAD

**Issue by Someone-NEW** [filoghost/HolographicDisplays#66]
So how the hex i can download any of this RAR or ZIP files that... ok ithis i know heh but i need jar file i realy dont want  download zips files i need a jar file and i dont know  how i will be happy when you can have here a link about latest one for download a JAR file thanks

**Comment by sgdc3** [comment]
wtf are you talking about? xD If you want the jar just download it from the HoloraphicDisplays bukkit page

**Comment by Someone-NEW** [comment]
Cool do you mean i dont know about that, dude here is updated to 1.12 omg yes i mean this version that i see is only here look around before you say some stupid but sorry dude i realy dont know how i can have a jar file from this files here i try with online converter from rar to jar but nothing work.

**Comment by sgdc3** [comment]
Latest version on the bukkit page works also on 1.12.

**Comment by Someone-NEW** [comment]
Thank you i know i am tested it but i download this and open old one with winrar and just transfer this files there and for now work but is this option not ideal i just want to know how use this files from github to jar files. somewhere i can see on wiki github links about latest dowload but not here :D

**Comment by ryantheleach** [comment]
@Someone-NEW To put it bluntly, you shouldn't.

The code on Github is experimental if you don't know programming, and have troubles telling between ready to release code, and not yet ready.

This project doesn't have releases tagged, so you wouldn't even be able to start to know when something was 100% ready without learning java.

Additionally, downloading the *source* and copying it into the compiled *jar binary* is not how you compile a project.

Depending on the exact project, programming language, or build tools used, it could be as easy as a single command, or a night fuelled by headaches trying to get someone elses project to compile.

This project is *not* set up with any build chain tools committed into the repository, so it will *not* be straight forward to compile this yourself.

**Comment by Someone-NEW** [comment]
Hmm ok i hope i am understand no i dont know programming just use this in java (dev) format will be great thank you
