### ISSUE TITLE
Getting the output from a command / mycmd-command as a holo

### ISSUE THREAD

**Issue by Zosum** [filoghost/HolographicDisplays#661]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

First of all hey everybody,

so I came up with this nice idea to create a holo  above a daily reward chest to show if this reward is claimable or not.
This uses the cooldown function that comes with the plugin my-command. I am able to show the minutes left of the cooldown but I think that we can all agree that nobody want's to see how many minutes a whole day has to offer...
So I created a workaround via my-command and a custom command "CooldownNormalekiste" which has a script inside that checks if the cooldown is equal to 0 or not.  And that works perfectly in chat but I want this output to be in the holo above the chest.

![image](https://user-images.githubusercontent.com/95768987/204095136-546cb348-805b-46ea-ab31-725ee1c49007.png)
![image](https://user-images.githubusercontent.com/95768987/204095227-82b4fc17-e9e1-4722-b610-da2eafd7ddc7.png)
![image](https://user-images.githubusercontent.com/95768987/204095308-c53edd8d-bbd9-464c-ac98-0aaf2850c67f.png)

### Holographic Displays version

Holographic Displays v.3.0.0 by filoghost

**Comment by filoghost** [comment]
You'd have to create an addon plugin that uses the API and registers a custom placeholder. That's the closest thing I can think of.
