### ISSUE TITLE
Pinger shows Offline for a long time after server restart or first join after a long time

### ISSUE THREAD

**Issue by Cyanoure** [filoghost/HolographicDisplays#662]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I've configured the pinger.
After server restart and when there are no players for a long time, the HD shows "Offline" for about 2 minutes.
I tried with version 3.0.0 and also with the lastest dev build, it works the same way.

### How to reproduce

1. Add 2 or more servers to the config.yml file, one of them should be down
2. Create holograms with the status of the servers
3. Start/Restart the server
4. It shows "Offline" for about 2 minutes

### Server version

This server is running Paper version git-Paper-300 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 54daefa)

### Holographic Displays version

HolographicDisplays version 3.0.1-SNAPSHOT-b239

### Installed plugins that allow players to join with multiple Minecraft versions

ViaBackwards, ViaVersion

### Additional information

Video: https://youtu.be/2LeZQHP_VtQ

**Comment by Cyanoure** [comment]
No logs, just the plugin's "enabled" message.

**Comment by filoghost** [comment]
Can you try again with debug enabled in Holographic Displays' config.yml? It should display the error. The fact that it works after 2 minutes suggests some kind of network issues. Is the target server reachable from where the holograms are displayed during these 2 minutes?

**Comment by Cyanoure** [comment]
Still no logs in that 2 minutes with debug enabled.
It could be one of my plugins, I'm trying to reproduce it, but currently it works on my recently created server. 😅

**Comment by Cyanoure** [comment]
I found the problem.
I have 3 servers in the config. One of my servers is down and it holds back the ping process for other servers too while HD waiting for that one server.
If I remove the offline server, the online servers appears as online instantly.
Can you make it run separated, asynchronously from each other?

**Comment by filoghost** [comment]
I would prefer to avoid creating multiple tasks on Bukkit/Spigot just to check online players. Could you lower the pinger timeout? Should be 2-3 seconds at most.

**Comment by filoghost** [comment]
Also if you need more control over these placeholders try the ones from PlaceholderAPI.
