### ISSUE TITLE
Holograms not getting removed while player is dead

### ISSUE THREAD

**Issue by Nishh** [filoghost/HolographicDisplays#663]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [x] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Removing holograms in the same tick with a player death causes holograms to be still visible for that player. (not removing holograms client side)

### How to reproduce

1. create a lot of holograms
2. delete some of them every tick randomly
3. kill yourself
4. some of the removed holograms still visible 

### Server version

1.18.2-R0.1-SNAPSHOT (387)

### Holographic Displays version

Holographic Displays v3.0.0

### Additional information

Tested with only 3 plugins; ProtocolLib, HolographicDisplays and my test plugin.
It seems HolographicDisplays does not send a remove packet if player is dead. (or died in last 1-2 ticks?)

Note: I have doImmediateRespawn true

**Comment by filoghost** [comment]
Thanks for reporting and reproducing it, fixed in https://github.com/filoghost/HolographicDisplays/commit/2fa71ad3e01449698f16af95bea3d580865e9945
