### ISSUE TITLE
Holograms not parsing PAPI Placeholders when creating though API

### ISSUE THREAD

**Issue by apatuka** [filoghost/HolographicDisplays#664]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

`
List<String> lines = Arrays.asList("§e§lNEXO de {papi : denizen_<server.flag[nexus.clan."+args[1]+".name]> }", "§b§l{papi : denizen_<server.flag[nexus.clan."+args[1]+".hp]> }");

Location location = new Location(plugin.getInstance().getServer().getWorld(args[2]), Double.parseDouble(args[3]), Double.parseDouble(args[4]), Double.parseDouble(args[5]));

Hologram hologram = api.createHologram(location);

for(String line : lines) {
	hologram.getLines().appendText(line);
}
`
Please check the picture:
![2022-12-07_00 09 21](https://user-images.githubusercontent.com/1668954/206078725-d0cc8529-98f1-43f1-82cd-5d02da1fd613.png)

### How to reproduce

Use the API

### Server version

Paper version git-Paper-298 (MC: 1.19.2) 

### Holographic Displays version

HolographicDisplays version 3.0.0

**Comment by winnipeg21** [comment]
Having this same issue on 1.19.3 using dev build #243 + purpur 1876.

**Comment by filoghost** [comment]
Placeholders are not enabled by default when using the API. You have to use [Hologram.setPlaceholderSetting](https://ci.codemc.io/job/filoghost/job/HolographicDisplays/javadoc/me/filoghost/holographicdisplays/api/hologram/Hologram.html#setPlaceholderSetting(me.filoghost.holographicdisplays.api.hologram.PlaceholderSetting))

**Comment by filoghost** [comment]
There is also another error, you have to escape the inner curly braces (like this: \{ and \}), otherwise the plugin will try to replace the innermost placeholder.
