### ISSUE TITLE
1.19.3 support

### ISSUE THREAD

**Issue by SlimeDog** [filoghost/HolographicDisplays#665]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Error on server start-up
```
[16:41:30] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v3.0.1-SNAPSHOT-b239
[16:41:30] [Server thread/INFO]: ^[[0;31;22m[HolographicDisplays] ^[[0;31;1mFatal error while enabling HolographicDisplays v3.0.1-SNAPSHOT-b239:
[16:41:30] [Server thread/INFO]:
[16:41:30] [Server thread/INFO]: Holographic Displays only supports Spigot from 1.8 to 1.18.2.
[16:41:30] [Server thread/INFO]: The plugin has been disabled.
```

### How to reproduce

- Update to Spigot 1.19.3-3616 or (later) Paper 1.19.3-321
- Start server
- Read log

### Server version

>version [16:47:19] [Server thread/INFO]: This server is running CraftBukkit version 3616-Spigot-d90018e-eecb4c0 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) [16:47:19] [Server thread/INFO]: You are running the latest version

> version[10:25:10 INFO]: This server is running Paper version git-Paper-321 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: d8cf30d)You are running the latest version

### Holographic Displays version

3.0.1-SNAPSHOT-b239

### Installed plugins that allow players to join with multiple Minecraft versions

n/a

### Additional information

Note that the error message lists support for 1.8 to 1.18.2, although 1.19.2 is supported.

**Comment by Budderman18** [comment]
furthermore, can you add a config option called something like "run-on-unsupported-versions?" That way we can at least try to run it on a new mc version, even if there's no garuntee it will work. Its very dumb that its setup this way

**Comment by Budderman18** [comment]
I submitted a pull request that does what i suggested

**Comment by Siddiet** [comment]
I'm having same issue. works fine with 1.19.2. Doesn't work with 1.19.3 spigot or paper. Says its only support 1.18 - 1.18.2 even though 1.19.2 worked fine. 3.0.0 and 3.0.1. Lotta holograms in my server need help asap

**Comment by Leahcimkrob** [comment]
I'm having same issue.

**Comment by filoghost** [comment]
Added dev build with support for 1.19.3.

**Comment by filoghost** [comment]
> furthermore, can you add a config option called something like "run-on-unsupported-versions?" That way we can at least try to run it on a new mc version, even if there's no garuntee it will work. Its very dumb that its setup this way

NMS versions don't work like that, you can't simply enable it and hope for the best. Code won't run, 100% of the time. More info: https://github.com/filoghost/HolographicDisplays/pull/666#issuecomment-1349883560

**Comment by SlimeDog** [comment]
HD build 243 looks good on Spigot 1.19.3, in our limited usage. Thanks.
