### ISSUE TITLE
Relative high performance usage since v3.0.0 (6% of server tick)

### ISSUE THREAD

**Issue by voodootje0** [filoghost/HolographicDisplays#667]
### Description

Since the 3.0.0 update our HD usages has been increased from ±0.8% tick usage to now 6% tick usage.

![image](https://user-images.githubusercontent.com/6852308/207351233-5acfb826-1231-43ef-87da-566cbefdc626.png)
As you can see in the above screenshot it's using almost 6% of server tick, I think this can be improved.

**Comment by filoghost** [comment]
Duplicate of #598. I've optimized it multiple times, I honestly don't know how to optimize it further.
