### ISSUE TITLE
Error: An internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by SammyKunimatsu** [filoghost/HolographicDisplays#668]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I'm trying to run the plugin commands, but I get this title error, in my console this appears:
`<html>
<body>

[23:13:51] [Server thread/INFO]: Sammy_KunOficial issued server command: /hd create teste
--
591 | [23:13:51] [Server thread/ERROR]: null
592 | org.bukkit.command.CommandException: Cannot execute command 'hd' in plugin HolographicDisplays v3.0.0 - plugin is disabled.
593 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
594 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
595 | at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:847) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
596 | at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
597 | at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:?]
598 | at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:306) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
599 | at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:290) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
600 | at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1957) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
601 | at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1919) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
602 | at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
603 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
604 | at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
605 | at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
606 | at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
607 | at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
608 | at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
609 | at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
610 | at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1133) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
611 | at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
612 | at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:115) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
613 | at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1109) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
614 | at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
615 | at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
616 | at java.lang.Thread.run(Unknown Source) ~[?:?]

</body>
</html>`

Link log: [https://mclo.gs/VysxNVi](logs)

how to solve? or if you can update the plugin

I'm using https://aternos.org/ as host

### How to reproduce

1. Register/Login Aternos
2. Create a server
3. Select Spigot/Bukkit software version 1.19.3(3630)
4. go to plugins tab
5. I used the plugins: "WorldEdit", "WorldGuard", "Vault", "TabList-bukkit-5.6.6", "SkinsRestorer", "ProtocolLib", "PlayerHeads-5.2.19-SNAPSHOT", "PixelPrinter", "nLogin ", "LuckPerms-Bukkit-5.4.40", "Geyser-Spigot", "GeyserSkinManager-Spigot", "EssentialsX-2.19.7", "EssentialsXGeoIP-2.19.7", "EssentialsXSpawn-2.19.7", "EnchantsSquared ", "Corpses". **And its 2 plugins: "HolographicDisplays", "TouchscreenHolograms".**
6. start the server
7. enter the server
8. use the command "/hd create test"
9. return error: "An internal error occurred while attempting to perform this command"

### Server version

This server is running CraftBukkit version 3630-Spigot-d90018e-ae8f5fc (MC: 1.19.3) (Implement API version 1.19.3-R0.1-SNAPSHOT)

### Holographic Displays version

HolographicDisplays version 3.0.0 Author: filoghost

### Installed plugins that allow players to join with multiple Minecraft versions

Geyser-Spigot: "makes bedrock also playable on the Java server"

**Comment by filoghost** [comment]
Update Holographic Displays to the latest dev build
