### ISSUE TITLE
Image Rendering not working

### ISSUE THREAD

**Issue by Dylan-Donders** [filoghost/HolographicDisplays#669]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I'm trying to load a simple icon as a hologram using the image rendering but its not working.
This Gyazo shows what the bukkit.png test symbol is showing right now.
https://gyazo.com/0c300feddba84c6b1178236fafb43139

### Holographic Displays version

3.0.1-SNAPSHOT-b243

**Comment by filoghost** [comment]
See here: https://github.com/filoghost/HolographicDisplays/issues/656#issuecomment-1336424044
