### ISSUE TITLE
Not available on 1.12

### ISSUE THREAD

**Issue by Mutim** [filoghost/HolographicDisplays#67]
I have read through the Issues, and although you guys say that it is available on 1.12, perhaps you have some dependency that you are unaware of, because I have a fresh server, with craftBukkit1.12 api, and get this error:
[13:30:31 INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.1.12
[13:30:31 INFO]:

******************************************************
     This version of HolographicDisplays can
     only work on these server versions:
     from 1.6.4 to 1.9.
     The plugin will be disabled.
******************************************************

I don't know what's wrong. I have correct version of ProtocolLib on here, but still, not working. If I am doing something wrong, can you please tell me what it is. =D thank you!

**Comment by sgdc3** [comment]
https://dev.bukkit.org/projects/holographic-displays/files
