### ISSUE TITLE
Add Action used on HologramLineClickEvent for Left/Right click

### ISSUE THREAD

**Issue by Stellrow** [filoghost/HolographicDisplays#671]
### Description

Recently experimented with this event and I notice the lack of having a right click on it, would be nice to either have the 
Action used on the hologram or a custom action for it

This can create a better experience for developers/server owners to have the ability to distinguish the clicks/decide different actions for each

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
