### ISSUE TITLE
Placeholder not working for me.

### ISSUE THREAD

**Issue by NEINtje** [filoghost/HolographicDisplays#673]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I was trying to make a leaderboard for lands using placeholders, but when I put in the placeholder %placeholder% it just showed the text instead of what the placeholder is supposed to show.

I tried putting in diffrent placeholders from diffrent plugins too but none worked.

### Holographic Displays version

HolographicDisplays version 3.0.0

### Additional information

![image](https://user-images.githubusercontent.com/91952040/212153643-6158da13-e937-43b9-bf19-f70aa672aa87.png)

**Comment by katekyy** [comment]
That's beacause they've changed the format to {papi: <placeholder>} (look here: #591) and it's not even documented that they changed it.

**Comment by filoghost** [comment]
Now this "short" format should be supported again.
