### ISSUE TITLE
Plugin doesn't work on 1.19

### ISSUE THREAD

**Issue by ctrsl** [filoghost/HolographicDisplays#676]
### Confirmation

- [x] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

As per the description on the plugin page:

"Compatible with Spigot 1.9 to 1.19"

But the plugin was disabled in console:

`[19:26:05 INFO]: [HolographicDisplays] Fatal error while enabling HolographicDisplays v3.0.0:
Holographic Displays only supports Spigot from 1.8 to 1.18.2.
The plugin has been disabled.`

Fix the description or add support :D

have a good one.

### How to reproduce

1. download the plugin
2.  put it in the plugins folder
3. restart the server
4. console produces error.

### Server version

paper 1.19.3

### Holographic Displays version

3.0.0

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards

### Additional information

n/a

**Comment by TheFaik** [comment]
Use version 3.0.1 - https://ci.codemc.io/job/filoghost/job/HolographicDisplays/
