### ISSUE TITLE
Add support for FancyDrops

### ISSUE THREAD

**Issue by Swirren** [filoghost/HolographicDisplays#677]
### Description

[The plugin FancyDrops](https://www.spigotmc.org/resources/steves-series-fancy-drops.68373/) changes the look of items to have somewhat realistic physics. Attempting to use a hologram to display an item for some kind of gallery with these changed items, however, simply does not work.

**Comment by filoghost** [comment]
The items used by that plugin are a different kind of item, it equips them on armor stands, HD uses dropped items. It can't work.
