### ISSUE TITLE
player head

### ISSUE THREAD

**Issue by ikikaidesu** [filoghost/HolographicDisplays#679]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

How can I display either a photo of the player's head or the player's head in the hologram?

### Holographic Displays version

2.4.8

**Comment by filoghost** [comment]
Sorry, this is not possible.
