### ISSUE TITLE
Holograms are higher in 1.9+ versions than in 1.8

### ISSUE THREAD

**Issue by checkium** [filoghost/HolographicDisplays#68]
In 1.9+ versions, holographic displays uses a normal armorstand, while in 1.8 uses a baby/small one, that makes the holograms have weird locations.

**Comment by sgdc3** [comment]
Are you using a plugin like protocolsupport or viaversion?

**Comment by checkium** [comment]
Yes

**Comment by sgdc3** [comment]
which one?

**Comment by checkium** [comment]
The two

**Comment by sgdc3** [comment]
in viaversion there is an option to fic the hologram position
