### ISSUE TITLE
Placeholder not working! Want to make a leaderboard :(

### ISSUE THREAD

**Issue by JaberOnFire** [filoghost/HolographicDisplays#680]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I know you said that you only use certain placeholders for the plugin but how is that possible if I want to add things like scoreboard objectives.. For example I want to make a scoreboard for the most kills so I would do this:

`/hd addLine Leaderboard1 &f%objective_scorepos_{Total_Kills}_{1}% %objective_entrypos_{Total_Kills}_{1}% `

But it uses the Scoreboard Objective API and it wont show.. How else am I meant to make a leaderboard??

### Holographic Displays version

Holographic Version 3.0.0

**Comment by filoghost** [comment]
Please try on the latest version, I'm assuming that placeholder is from PlaceholderAPI.
