### ISSUE TITLE
Placeholders don't work. None of the holograms I made with placeholders worked

### ISSUE THREAD

**Issue by jhqwqmc** [filoghost/HolographicDisplays#681]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Nothing wrong was reported

### How to reproduce

Use placeholders in the hologram to reproduce the problem

### Server version

git-KeYi-main/1.19.3-4595b8e (MC: 1.19.3)

### Holographic Displays version

HolographicDisplays version 3.0.2-SNAPSHOT-b246

### Additional information

![image](https://user-images.githubusercontent.com/113768629/217122267-34edea2f-aec7-419e-a2e2-c936014f0359.png)
![image](https://user-images.githubusercontent.com/113768629/217122275-5187f4cf-0f89-458a-9af6-a45d1bef6e50.png)
Plugins on the server
![image](https://user-images.githubusercontent.com/113768629/217122379-7edd4d60-e5f1-4b84-9436-7aebe8c5687b.png)
Display {papi: and placeholder variable name}

**Comment by xanderforrest** [comment]
Have you figured this out? Having the same. Have read every doc page, can't find anything at all pointing out how to use PlaceholderAPI placeholders.

**Comment by filoghost** [comment]
Are you sure those placeholders exist? Please try with something that should be enabled by default, like `%player_gamemode%`. Does that work?
