### ISSUE TITLE
holographic item

### ISSUE THREAD

**Issue by ikikaidesu** [filoghost/HolographicDisplays#682]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

How can I make a player's head in a hologram?

### Holographic Displays version

2.4.8

**Comment by Symmettry** [comment]
add this line:

ICON: player head

for the nbt you can do

ICON: player head {SkullOwner:"name"}

**Comment by filoghost** [comment]
> How can I make sure that each player sees his own head?

That is not possible, as placeholders only exist in text lines, i.e. there is nothing equivalent to {player} but for items.
