### ISSUE TITLE
How to update placeholders each second

### ISSUE THREAD

**Issue by azzztec** [filoghost/HolographicDisplays#684]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

In recent version there were {slow} {medium}, how to use that in 3.0.0+ ?

### Holographic Displays version

3.0.1

**Comment by filoghost** [comment]
Those placeholders were from an external plugin, not HD. In v3 each placeholder manages its own refresh rate. If you're using PlaceholderAPI there's a config option to change the refresh rate globally (not yet individually).
