### ISSUE TITLE
Background of the hologram extends further than text.

### ISSUE THREAD

**Issue by iPrahh** [filoghost/HolographicDisplays#686]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Hello, my holograms are looking like that to repent and before it did not happen. The hologram text is a papi placeholder of an itemsadder font image
![2023-03-06_05 47 03](https://user-images.githubusercontent.com/127075391/223022572-e8035f39-4aa8-4bdf-a04c-36a5c43668d2.png)

### How to reproduce

Nothing, all holograms looks like that to repent and I tried to reload and restart and nothing

### Server version

PaperSpigo 1.18.2 build 388

### Holographic Displays version

HolographicDisplays v3.0.1

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion

**Comment by filoghost** [comment]
Holographic Displays cannot control how holograms are rendered. This probably happens because the font image is very wide compared to normal characters, and cannot be fixed.
