### ISSUE TITLE
flicker in editing the hologram lines

### ISSUE THREAD

**Issue by itsmu1x** [filoghost/HolographicDisplays#689]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

flicker in editing the hologram lines..

### Holographic Displays version

HolographicDisplays version 3.0.1

### Additional information

Hello!
i'm trying to make an top list for the most players have played my server.
i'm the developer for the server and i made this hologram with this syntax `Updates in: 00:00` (changes every second)
![Screenshot-20230313041554-334x52](https://user-images.githubusercontent.com/94903742/224593247-74605af0-1c17-4074-bb97-1fbbdeb70b85.png)
and thats a cooldown tells the players when the top online list will refresh
but the issue is the `/hd setline` command is making something like flicker the hologram everysecond will flick like disappear and reappear again
so how can i avoid that?
and another thing.. how can i catch if the player clicks for an hologram? thanks.

**Comment by filoghost** [comment]
You shouldn't use /hd setline to constantly update the line, use a custom placeholder. For detecting the click, see https://ci.codemc.io/job/filoghost/job/HolographicDisplays/javadoc/me/filoghost/holographicdisplays/api/hologram/line/ClickableHologramLine.html (all hologram lines are clickable lines)
