### ISSUE TITLE
Folia Support

### ISSUE THREAD

**Issue by pontaoski** [filoghost/HolographicDisplays#692]
### Description

With the advent of https://github.com/PaperMC/Folia/ (multithreaded MC server), plugins that want to run on Folia need to explicitly declare compatibility with it. 

I have a downstream plugin (https://github.com/BlueMoonVineyard/BallCore/) that I am in the process of porting to Folia, and I'd be interested in making sure that this plugin works fine with it.

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm no longer adding new features or enhancements to the plugin.
