### ISSUE TITLE
Minecraft 1.12.2: The Invisible Problem of Holograms.

### ISSUE THREAD

**Issue by TeQTabanca** [filoghost/HolographicDisplays#696]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

If I move after adding the holgram, the hologram will never appear, even if I restart the server.

### How to reproduce

1. Add any holograms
2. Move a little after adding

### Server version

CraftBukkit git-Spigot-79a30d7-f4830a1 (MC: 1.12.2)

### Holographic Displays version

3.0.3-SNAPSHOT-b256

### Additional information

[[Video](https://www.dropbox.com/s/vekeo47hgwi8nsn/HolographicDisplays-hologram_invisible-issue.mp4?dl=0)]

**Comment by filoghost** [comment]
Do you have view distance set to 1 by chance? Sorry for not answering before, didn't really have any clue.
