### ISSUE TITLE
API RGB color don't work

### ISSUE THREAD

**Issue by VanyaNexus** [filoghost/HolographicDisplays#697]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

If you set the RGB color on the hologram using the API, then there is no color. If you create a hologram through commands, then the colors are perfectly displayed

### How to reproduce

hologram.getLines().appendText("&#AAF310test text")

### Server version

Paper 1.19.2

### Holographic Displays version

3.0.2

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards

**Comment by Black-Hole** [comment]
It should work you use "§" instead of "&".

**Comment by VanyaNexus** [comment]
No, I create test holo with two lines: "&#FF6662TEST TEXT 1" and "§#FF6662TEST TEXT 2" and it doesn't work, here is a screenshot
![image](https://github.com/filoghost/HolographicDisplays/assets/60396560/c466001d-4bcb-4b7e-8950-c24db361333f)

**Comment by filoghost** [comment]
If you use the API, colors are not automatically added. You'll have to do that manually, as if you were using `player.sendMessage(...)`, using the ChatColor class (for example `ChatColor.GREEN + "Hello world"`)
