### ISSUE TITLE
I can't use the HologramAPI.

### ISSUE THREAD

**Issue by Sandro642** [filoghost/HolographicDisplays#698]
### Confirmation

- [x] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

![image](https://github.com/filoghost/HolographicDisplays/assets/84270313/dd751416-55c7-497c-a70e-5876719835e4)

### How to reproduce

Player player = event.getPlayer();
        Location location = player.getLocation();
        Vector direction = location.getDirection();
        direction.multiply(2);
        location.add(direction).add(0, 2, 0);

        HolographicDisplaysAPI api = HolographicDisplaysAPI.get(plugin);
        Hologram hologram = api.createHologram(plugin, location);

### Server version

Spigot 1.16.5

### Holographic Displays version

holographicdisplays-api-3.0.0-20221009.143217-57

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackward, ViaRewind

**Comment by filoghost** [comment]
Well, as your IDE says, that method doesn't exist (to be more specific, it exists but it has different parameters).
