### ISSUE TITLE
1.19.4 Holo Bug

### ISSUE THREAD

**Issue by Warrior1321** [filoghost/HolographicDisplays#700]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I am getting this weird issue, my server is made in 1.17.1 but anyone on im guessing 1.19.3+ get this bug where the {player} placeholder shows 'You' and the first line is not centerd

### How to reproduce

1. Setup a hologram in a version like 1.17.1
2. be on 1.19.2+ I believe
3. Use the {player} placeholder in the hologram

### Server version

This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1) You are running the latest version

### Holographic Displays version

HolographicDisplays Version 3.0.0

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaRewind, ViaBackWards

### Additional information

I use all 3 of the multiple minecraft versions, but i dont allow people to join in 1.8-1.15 its 1.16+ only with serevr having been made in 1.17.1

My Database.yml for hologram https://paste.md-5.net/loqejucobu.bash

**Comment by Warrior1321** [comment]
Just an update for this, its due to the {player} or {displayname} placeholder as when i remove that the hologram goes to how it should be all centred

**Comment by filoghost** [comment]
If the plugin works without ViaVersion, ViaRewind and ViaBackWards I cannot do anything to fix it. Seems like a visual bug caused by one of those.
