### ISSUE TITLE
1.20 Support

### ISSUE THREAD

**Issue by yomanwasup** [filoghost/HolographicDisplays#703]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Spigot, Paper, and Bukkit have released their dev builds for plugins for MC version 1.20

### How to reproduce

If you update your server to the latest version (1.20), the plugin doesn't work

### Server version

1.20

### Holographic Displays version

3.0.2

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards, Worldgaurd

**Comment by BiigToastie** [comment]
have the same problem, Please Update to 1.20
only Plugin what is still not Updated is HD

**Comment by BiigToastie** [comment]
can not please someone just take over this Project and give HD a "New Future ?"
PLease

**Comment by BiigToastie** [comment]
Oh wait, i just see the lates update here:
https://ci.codemc.io/job/filoghost/job/HolographicDisplays/lastBuild/
