### ISSUE TITLE
VERSION

### ISSUE THREAD

**Issue by MHNE** [filoghost/HolographicDisplays#705]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

this not bug just give my idea for version number,,

why not use same with minecraft version?
1.20 or 1.20.1

### How to reproduce

-

### Server version

1.20

### Holographic Displays version

3.0.0

**Comment by filoghost** [comment]
You don't always release new versions perfectly in sync with Spigot. Also they're different software, so different versions.
