### ISSUE TITLE
Error related to appendItem

### ISSUE THREAD

**Issue by YerassylB** [filoghost/HolographicDisplays#706]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

The error appears when I try to change the location of a hologram created using the API.

### How to reproduce

I'm creating a hologram with 2 lines of text and 1 head with skin, I'm trying to make an animation for the case. I will attach a screenshot below.

### Server version

1.16.5

### Holographic Displays version

3.0.3

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards

### Additional information

Error:
![image](https://github.com/filoghost/HolographicDisplays/assets/101264771/72799fc3-51bb-4b46-88e0-8ae5219aa7e4)

What happens when there's a skin head in a hologram:
![image](https://github.com/filoghost/HolographicDisplays/assets/101264771/94d93fc2-a8e1-4b95-af0a-95d80ebd8bb9)
![image](https://github.com/filoghost/HolographicDisplays/assets/101264771/6943e840-ee38-4f90-9fe0-e1288638b8cc)

Intentionally removed his head in holograms:
![image](https://github.com/filoghost/HolographicDisplays/assets/101264771/831d05c8-a2e7-4f32-8aaf-ff4e0251cbdb)

**Comment by filoghost** [comment]
It seems that you're adding a custom head without a profile somehow, the resulting NBT is invalid and it breaks Bukkit's API.
