### ISSUE TITLE
Error fatal al iniciar puglin

### ISSUE THREAD

**Issue by Totolas** [filoghost/HolographicDisplays#709]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Al intentar meter el puglin a la consola me dice error fatal solucionar inmediato. ayuda

### How to reproduce

[HolographicDisplays] Fatal error while enabling the plugin. Check previous logs for more information.

### Server version

version 1.20.12

### Holographic Displays version

HolographicDisplays version 3.0.2

### Additional information

![Captura de pantalla 2023-08-02 164825](https://github.com/filoghost/HolographicDisplays/assets/141208612/6ec63fbf-f872-4b20-bbef-e9eca64b5d69)

**Comment by filoghost** [comment]
This problem is caused by an addon of Holographic Displays, not Holographic Displays itself. I also see a warning about multiple versions of Holographic Displays in the plugins folder.
