### ISSUE TITLE
Not working with Minecraft 1.20.2

### ISSUE THREAD

**Issue by Jeppa** [filoghost/HolographicDisplays#711]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

When starting an 1.20.2 server the plugin shuts down...

`
[10:26:29] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v3.0.3
[10:26:29] [Server thread/INFO]: [HolographicDisplays] Fatal error while enabling HolographicDisplays v3.0.3:

Holographic Displays only supports Spigot from 1.8 to 1.20.
The plugin has been disabled.
`

### How to reproduce

Just start the server...

### Server version

This server is running Paper version git-Paper-201 (MC: 1.20.2)  (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 298c478)

### Holographic Displays version

HolographicDisplays-3.0.3_B258

**Comment by koroxo** [comment]
i have the same problem in 1.20.2 with this Plugin, please fix it or update it to new version

**Comment by andrewkm** [comment]
Same thing on this end @filoghost - doesn't seem to function via 1.20.2

**Comment by filoghost** [comment]
I pushed a development build, please test it and I will release on Bukkit in a few days https://ci.codemc.io/job/filoghost/job/HolographicDisplays/

**Comment by andrewkm** [comment]
> I pushed a development build, please test it and I will release on Bukkit in a few days https://ci.codemc.io/job/filoghost/job/HolographicDisplays/

Works, thank you! :)
