### ISSUE TITLE
Moving players from one server to another causes "unexpected error while modifying the channel pipeline."

### ISSUE THREAD

**Issue by andrewkm** [filoghost/HolographicDisplays#712]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

https://pastebin.com/raw/KjWcG1Yy

### How to reproduce

Move players from one server to another via bungeecord command.

### Server version

Paper 1.20.1 Build 196

### Holographic Displays version

Latest compiled against https://github.com/filoghost/HolographicDisplays/commit/5d22e2754df028b3efd01a7fcc1e5bb94dc186a4

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards

### Additional information

Some players who are being moved may or may not be on the 1.20.2 client.
Unsure if problem is related.

**Comment by filoghost** [comment]
In the latest version on Bukkit I attempted to fix this. Please give it a try.

**Comment by andrewkm** [comment]
This look good now, thanks! :)

**Comment by andrewkm** [comment]
@filoghost I spoke far too soon, this is still an issue:
https://pastebin.com/raw/ymgBsYDx

I simply didn't extensively test it with my reply 3 weeks ago.

Currently on https://github.com/filoghost/HolographicDisplays/commit/6f343c5fc0c7e5da634a6e4565cc9c4bce62e7dc for the record.

**Comment by andrewkm** [comment]
There seems to be no packet_handler in the pipeline.
https://github.com/filoghost/HolographicDisplays/blob/master/nms/v1_20_r3/src/main/java/me/filoghost/holographicdisplays/nms/v1_20_R3/VersionNMSManager.java#L83

**Comment by andrewkm** [comment]
Migrated to DecentHolograms
