### ISSUE TITLE
An internal error occured after trying to use any command, and none of my holograms show up.

### ISSUE THREAD

**Issue by OMGGamiing11** [filoghost/HolographicDisplays#714]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [x] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

When i try to use a commend it just tells me an internal error has occurred and none of my pre-existing holograms work.

### How to reproduce

1. Install the plugin, development build or not.
2.Try to run a command

### Server version

Paper 1.20.2

### Holographic Displays version

3.0.4-SNAPSHOT-b259

### Installed plugins that allow players to join with multiple Minecraft versions

none

### Additional information

![2023-10-08_16 22 48](https://github.com/filoghost/HolographicDisplays/assets/147346500/f14ca1a1-ba9b-4533-a26c-1f2b99db470a)

**Comment by filoghost** [comment]
I need a log of the error that shows up in the console please.
