### ISSUE TITLE
[BUG] Not compatable with Minecraft 1.20.4 Paper or Spigot

### ISSUE THREAD

**Issue by Tsoccerguy3** [filoghost/HolographicDisplays#715]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Plugin needs a update for 1.20.4

### How to reproduce

Update Minecraft to Paper or Spigot 1.20.4

### Server version

Paper 1.20.4 b119

### Holographic Displays version

HolographicDisplays-3.0.4-SNAPSHOT

**Comment by Leahcimkrob** [comment]
Log:
[17:43:02] [Server thread/INFO]: [HolographicDisplays] Fatal error while enabling HolographicDisplays v3.0.4-SNAPSHOT-b259:

Holographic Displays only supports Spigot from 1.8 to 1.20.
The plugin has been disabled.

**Comment by Tsoccerguy3** [comment]
Fixed in PR here https://github.com/filoghost/HolographicDisplays/pull/716

**Comment by Tsoccerguy3** [comment]
[plugins.zip](https://github.com/filoghost/HolographicDisplays/files/13940472/plugins.zip)

Here is my 1.20.4 HoloDisplay and HoloPlots for Plotsquare. Uzip for use

**Comment by filoghost** [comment]
PR merged.
