### ISSUE TITLE
HolographicDisplaysAPI create hologram, hex colors in text.

### ISSUE THREAD

**Issue by teddhun** [filoghost/HolographicDisplays#718]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I created Hologram with the API, but somehow I can't colorize the text with hex.

I tried multiple variations..

- #hexcode
- &#hecode
- <#hexcode>

[Result](https://i.imgur.com/ETKKM6t.png)

### How to reproduce

1. Create a hologram via API.
2. AppendText with hex color

### Server version

Spigot 1.18.2

### Holographic Displays version

HolographicDisplaysAPI 3.0.0

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion

### Additional information

`Hologram hologram = instance.getHolographicDisplaysAPI().createHologram(location);
hologram.getVisibilitySettings().setGlobalVisibility(VisibilitySettings.Visibility.HIDDEN);
hologram.getVisibilitySettings().setIndividualVisibility(player, VisibilitySettings.Visibility.VISIBLE);

hologram.getLines().appendText("&#3b5fC7Camo");`

**Comment by filoghost** [comment]
This is expected, just like normal colors, you don't write "&c" (for example) in the text when using the API. In the same way, you can't use &#0123456, but you have to create the HEX color yourself.

See the class `me.filoghost.fcommons.Colors` for an example implementation.
