### ISSUE TITLE
The plugin does not load in 1.20.4.

### ISSUE THREAD

**Issue by BurkenDev** [filoghost/HolographicDisplays#719]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Loading plugin in paper 1.20.4 does not work.

[20:50:50] [Server thread/INFO]: [HolographicDisplays] Fatal error while enabling HolographicDisplays v3.0.4-SNAPSHOT-b259:

Holographic Displays only supports Spigot from 1.8 to 1.20.
The plugin has been disabled.

[20:50:50] [Server thread/INFO]: [HolographicDisplays] Fatal error while enabling the plugin. Check previous logs for more information.

### How to reproduce

See above

### Server version

Paper 1.20.4

### Holographic Displays version

HolographicDisplays v3.0.4-SNAPSHOT-b259

**Comment by andrewkm** [comment]
It's been updated here:
https://github.com/rayanbzd/HolographicDisplays

**Comment by DeEthria** [comment]
@filoghost @andrewkm 

Would it be possible to compile the plugin for us? We don't know how to do this and we need this urgently

**Comment by Remigio07** [comment]
@DeEthria, it is not recommended to ask for compiled JARs so here's how you can do it yourself. 😃 To compile the plugin you need to install Maven first. You can download the latest release [here](https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip). Once done you have to unzip it, copy the extracted folder's path and add it to your `Path` environment variable. To open the dialog press Windows key and search for "Edit the system environment variables", press "Environment Variables..." and locate the Path variable under "System variables", then press "Edit":
![](https://i.imgur.com/3s6is7s.png)

Press "New" and paste the path of the folder you installed Maven it but add `\bin` to it. Press OK, OK again and proceed.

Now you have to download the [repository](https://github.com/rayanbzd/HolographicDisplays)'s source .zip (using the green "<> Code" button, then "Download ZIP"), unzip it, open a cmd into the extracted folder and type `mvn package` in the terminal. This will start the process which may take several minutes (took 12 for me) depending on connection speed.

Once completed you will two .jars inside the `plugin\target` folder just generated. You want the 900 KB one.
Let me know if you encounter difficulties. 🙂

**Comment by DeEthria** [comment]
Yes, thanks, I'll try it

**Comment by Tsoccerguy3** [comment]
https://github.com/filoghost/HolographicDisplays/issues/715

**Comment by filoghost** [comment]
Merged @rayanbzd's PR.
