### ISSUE TITLE
1.8 holos do not use setMarker(true)

### ISSUE THREAD

**Issue by MedicOP** [filoghost/HolographicDisplays#72]
Even though the setMarker method does not exist in 1.8 yet, you can still do it by calling EntityArmorStand.n(true)

Using setMarker will remove the annoying hitboxes caused by the invisible armor stands.

**Comment by MedicOP** [comment]
Offsets.ARMOR_STAND_ALONE needs to be changed to -0.26

**Comment by filoghost** [comment]
Better late than never https://github.com/filoghost/HolographicDisplays/commit/a67866ff4241caf4d56f16ffb91e2d833968cbd9
