### ISSUE TITLE
Farmlimiter support needed

### ISSUE THREAD

**Issue by A1yshia** [filoghost/HolographicDisplays#721]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I can't find anywhere else to write this, but im struggling to make your plugin work how I want. Please help. 

### How to reproduce

.

### Server version

paper 1.20.2

### Holographic Displays version

.

### Installed plugins that allow players to join with multiple Minecraft versions

Viaversion Viabackwards

### Additional information

I am struggling to get the farm limiter to check each entity individually, and need help. its grouping plugins despite me setting rules per entity. 

Config is currently as followed: 

# Plugin created by filoghost. All rights reserved.
# Redistribution of this product is forbidden.
# 
# Online documentation: https://filoghost.me/docs/farm-limiter

# How often to check mob farms in seconds.
check-interval: 180

broadcast:
  enable: true
  message: '&6[FarmLimiter]&e Removed {amount} entities.'
  # How many entities should be removed at minimum to broadcast the message.
  minimum: 1
  # Enable to require the permission "farmlimiter.receive-broadcast" to see the message.
  require-permission: false

rules:
# A global rule active on all the worlds, for groups of 50+ entities.
# A rule to avoid friendly mob farms, limit the mobs amount to 25.
- entities: villager, wandering trader
  worlds: all
  distance: 5
  max-amount: 25

- entities: cow
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: pig
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: sheep
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: chicken
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: frog, tadpole
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: mushroom cow
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: axolotl
  worlds: all
  distance: 5
  max-amount: 50

- entities: horse, mule, skeleton horse, donkey
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: cat
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: fox
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: goat, llama
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: iron golem
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: salmon, cod
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: squid, glow squid
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: wolf
  worlds: all
  distance: 5
  max-amount: 50

- entities: tropical fish, pufferfish
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: bee
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: camel
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: dolphin
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: parrot
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: ocelot
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: sniffer
  worlds: all
  distance: 5
  max-amount: 50

- entities: panda
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: rabbit
  worlds: all
  distance: 5
  max-amount: 50

- entities: snowman
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: turtle
  worlds: all
  distance: 5
  max-amount: 50

- entities: cave spider, creeper, drowned, elder guardian, enderman, endermite, ender dragon, evoker, ghast, giant, guardian, hoglin, husk, illusioner, magma cube, phantom, piglin, piglin brute, pillager, polar bear, ravager, silverfish, skeleton, slime, spider, stray, strider, vex, vindicator, warden, witch, wither, wither skeleton, zoglin, zombie, zombie horse, zombie villager, zombified piglin
  worlds: all
  distance: 5
  max-amount: 50
  
- entities: boat, chest boat, minecart, minecart chest,  minecart command, minecart hopper, minecart mob spawner 
  worlds: all
  distance: 5
  max-amount: 50
  

  
# A rule for spawner grinders, max of 10 mobs of the same type in the same block.
- entities: zombie, skeleton, spider, cave spider, creeper, blaze, wither skeleton, stray, drowned, husk, elder guardian, guardian, enderman
  worlds: all
  distance: 1
  max-amount: 10
  

group-separately:
  # Set to true to group MythicMobs separately as different entity types.
  mythic-mobs: false

extra:
  # The rate of mobs that will successfully spawn from a nether portal.
  # Setting to 0% disables mobs spawning from portals.
  portal-spawn-rate: '100%'
  # Whether to exclude tamed entities or not
  exclude-tamed: true
  # Whether to exclude entities with a name tag or not
  exclude-nametagged: false

**Comment by filoghost** [comment]
I'm sorry, I don't understand what do you want Farm Limiter to do. What do you mean by "grouping plugins"? It doesn't differentiate entities created by different plugins, it only checks entity types.

**Comment by A1yshia** [comment]
I would like it to check each entity separately. for example, 50 sheep + 50 cows = 100 instead of: 50 cows and sheep = 50

**Comment by filoghost** [comment]
Sorry, that is not possible.

**Comment by A1yshia** [comment]
no problem. thanks for your reply!
