### ISSUE TITLE
destroying hologram doesn't update for nearby players

### ISSUE THREAD

**Issue by rudde0** [filoghost/HolographicDisplays#724]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I'm using [skript-holo](https://github.com/Blueyescat/skript-holo) for HolographicDisplays hook. When I deleted a hologram it would delete from nearby players, as expected. It was working fine until [Experimental and potentially unstable: async packet sending](https://github.com/filoghost/HolographicDisplays/commit/0754e0ac330e8cb8ee480d5add68db8061372dde) patch. Now, players need to relog to stop seeing the old holograms.

### How to reproduce

1. Create a hologram with com.gmail.filoghost.holographicdisplays.api.HologramsAPI's createHologram method.
2. Delete a hologram with com.gmail.filoghost.holographicdisplays.api.Hologram's static delete method.

The hologram will be remain for viewers.

### Server version

git-Purpur-2143 (MC: 1.20.4)*

### Holographic Displays version

HolographicDisplays version 3.0.5-SNAPSHOT-b266

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards

### Additional information

I tested this only with 1.20.4 server & client.

**Comment by WhiteFreezing** [comment]
i have same problem :/

**Comment by filoghost** [comment]
Bug reproduced, should be fixed in the latest build.

**Comment by rudde0** [comment]
fixed now, ty
