### ISSUE TITLE
1.20.5/6 support

### ISSUE THREAD

**Issue by BySwiizen** [filoghost/HolographicDisplays#725]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Add support for 1.20.5/6 to the plugin.

### How to reproduce

1. Add the plugin to the folder.
2. Start the server.
3. See the error in console

### Server version

Spigot 1.20.6

### Holographic Displays version

HolographicDisplays 3.0.4

### Additional information

Here is the error message: https://pastebin.com/YBDFzMJ2

**Comment by Tsoccerguy3** [comment]
https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

Important changes to get this to load on Paper

**Comment by BySwiizen** [comment]
I don't think it will be updated...

**Comment by andrewkm** [comment]
Same issue here @filoghost 
Any chances this will be updated?

```
[12:54:12] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v3.0.5-SNAPSHOT-b144
[12:54:12] [Server thread/INFO]: [HolographicDisplays] Fatal error while enabling HolographicDisplays v3.0.5-SNAPSHOT-b144:

Holographic Displays only supports Spigot from 1.8 to 1.20.
The plugin has been disabled.
```

**Comment by crumpkatrina** [comment]
We too are experiencing issues loading on 1.20.6 😦

**Comment by Tsoccerguy3** [comment]
I'm sure someone will update this code to 1.21 next week , There is this if you need it for say Holoplots https://www.spigotmc.org/resources/decentholograms-1-8-1-20-6-papi-support-no-dependencies.96927/ 

It will convert your existing holograms to DecentHolograms . Do /Hologram convert HolographicDisplays

**Comment by filoghost** [comment]
No, sorry, it won't be updated anymore. I encourage using DecentHolograms or forking the code.

**Comment by andrewkm** [comment]
We've converted to DecentHolograms. The migrate commands made it easy as ever. Thanks for all your support throughout the years. Best to archive the repo now. :) @filoghost
