### ISSUE TITLE
MC 1.21

### ISSUE THREAD

**Issue by rudde0** [filoghost/HolographicDisplays#726]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I know this isn't the right place but there's no any button which is related to suggestions.

Could you add support for MC 1.21? Since HolographicDisplays working stable it's still needed for most server owners and updating to MC 1.21 would be nice.

### How to reproduce

-

### Server version

-

### Holographic Displays version

-

**Comment by filoghost** [comment]
Sorry, the plugin is not maintained anymore. I recommend switching to Decent Holograms (which has an import function), or similar plugins.
