### ISSUE TITLE
API - Get hologram by name?

### ISSUE THREAD

**Issue by period** [filoghost/HolographicDisplays#74]
Is it possible to get a hologram by its name? (i.e. one created by /hd create) or get the name of a hologram from its object?

**Comment by Oxro** [comment]
+1 for this

**Comment by xH3LLRAIZ3Rx** [comment]
+1 for this too

**Comment by filoghost** [comment]
There isn't one for a reason, that plugins shouldn't edit holograms of Holographic Displays itself. HD exposes an API to allow plugins to create their own holograms, but nothing more. More experienced developers can use the undocumented internal API.
