### ISSUE TITLE
HD + SilkSpawners Slime Spawners Problem

### ISSUE THREAD

**Issue by OrrinWolf** [filoghost/HolographicDisplays#76]
We recently switched over to using Holographic Displays versus another Hologram plugin, and our slime spawners stopped functioning completely. We are using SilkSpawners, and that plugin still lists this as an issue on their page. >> "Holographic Displays makes Slime spawners non functional"

We tested the slime spawners in several environments including:
Light levels below 7, and over 7 (this should not matter)
In a swamp, and out of a swamp.
On grass, and on other materials.
Even tested during a new moon, and all other conditions where slimes SHOULD be able to spawn.

Natural slimes spawn just fine. This only affects slimes spawning from a monster spawner, but it renders our server's spawner system ineffectual for this specific mob.

In case this is something that can be fixed, here is the info you may need.
Using spigot, Minecraft version 1.12.1, Silk Spawners, and the latest version of Holographics Displays.

NOTE: I saw that this issue has been a problem for some time, and was closed before. I had stumbled across a previous issue in the tracker and posted there before I realized it was closed. So, I apologize if this looks like a duplicate.

**Comment by Flavourized** [comment]
If it tells you it is a known issue, what are you expecting to get fixed, which they haven't already tried?

**Comment by filoghost** [comment]
Finally i can close this, the new beta doesn't use real entities anymore.
