### ISSUE TITLE
Holographic displays api Placeholders

### ISSUE THREAD

**Issue by FlashOnFire** [filoghost/HolographicDisplays#79]
Hello, I wanted an hologram for my plugin and I found this API. I have just one question about placeholders : 

is it possible to make a placeholder like {score} which will show the score of the player who see the holo without using the VisibilityManager ?

Like the {player} variable.

EDIT : I seen this PR : https://github.com/filoghost/HolographicDisplays/pull/48
so it would be very nice if you could implement it.

(@filoghost)

**Comment by FlashOnFire** [comment]
So I made some changes to make this PR compatible with the new updates of the plugin.I'll test all that today.

**Comment by FlashOnFire** [comment]
So I made some changes to make this PR compatible with the new updates of the plugin.I'll test all that today.

**Comment by Niall7459** [comment]
https://www.spigotmc.org/resources/holographic-extension.18461/
use with PlaceholderAPI https://www.spigotmc.org/resources/placeholderapi.6245/
