### ISSUE TITLE
Non collidable touchable holograms

### ISSUE THREAD

**Issue by Sataniel98** [filoghost/HolographicDisplays#80]
Hi,
is it possible to make touchable holograms not collidable? I noticed that they're not collidable until you make them touchable.

See DRE2N/HolographicMenus/issues/13

~ Best regards

**Comment by filoghost** [comment]
I've researched a bit on this issue, there is no good solution.

The only thing that could work is using Player#setCollidable(false), because the invisible slime used for touchable holograms already has collidable set to false.
