### ISSUE TITLE
Holograms attempted to load before worlds were loaded.

### ISSUE THREAD

**Issue by mibby** [filoghost/HolographicDisplays#82]
HolographicDisplay v2.3.0 (@markhughes's build here for java 9/10 support https://github.com/filoghost/HolographicDisplays/issues/70#issuecomment-337765890)
Paper dev 1424 (Spigot 1.12.2)

Restarted my server after adding a new map (making it the 10th one on the server) and for the first time, had Holograms attempt to load before worlds did.

https://paste.ubuntu.com/p/mrsHrKKWTt/

**Comment by filoghost** [comment]
This is weird. What plugin are you using to add more worlds? Can you try the official dev build on https://ci.codemc.org/job/CodeMC/job/HolographicDisplays (supports Java 9+ now)?

**Comment by Fader-GumGum** [comment]
Same here.
Running latest version of:
This server is running CraftBukkit version git-Spigot-500ff5d-1cead62 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
[HolographicDisplays] Loading HolographicDisplays v2.3.1-SNAPSHOT
[Multiverse-Core] Enabling Multiverse-Core v2.6.0-b738
[PlotSquared] Loading PlotSquared v18.09.09-eab918b-2040
https://pastebin.com/raw/GpLNVmqJ

**Comment by filoghost** [comment]
I think this is an issue with Spigot. I will try loading the holograms later, hopefully there won't be the need anymore to use softdepend in plugin.yml.

**Comment by Sikatsu** [comment]
You might be right, since it randomly started to occur and the only thing changed is spigot.

**Comment by filoghost** [comment]
Should be fixed here https://github.com/filoghost/HolographicDisplays/commit/8022a167ed831f166a628eec3b02c5e7b896e595 please try a new development build from https://ci.filoghost.me/job/HolographicDisplays/

**Comment by Sikatsu** [comment]
I'll test tomorrow!

**Comment by Fader-GumGum** [comment]
Seems to work OK. No more errors in the log. Thanks for this fix.
