### ISSUE TITLE
1.13 Update

### ISSUE THREAD

**Issue by Velasco83** [filoghost/HolographicDisplays#86]
"This version of HolographicDisplays only works on server versions from 1.7 to 1.12. The plugin will be disabled."

Please, update or make it compatible. A lot of thanks. Greetings.

**Comment by sgdc3** [comment]
i'm working on it, but i need to fix some issues caused by nms changes

**Comment by Velasco83** [comment]
I testing the version 2.3 of HolographicDisplays in the last dev buil of spigot 1.13 and work without issues (create, edit and remove HDs).

**Comment by sgdc3** [comment]
@Velasco83 nice to ear that, sadly filoghost will not merge my pr and will update it by it's own... rip

**Comment by filoghost** [comment]
Official development build is ready https://ci.filoghost.me/job/HolographicDisplays/lastStableBuild/

**Comment by DmitryRendov** [comment]
@filoghost thank you! one thing - i'm getting an exception 
`java.lang.IllegalArgumentException: Channel must contain : separator`
when {online: serverName} is used

**Comment by sgdc3** [comment]
@DmitryRendov pls try again with the latest dev build

**Comment by DmitryRendov** [comment]
yes, I'm using the latest 12 build. the full stack trace is here - https://pastebin.com/utMn4Dk7

**Comment by filoghost** [comment]
Fixed for the moment, but RedisBungee doesn't currently support 1.13 plugin channels, it will just display 0.
