### ISSUE TITLE
Error b21

### ISSUE THREAD

**Issue by FrankHeijden** [filoghost/HolographicDisplays#95]
https://paste.md-5.net/wevucicefe.avrasm
CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by sgdc3** [comment]
@FrankHeijden this is an issue with HolograpicExtension

**Comment by FrankHeijden** [comment]
Oh im so sorry, I did not see this lol. thanks.
