### ISSUE TITLE
HolographicDisplays lags

### ISSUE THREAD

**Issue by BestMark** [filoghost/HolographicDisplays#96]
Hello,

Recently, with the increase of online on my server, the TPS dropped heavily, and server began to freeze every minute (average online 240-270).
So, I did the JFR and I saw that the reason of the lags is HolographicDisplays.
![2018-08-22 15 04 13](https://user-images.githubusercontent.com/18399104/44462240-adcd2d00-a61c-11e8-95af-592212363fee.png)
Also I use Paper 1.12.2 (latest build)

Please, fix it as soon as possible, because I can't find a replacement for your wonderful plugin.

**Comment by filoghost** [comment]
That function is called frequently, but it shouldn't cause lag. I don't know much about that tool, but you should look at timings, rather than call counts, it probably takes just a few nanoseconds to execute.

Is there any other plugin creating lots of holograms?

Are you using Java 9+? I will improve that part of code for Java 9+ soon.

Side note, I need to add an option to disable this overhead: the reason I added it was to align holograms lines precisely, when teleported frequently. But if they aren't teleported frequently (like a chat bubble over a player's head) it's not needed.

**Comment by BestMark** [comment]
> Is there any other plugin creating lots of holograms?
No, I have only one plugin that uses HolographicDisplays ([it's code](https://hastebin.com/fenoxuredi.java)), but it doesn't creates a lot of holograms.
But there is one more plugin that creates a lot of holograms (chat bubble over a player's head) and it exactly uses own API, not HolographicDisplays.
> Are you using Java 9+?
No, I'm using Java 10 only on my computer. On my Linux server I use Server JRE 8u181.

**Comment by sgdc3** [comment]
@filoghost the issue is reflection, it is super slow in this scenario.

**Comment by BestMark** [comment]
Is the issue in my plugins? Chat Bubbles or the first plugin, which code I sent?

**Comment by BestMark** [comment]
As I said, I use Java 8. Issue happens on Java 8 server.

**Comment by sgdc3** [comment]
uh sorry misread your post

**Comment by BestMark** [comment]
OK, I hope you'll fix this bug. I think it's important for many servers using this plugin.

**Comment by BestMark** [comment]
Hello,
Should I wait for the fix? On my server it is impossible to play (4 TPS) because of the load from your plugin.

**Comment by sgdc3** [comment]
@BestMark it has been fixed, please try again with the latest dev build

**Comment by BestMark** [comment]
Ok, I will try

**Comment by BestMark** [comment]
@sgdc3, update didn't help to resolve this lags.
![2018-08-31 13 10 20](https://user-images.githubusercontent.com/18399104/44907046-6121da00-ad1f-11e8-8619-d2feb08535e8.png)

**Comment by filoghost** [comment]
Please get the timings instead of method calls count. Also try removing the plugin to see if the lag goes away.

The freeze is odd, because that method is called frequently, and the server should lag constantly if that is the cause (instead of just freezing every 15-20 seconds).

**Comment by BestMark** [comment]
As I already said, problem resolves when I delete HolographicDisplays.

**Comment by BestMark** [comment]
If you need, I can send you JFR file.

**Comment by filoghost** [comment]
A new build is out, with the option to disable this part of code that may be slowing your server. Please try it, a new config.yml node will appear: "precise-hologram-teleport" (set it to false)
