### ISSUE TITLE
Holograms not appearing to certain players

### ISSUE THREAD

**Issue by Shadowdragon8969** [filoghost/HolographicDisplays#97]
I have been trying to make holograms that display above the player's name tag.

First I create the hologram on join
Constantly teleport it to the player and update the message 
Then Delete it when they leave

However when a player leaves and rejoins their holo only displays for them
Am I missing something?
I have tried showing and resetting visibility

Is there anything else I'm missing? Or is this a bug?

Also I am using 1.13 if that changes anything.

**Comment by filoghost** [comment]
Code? By default holograms are visible to everyone.
