### ISSUE TITLE
Will not enable on 1.13.1

### ISSUE THREAD

**Issue by Sikatsu** [filoghost/HolographicDisplays#98]
Plugin disables on 1.13.1.

**Comment by sgdc3** [comment]
@Sikatsu error log pls

**Comment by Sikatsu** [comment]
Just doesn't enable. Could send the error log in the evening.

Op zo 26 aug. 2018 13:01 schreef Gabriele C. <notifications@github.com>:

**Comment by Sikatsu** [comment]
******************************************************
     This version of HolographicDisplays only
     works on server versions from 1.7 to 1.13.
     The plugin will be disabled.
******************************************************

**Comment by sgdc3** [comment]
ah ok

**Comment by sgdc3** [comment]
@filoghost you should add an option to remove the version check, as usually minor releases doesn't have nms changes

**Comment by FrankHeijden** [comment]
no 1.13.1 has different NMS, v1_13_R2

**Comment by sgdc3** [comment]
yep i noticed xD damn md5

**Comment by FrankHeijden** [comment]
thats not md_5

**Comment by sgdc3** [comment]
i know, that's why i edited the comment :P HD would be broken on 1.13.1 event without nms versioning, as mojang changed how the intenral registers works.

**Comment by filoghost** [comment]
A new build is out, working on 1.13.1.
